/**
 * 分野別語彙（商务谈判 / 高尔夫 / AI・机器人・无人车）。
 * **自動生成。手で編集しない。**
 *
 *   pnpm build:domain
 *
 * 出典: JMdict（https://www.edrdg.org/jmdict/j_jmdict.html）
 *       配布は scriptin/jmdict-simplified の JSON 版、版 3.6.2+20260810124713
 *       **ライセンス: CC BY-SA 4.0** —— 派生物の再配布時は同ライセンス。
 *
 * 分野の決め方：JMdict の分野タグ（`bus` `golf`）で引けるものはタグで決める。
 * AI・ロボット・自動運転にはタグが無いので術語を `scripts/build-domain-vocab.ts`
 * に列挙してあるが、**語そのものは全部 JMdict から引いている**。
 *
 * 例文は付かない。Tatoeba にこの三分野の文は実質存在しないため
 * （品質タグと中文訳まで通すと 5 / 7 / 1 文）、単語カードだけ。
 */

export interface DomainEntry {
  /**
   * `分野の頭文字 + 連番`（`g12` など）。表記を入れない——Telegram の
   * コールバックは 64 バイトまでで、長い外来語を二つ載せると超える。
   */
  readonly id: string;
  readonly domain: string;
  readonly expression: string;
  /** 仮名の読み。振り仮名と音声合成に使う。 */
  readonly reading: string;
  /** JMdict の英語語義（先頭三つまで）。 */
  readonly meaning: string;
}

export interface Domain {
  readonly id: string;
  readonly name: string;
}

export const DOMAINS: readonly Domain[] = [
  { id: 'business', name: '商务谈判' },
  { id: 'golf', name: '高尔夫与球场经营' },
  { id: 'tech', name: 'AI・机器人・无人车' },
];

export const DOMAIN_VOCAB: readonly DomainEntry[] = [
  { id: 'b1', domain: 'business', expression: 'インボイス', reading: 'インボイス', meaning: 'invoice' },
  { id: 'b2', domain: 'business', expression: 'コンシューマリング', reading: 'コンシューマリング', meaning: 'consumer-first (marketing, manufacturing, etc.)' },
  { id: 'b3', domain: 'business', expression: 'バックマージン', reading: 'バックマージン', meaning: 'retroactive discount paid to a retailer by a distributor' },
  { id: 'b4', domain: 'business', expression: 'パーソナルセリング', reading: 'パーソナルセリング', meaning: 'personal selling' },
  { id: 'b5', domain: 'business', expression: 'ビハインド', reading: 'ビハインド', meaning: 'being behind schedule' },
  { id: 'b6', domain: 'business', expression: 'ベンチャーキャピタル', reading: 'ベンチャーキャピタル', meaning: 'venture capital' },
  { id: 'b7', domain: 'business', expression: 'ユースマーケット', reading: 'ユースマーケット', meaning: 'youth market' },
  { id: 'b8', domain: 'business', expression: '仮定款', reading: 'かりていかん', meaning: 'provisional articles of incorporation' },
  { id: 'b9', domain: 'business', expression: '企画書', reading: 'きかくしょ', meaning: '(written) proposal' },
  { id: 'b10', domain: 'business', expression: '企業プラン', reading: 'きぎょうプラン', meaning: 'corporate plan' },
  { id: 'b11', domain: 'business', expression: '企業戦略', reading: 'きぎょうせんりゃく', meaning: 'corporate strategy' },
  { id: 'b12', domain: 'business', expression: '最高経営責任者', reading: 'さいこうけいえいせきにんしゃ', meaning: 'chief executive officer, CEO' },
  { id: 'b13', domain: 'business', expression: '消費者', reading: 'しょうひしゃ', meaning: 'consumer (of a product, service, etc.), customer, (end) user' },
  { id: 'b14', domain: 'business', expression: '鞘', reading: 'さや', meaning: 'margin (between two prices), spread, markup' },
  { id: 'b15', domain: 'business', expression: '生産者', reading: 'せいさんしゃ', meaning: 'producer, grower, maker' },
  { id: 'b16', domain: 'business', expression: '粗利益', reading: 'あらりえき', meaning: 'gross profit, gross margin' },
  { id: 'b17', domain: 'business', expression: '属名', reading: 'ぞくめい', meaning: 'generic name' },
  { id: 'b18', domain: 'business', expression: '叩き', reading: 'たたき', meaning: 'springboard for discussion, draft proposal, tentative plan' },
  { id: 'b19', domain: 'business', expression: '暖簾', reading: 'のれん', meaning: 'goodwill' },
  { id: 'b20', domain: 'business', expression: '値動き', reading: 'ねうごき', meaning: 'price movement, price fluctuation' },
  { id: 'b21', domain: 'business', expression: '展開', reading: 'てんかい', meaning: 'sharing (information)' },
  { id: 'b22', domain: 'business', expression: '目標管理', reading: 'もくひょうかんり', meaning: 'management by objectives, MBO' },
  { id: 'b23', domain: 'business', expression: '離反', reading: 'りはん', meaning: '(customer) churn, attrition' },
  { id: 'b24', domain: 'business', expression: '付け替える', reading: 'つけかえる', meaning: 'to reassign (an expense), to charge (to a different account)' },
  { id: 'b25', domain: 'business', expression: '有限責任', reading: 'ゆうげんせきにん', meaning: 'limited liability' },
  { id: 'b26', domain: 'business', expression: '当用買い', reading: 'とうようがい', meaning: 'buying for immediate requirements' },
  { id: 'b27', domain: 'business', expression: '内部留保', reading: 'ないぶりゅうほ', meaning: 'internal reserves, retained profit' },
  { id: 'b28', domain: 'business', expression: 'たたき台', reading: 'たたきだい', meaning: 'springboard for discussion, draft proposal, tentative plan' },
  { id: 'b29', domain: 'business', expression: 'マーケットイン', reading: 'マーケットイン', meaning: 'market orientation' },
  { id: 'b30', domain: 'business', expression: '付加価値', reading: 'ふかかち', meaning: 'added value' },
  { id: 'b31', domain: 'business', expression: 'ＡＢＣ', reading: 'エー・ビー・シー', meaning: 'activity-based costing, ABC' },
  { id: 'b32', domain: 'business', expression: '一人会社', reading: 'いちにんかいしゃ', meaning: 'one-man company' },
  { id: 'b33', domain: 'business', expression: '純利益', reading: 'じゅんりえき', meaning: 'net income, net profit' },
  { id: 'b34', domain: 'business', expression: '成長戦略', reading: 'せいちょうせんりゃく', meaning: 'growth strategy' },
  { id: 'b35', domain: 'business', expression: '証憑', reading: 'しょうひょう', meaning: 'voucher, documentary evidence of a transaction' },
  { id: 'b36', domain: 'business', expression: '毒薬条項', reading: 'どくやくじょうこう', meaning: 'poison pill (anti-takeover measure)' },
  { id: 'b37', domain: 'business', expression: 'ポイズンピル', reading: 'ポイズンピル', meaning: 'poison pill (anti-takeover measure)' },
  { id: 'b38', domain: 'business', expression: '先入れ先出し', reading: 'さきいれさきだし', meaning: 'first in, first out, FIFO' },
  { id: 'b39', domain: 'business', expression: '希望小売価格', reading: 'きぼうこうりかかく', meaning: 'manufacturer\'s suggested retail price, MSRP' },
  { id: 'b40', domain: 'business', expression: '市場シェア', reading: 'しじょうシェア', meaning: 'market share' },
  { id: 'b41', domain: 'business', expression: '頭出し', reading: 'あたまだし', meaning: 'brief overview, heads-up, brief discussion' },
  { id: 'b42', domain: 'business', expression: 'ＣＥＯ', reading: 'シー・イー・オー', meaning: 'chief executive officer, CEO' },
  { id: 'b43', domain: 'business', expression: '内部統制', reading: 'ないぶとうせい', meaning: 'internal controls, internal governance' },
  { id: 'b44', domain: 'business', expression: 'イニシャルコスト', reading: 'イニシャルコスト', meaning: 'initial cost, startup cost' },
  { id: 'b45', domain: 'business', expression: 'ＣＲＭ', reading: 'シー・アール・エム', meaning: 'customer relationship management, CRM' },
  { id: 'b46', domain: 'business', expression: 'シックスシグマ', reading: 'シックスシグマ', meaning: 'six sigma' },
  { id: 'b47', domain: 'business', expression: 'ベンダー側', reading: 'ベンダーがわ', meaning: 'vendor side' },
  { id: 'b48', domain: 'business', expression: 'ユーザー側', reading: 'ユーザーがわ', meaning: 'user side' },
  { id: 'b49', domain: 'business', expression: '戦略情報システム', reading: 'せんりゃくじょうほうシステム', meaning: 'strategic information system, SIS' },
  { id: 'b50', domain: 'business', expression: '付加価値再販業者', reading: 'ふかかちさいはんぎょうしゃ', meaning: 'value-added reseller, VAR' },
  { id: 'b51', domain: 'business', expression: '方向性', reading: 'ほうこうせい', meaning: 'goal, aim' },
  { id: 'b52', domain: 'business', expression: 'ＳＩＳ', reading: 'シス', meaning: 'strategic information system (SIS)' },
  { id: 'b53', domain: 'business', expression: 'ゾンビ会社', reading: 'ゾンビかいしゃ', meaning: 'zombie company' },
  { id: 'b54', domain: 'business', expression: 'リスケ', reading: 'リスケ', meaning: 'rescheduling (a meeting, debt, etc.)' },
  { id: 'b55', domain: 'business', expression: 'ＭＩＳ', reading: 'エム・アイ・エス', meaning: 'management information system, MIS' },
  { id: 'b56', domain: 'business', expression: 'カテゴリーキラー', reading: 'カテゴリーキラー', meaning: 'category killer (retail)' },
  { id: 'b57', domain: 'business', expression: 'コストパーサウザンド', reading: 'コストパーサウザンド', meaning: 'cost per thousand (in digital advertising), cost per mille' },
  { id: 'b58', domain: 'business', expression: '委員会設置会社', reading: 'いいんかいせっちかいしゃ', meaning: 'company with a committee governance structure' },
  { id: 'b59', domain: 'business', expression: '報連相', reading: 'ほうれんそう', meaning: 'reporting, contacting, and consultation' },
  { id: 'b60', domain: 'business', expression: '管理会社', reading: 'かんりがいしゃ', meaning: 'proprietary company' },
  { id: 'b61', domain: 'business', expression: '冒険資本', reading: 'ぼうけんしほん', meaning: 'venture capital' },
  { id: 'b62', domain: 'business', expression: '製品群', reading: 'せいひんぐん', meaning: 'family of products, product aggregate, product family' },
  { id: 'b63', domain: 'business', expression: '社内便', reading: 'しゃないびん', meaning: 'interoffice mail, in-house mail' },
  { id: 'b64', domain: 'business', expression: 'オランダ病', reading: 'オランダびょう', meaning: 'Dutch disease' },
  { id: 'b65', domain: 'business', expression: '海外移転', reading: 'かいがいいてん', meaning: 'offshoring, overseas transfer (esp. of production)' },
  { id: 'b66', domain: 'business', expression: '即戦力', reading: 'そくせんりょく', meaning: 'ready fire-power, battle-ready forces' },
  { id: 'b67', domain: 'business', expression: '中間法人', reading: 'ちゅうかんほうじん', meaning: 'intermediate corporation (abolished in 2008)' },
  { id: 'b68', domain: 'business', expression: '機会損失', reading: 'きかいそんしつ', meaning: 'missing an opportunity, opportunity loss' },
  { id: 'b69', domain: 'business', expression: 'チャンスロス', reading: 'チャンスロス', meaning: 'opportunity loss, loss of a sales opportunity' },
  { id: 'b70', domain: 'business', expression: '大家族主義', reading: 'だいかぞくしゅぎ', meaning: 'big family principle, extended family policy' },
  { id: 'b71', domain: 'business', expression: '原資産', reading: 'げんしさん', meaning: 'underlying asset, underlying security, underlier' },
  { id: 'b72', domain: 'business', expression: '勘定科目', reading: 'かんじょうかもく', meaning: 'account name, account title' },
  { id: 'b73', domain: 'business', expression: '回転率', reading: 'かいてんりつ', meaning: 'turnover rate (merchandise, capital)' },
  { id: 'b74', domain: 'business', expression: '機会ロス', reading: 'きかいロス', meaning: 'missing an opportunity, opportunity loss' },
  { id: 'b75', domain: 'business', expression: 'レポートライン', reading: 'レポートライン', meaning: 'reporting line (business management)' },
  { id: 'b76', domain: 'business', expression: 'ＳＩｅｒ', reading: 'エスアイヤー', meaning: 'systems integrator, system integrator (company)' },
  { id: 'b77', domain: 'business', expression: 'ブルーオーシャン', reading: 'ブルーオーシャン', meaning: 'blue ocean (strategy)' },
  { id: 'b78', domain: 'business', expression: '顧客関係管理', reading: 'こきゃくかんけいかんり', meaning: 'customer relationship management, CRM' },
  { id: 'b79', domain: 'business', expression: 'フランチャイジー', reading: 'フランチャイジー', meaning: 'franchisee' },
  { id: 'b80', domain: 'business', expression: '非上場', reading: 'ひじょうじょう', meaning: 'unlisted (company, stock)' },
  { id: 'b81', domain: 'business', expression: 'ＥＶ', reading: 'イー・ブイ', meaning: 'enterprise value, EV' },
  { id: 'b82', domain: 'business', expression: '見込み客', reading: 'みこみきゃく', meaning: 'prospective client, sales lead' },
  { id: 'b83', domain: 'business', expression: '超過収益力', reading: 'ちょうかしゅうえきりょく', meaning: 'excess earning power' },
  { id: 'b84', domain: 'business', expression: 'ゾンビ企業', reading: 'ゾンビきぎょう', meaning: 'zombie company, corporate zombie' },
  { id: 'b85', domain: 'business', expression: 'ネガティブオプション', reading: 'ネガティブオプション', meaning: 'negative option (billing)' },
  { id: 'b86', domain: 'business', expression: '活動基準原価計算', reading: 'かつどうきじゅんげんかけいさん', meaning: 'activity-based costing, ABC' },
  { id: 'b87', domain: 'business', expression: '射倖契約', reading: 'しゃこうけいやく', meaning: 'aleatory contract' },
  { id: 'b88', domain: 'business', expression: 'ガラスの崖', reading: 'ガラスのがけ', meaning: 'glass cliff (corporate leadership)' },
  { id: 'b89', domain: 'business', expression: 'プロダクトアウト', reading: 'プロダクトアウト', meaning: 'product orientation' },
  { id: 'b90', domain: 'business', expression: '指名委員会', reading: 'しめいいいんかい', meaning: 'nominating committee, nomination committee' },
  { id: 'b91', domain: 'business', expression: '報酬委員会', reading: 'ほうしゅういいんかい', meaning: 'compensation committee, remuneration committee' },
  { id: 'b92', domain: 'business', expression: '社外取締役', reading: 'しゃがいとりしまりやく', meaning: 'outside director, independent director' },
  { id: 'b93', domain: 'business', expression: '社外監査役', reading: 'しゃがいかんさやく', meaning: 'external auditor' },
  { id: 'b94', domain: 'business', expression: '最終事業年度', reading: 'さいしゅうじぎょうねんど', meaning: 'most recent business year' },
  { id: 'b95', domain: 'business', expression: '組織変更', reading: 'そしきへんこう', meaning: 'entity conversion, change of company form' },
  { id: 'b96', domain: 'business', expression: '新設合併', reading: 'しんせつがっぺい', meaning: 'consolidation, consolidation-type merger' },
  { id: 'b97', domain: 'business', expression: '吸収分割', reading: 'きゅうしゅうぶんかつ', meaning: 'absorption-type company split' },
  { id: 'b98', domain: 'business', expression: '新設分割', reading: 'しんせつぶんかつ', meaning: 'incorporation-type company split' },
  { id: 'b99', domain: 'business', expression: '表見支配人', reading: 'ひょうけんしはいにん', meaning: 'apparent manager, office chief of the business' },
  { id: 'b100', domain: 'business', expression: '代理商', reading: 'だいりしょう', meaning: 'commercial agent, commission merchant' },
  { id: 'b101', domain: 'business', expression: '譲渡会社', reading: 'ゆずりわたしがいしゃ', meaning: 'transferor company' },
  { id: 'b102', domain: 'business', expression: '譲受会社', reading: 'ゆずりうけがいしゃ', meaning: 'transferee company' },
  { id: 'b103', domain: 'business', expression: '会計帳簿', reading: 'かいけいちょうぼ', meaning: 'account book, book of account, ledger' },
  { id: 'b104', domain: 'business', expression: '特定社員', reading: 'とくていしゃいん', meaning: 'specified partner' },
  { id: 'b105', domain: 'business', expression: '平取', reading: 'ひらとり', meaning: 'non-executive director, nonmanagerial director' },
  { id: 'b106', domain: 'business', expression: '平取締役', reading: 'ひらとりしまりやく', meaning: 'non-executive director, nonmanagerial director' },
  { id: 'b107', domain: 'business', expression: '参考価格', reading: 'さんこうかかく', meaning: 'reference price' },
  { id: 'b108', domain: 'business', expression: '法人課税', reading: 'ほうじんかぜい', meaning: 'corporate taxation' },
  { id: 'b109', domain: 'business', expression: '組合契約', reading: 'くみあいけいやく', meaning: 'partnership contract' },
  { id: 'b110', domain: 'business', expression: '消費者契約', reading: 'しょうひしゃけいやく', meaning: 'consumer contract' },
  { id: 'b111', domain: 'business', expression: 'コストセンター', reading: 'コストセンター', meaning: 'cost center, cost centre' },
  { id: 'b112', domain: 'business', expression: 'プロフィットセンター', reading: 'プロフィットセンター', meaning: 'profit center, profit centre' },
  { id: 'b113', domain: 'business', expression: '受託事業', reading: 'じゅたくじぎょう', meaning: 'entrusted business, contractor, outsourcing business' },
  { id: 'b114', domain: 'business', expression: 'エンタイトルメント', reading: 'エンタイトルメント', meaning: 'entitlement' },
  { id: 'b115', domain: 'business', expression: 'ＶＡＲ', reading: 'ブイ・エー・アール', meaning: 'value-added reseller, VAR' },
  { id: 'b116', domain: 'business', expression: 'Ｍ＆Ａ', reading: 'エム・アンド・エー', meaning: 'M&A, mergers and acquisitions' },
  { id: 'b117', domain: 'business', expression: 'カスタマーサクセス', reading: 'カスタマーサクセス', meaning: 'customer success' },
  { id: 'b118', domain: 'business', expression: 'オンボーディング', reading: 'オンボーディング', meaning: 'onboarding, organizational socialization' },
  { id: 'b119', domain: 'business', expression: 'パーパス', reading: 'パーパス', meaning: 'purpose, business purpose, corporate purpose' },
  { id: 'b120', domain: 'business', expression: '予実', reading: 'よじつ', meaning: 'forecast and actual results, budget and actual amounts' },
  { id: 'b121', domain: 'business', expression: '死の谷', reading: 'しのたに', meaning: 'valley of death' },
  { id: 'b122', domain: 'business', expression: 'アーリーアダプター', reading: 'アーリーアダプター', meaning: 'early adopter' },
  { id: 'b123', domain: 'business', expression: 'アタックリスト', reading: 'アタックリスト', meaning: 'list of prospective customers, leads, etc.' },
  { id: 'b124', domain: 'business', expression: '受注率', reading: 'じゅちゅうりつ', meaning: 'order acceptance rate, win rate' },
  { id: 'b125', domain: 'business', expression: 'イネーブルメント', reading: 'イネーブルメント', meaning: '(sales) enablement' },
  { id: 'b126', domain: 'business', expression: 'フルフィルメント', reading: 'フルフィルメント', meaning: 'fulfilment (of an order), fulfillment' },
  { id: 'b127', domain: 'business', expression: '非営利法人', reading: 'ひえいりほうじん', meaning: 'nonprofit corporation' },
  { id: 'b128', domain: 'business', expression: '持分会社', reading: 'もちぶんがいしゃ', meaning: 'mochibun gaisha' },
  { id: 'b129', domain: 'business', expression: '生涯価値', reading: 'しょうがいかち', meaning: '(customer) lifetime value, LTV' },
  { id: 'b130', domain: 'business', expression: 'バーンダウン', reading: 'バーンダウン', meaning: 'burndown chart, burn down' },
  { id: 'b131', domain: 'business', expression: 'バーンダウンチャート', reading: 'バーンダウンチャート', meaning: 'burndown chart' },
  { id: 'b132', domain: 'business', expression: '赤伝', reading: 'あかでん', meaning: 'slip to cancel existing transactions' },
  { id: 'b133', domain: 'business', expression: '黒伝', reading: 'くろでん', meaning: 'slip for regular business transactions' },
  { id: 'b134', domain: 'business', expression: '資本業務提携', reading: 'しほんぎょうむていけい', meaning: 'capital and business alliance, business and capital tie-up' },
  { id: 'b135', domain: 'business', expression: 'リピート率', reading: 'リピートりつ', meaning: 'repeat customer rate, returning customer rate' },
  { id: 'b136', domain: 'business', expression: 'コミュニケーションコスト', reading: 'コミュニケーションコスト', meaning: 'time and effort taken by communicating' },
  { id: 'b137', domain: 'business', expression: '統括部', reading: 'とうかつぶ', meaning: 'operational unit, supervisory department, control division' },
  { id: 'b138', domain: 'business', expression: 'トスアップ', reading: 'トスアップ', meaning: 'introducing a customer or lead to other employees or departm' },
  { id: 'b139', domain: 'business', expression: 'ビジネスエンジェル', reading: 'ビジネスエンジェル', meaning: 'business angel, start-up investor' },
  { id: 'b140', domain: 'business', expression: 'ネットプロモータースコア', reading: 'ネットプロモータースコア', meaning: 'net promoter score, NPS' },
  { id: 'b141', domain: 'business', expression: '傷害特約', reading: 'しょうがいとくやく', meaning: 'rider on a life insurance policy' },
  { id: 'b142', domain: 'business', expression: 'ポモドーロ', reading: 'ポモドーロ', meaning: 'Pomodoro Technique (time management system)' },
  { id: 'b143', domain: 'business', expression: 'ファンド会社', reading: 'ファンドがいしゃ', meaning: 'investment company, investment firm' },
  { id: 'b144', domain: 'business', expression: '対物信用', reading: 'たいぶつしんよう', meaning: 'collateral credit, credit in respect to real property' },
  { id: 'b145', domain: 'business', expression: 'グローバルバリューチェーン', reading: 'グローバルバリューチェーン', meaning: 'global value chain, GVC' },
  { id: 'b146', domain: 'business', expression: 'バリューチェーン', reading: 'バリューチェーン', meaning: 'value chain' },
  { id: 'b147', domain: 'business', expression: '差別化戦略', reading: 'さべつかせんりゃく', meaning: 'differentiation strategy, product differentiation' },
  { id: 'b148', domain: 'business', expression: '需要家', reading: 'じゅようか', meaning: 'consumer (of a product, service, etc.), customer, end user' },
  { id: 'b149', domain: 'business', expression: '単元株', reading: 'たんげんかぶ', meaning: 'trading unit (of shares)' },
  { id: 'b150', domain: 'business', expression: '先行者利益', reading: 'せんこうしゃりえき', meaning: 'first-mover advantage' },
  { id: 'b151', domain: 'business', expression: 'アンドを取る', reading: 'アンドをとる', meaning: 'to find a time when everyone\'s schedule is free' },
  { id: 'b152', domain: 'business', expression: '情物一致', reading: 'じょうぶついっち', meaning: 'consistency between recorded stock information and actual st' },
  { id: 'b153', domain: 'business', expression: 'ＭＢＯ', reading: 'エム・ビー・オー', meaning: 'management by objectives, MBO' },
  { id: 'b154', domain: 'business', expression: '目標による管理', reading: 'もくひょうによるかんり', meaning: 'management by objectives, MBO' },
  { id: 'b155', domain: 'business', expression: 'ＫＹＣ', reading: 'ケー・ワイ・シー', meaning: 'know your customer, KYC' },
  { id: 'b156', domain: 'business', expression: 'ニアショア', reading: 'ニアショア', meaning: 'outsourcing development, etc. to regional cities' },
  { id: 'b157', domain: 'business', expression: '株主優待', reading: 'かぶぬしゆうたい', meaning: 'shareholder benefit' },
  { id: 'b158', domain: 'business', expression: 'ファシリーダー', reading: 'ファシリーダー', meaning: '(main) facilitator (e.g. for a meeting)' },
  { id: 'b159', domain: 'business', expression: 'ＢＰＭ', reading: 'ビー・ピー・エム', meaning: 'business process management, BPM' },
  { id: 'b160', domain: 'business', expression: '執行者', reading: 'しっこうしゃ', meaning: 'executive, officer' },
  { id: 'b161', domain: 'business', expression: 'ＢＰＯ', reading: 'ビー・ピー・オー', meaning: 'business process outsourcing, BPO' },
  { id: 'b162', domain: 'business', expression: '黒字リストラ', reading: 'くろじリストラ', meaning: 'reducing staff despite being profitable' },
  { id: 'b163', domain: 'business', expression: '役員人事', reading: 'やくいんじんじ', meaning: 'change of company director, reassignment of executives' },
  { id: 'b164', domain: 'business', expression: 'アクハイヤー', reading: 'アクハイヤー', meaning: 'acquihire, acqui-hire' },
  { id: 'b165', domain: 'business', expression: '指図人', reading: 'さしずにん', meaning: 'order (as in payable to order)' },
  { id: 'b166', domain: 'business', expression: '受注調整', reading: 'じゅちゅうちょうせい', meaning: 'bid rigging' },
  { id: 'g1', domain: 'golf', expression: 'アイアン', reading: 'アイアン', meaning: 'iron' },
  { id: 'g2', domain: 'golf', expression: 'ＯＵＴ', reading: 'アウト', meaning: 'front nine' },
  { id: 'g3', domain: 'golf', expression: 'アテスト', reading: 'アテスト', meaning: 'to attest (a scorecard), to sign' },
  { id: 'g4', domain: 'golf', expression: 'アドレス', reading: 'アドレス', meaning: 'addressing (the ball)' },
  { id: 'g5', domain: 'golf', expression: 'アプローチ', reading: 'アプローチ', meaning: 'approach shot' },
  { id: 'g6', domain: 'golf', expression: 'アプローチショット', reading: 'アプローチショット', meaning: 'approach shot' },
  { id: 'g7', domain: 'golf', expression: 'アベレージゴルファー', reading: 'アベレージゴルファー', meaning: 'average golfer' },
  { id: 'g8', domain: 'golf', expression: 'アルバトロス', reading: 'アルバトロス', meaning: 'albatross (score), double eagle' },
  { id: 'g9', domain: 'golf', expression: 'アンダーパー', reading: 'アンダーパー', meaning: 'under par' },
  { id: 'g10', domain: 'golf', expression: 'アンプレアブル', reading: 'アンプレアブル', meaning: 'unplayable (ball)' },
  { id: 'g11', domain: 'golf', expression: 'イーグル', reading: 'イーグル', meaning: 'eagle' },
  { id: 'g12', domain: 'golf', expression: 'イーブンパー', reading: 'イーブンパー', meaning: 'even par' },
  { id: 'g13', domain: 'golf', expression: 'ＩＮ', reading: 'イン', meaning: 'back nine' },
  { id: 'g14', domain: 'golf', expression: 'ウッド', reading: 'ウッド', meaning: 'wood (club)' },
  { id: 'g15', domain: 'golf', expression: 'エージシューター', reading: 'エージシューター', meaning: 'age shooter' },
  { id: 'g16', domain: 'golf', expression: 'エキストラホール', reading: 'エキストラホール', meaning: 'extra hole' },
  { id: 'g17', domain: 'golf', expression: 'Ｈ', reading: 'エッチ', meaning: 'hole' },
  { id: 'g18', domain: 'golf', expression: 'オーバー', reading: 'オーバー', meaning: 'over par' },
  { id: 'g19', domain: 'golf', expression: 'オーバードライブ', reading: 'オーバードライブ', meaning: 'outdriving (another player)' },
  { id: 'g20', domain: 'golf', expression: 'オーバーパー', reading: 'オーバーパー', meaning: 'over par' },
  { id: 'g21', domain: 'golf', expression: 'ＯＢ', reading: 'オー・ビー', meaning: 'out of bounds' },
  { id: 'g22', domain: 'golf', expression: 'オフィシャルハンデ', reading: 'オフィシャルハンデ', meaning: 'official handicap' },
  { id: 'g23', domain: 'golf', expression: 'ＯＮ', reading: 'オン', meaning: 'being on the green (of one\'s ball)' },
  { id: 'g24', domain: 'golf', expression: 'カット', reading: 'カット', meaning: 'cutting (the ball)' },
  { id: 'g25', domain: 'golf', expression: 'キャディー', reading: 'キャディー', meaning: 'caddie, caddy' },
  { id: 'g26', domain: 'golf', expression: 'クラブフェース', reading: 'クラブフェース', meaning: 'club face' },
  { id: 'g27', domain: 'golf', expression: 'クリーク', reading: 'クリーク', meaning: '5-wood (club)' },
  { id: 'g28', domain: 'golf', expression: 'クロスバンカー', reading: 'クロスバンカー', meaning: 'cross bunker' },
  { id: 'g29', domain: 'golf', expression: 'グリーン', reading: 'グリーン', meaning: 'green, putting green' },
  { id: 'g30', domain: 'golf', expression: 'グリーンフィー', reading: 'グリーンフィー', meaning: 'green fee' },
  { id: 'g31', domain: 'golf', expression: 'サンドウェッジ', reading: 'サンドウェッジ', meaning: 'sand wedge' },
  { id: 'g32', domain: 'golf', expression: 'シャンク', reading: 'シャンク', meaning: 'shank' },
  { id: 'g33', domain: 'golf', expression: 'ショートアイアン', reading: 'ショートアイアン', meaning: 'short iron' },
  { id: 'g34', domain: 'golf', expression: 'ショートホール', reading: 'ショートホール', meaning: 'par-three hole' },
  { id: 'g35', domain: 'golf', expression: 'シングル', reading: 'シングル', meaning: 'single-figure handicap' },
  { id: 'g36', domain: 'golf', expression: 'シングルプレーヤー', reading: 'シングルプレーヤー', meaning: 'golfer with a single-figure handicap' },
  { id: 'g37', domain: 'golf', expression: 'スタイミー', reading: 'スタイミー', meaning: 'situation in which there is an obstacle between the ball and' },
  { id: 'g38', domain: 'golf', expression: 'ストロークプレー', reading: 'ストロークプレー', meaning: 'stroke play, medal play' },
  { id: 'g39', domain: 'golf', expression: 'スライス', reading: 'スライス', meaning: 'slice' },
  { id: 'g40', domain: 'golf', expression: 'トゥ', reading: 'トゥ', meaning: 'toe (of a club)' },
  { id: 'g41', domain: 'golf', expression: 'ドーミー', reading: 'ドーミー', meaning: 'dormie' },
  { id: 'g42', domain: 'golf', expression: 'ドーミーホール', reading: 'ドーミーホール', meaning: 'hole at which a player becomes dormie' },
  { id: 'g43', domain: 'golf', expression: 'ドライバー', reading: 'ドライバー', meaning: 'driver (club)' },
  { id: 'g44', domain: 'golf', expression: 'ドラコン', reading: 'ドラコン', meaning: 'driving contest, longest drive contest' },
  { id: 'g45', domain: 'golf', expression: 'ドロー', reading: 'ドロー', meaning: 'draw (shot)' },
  { id: 'g46', domain: 'golf', expression: 'ドローボール', reading: 'ドローボール', meaning: 'draw (shot)' },
  { id: 'g47', domain: 'golf', expression: 'ドロップ', reading: 'ドロップ', meaning: 'dropping (an unplayable ball)' },
  { id: 'g48', domain: 'golf', expression: 'ニアピン', reading: 'ニアピン', meaning: 'closest to pin' },
  { id: 'g49', domain: 'golf', expression: 'ハーフ', reading: 'ハーフ', meaning: '9-hole half (of a round)' },
  { id: 'g50', domain: 'golf', expression: 'ハーフスイング', reading: 'ハーフスイング', meaning: 'half swing' },
  { id: 'g51', domain: 'golf', expression: 'バーディー', reading: 'バーディー', meaning: 'birdie' },
  { id: 'g52', domain: 'golf', expression: 'バッフィー', reading: 'バッフィー', meaning: 'baffy' },
  { id: 'g53', domain: 'golf', expression: 'バンカー', reading: 'バンカー', meaning: 'bunker' },
  { id: 'g54', domain: 'golf', expression: 'パー', reading: 'パー', meaning: 'par' },
  { id: 'g55', domain: 'golf', expression: 'パープレー', reading: 'パープレー', meaning: 'scoring even-par for the entire round' },
  { id: 'g56', domain: 'golf', expression: 'パター', reading: 'パター', meaning: 'putter' },
  { id: 'g57', domain: 'golf', expression: 'パット', reading: 'パット', meaning: 'putt' },
  { id: 'g58', domain: 'golf', expression: 'ピン', reading: 'ピン', meaning: 'pin, flagstick' },
  { id: 'g59', domain: 'golf', expression: 'フェアウェイ', reading: 'フェアウェイ', meaning: 'fairway' },
  { id: 'g60', domain: 'golf', expression: 'フック', reading: 'フック', meaning: 'hook' },
  { id: 'g61', domain: 'golf', expression: 'フックライン', reading: 'フックライン', meaning: 'right-to-left-breaking putt' },
  { id: 'g62', domain: 'golf', expression: 'フレックス', reading: 'フレックス', meaning: 'flex (in a golf shaft)' },
  { id: 'g63', domain: 'golf', expression: 'ブラックシャフト', reading: 'ブラックシャフト', meaning: 'golf club with a graphite shaft' },
  { id: 'g64', domain: 'golf', expression: 'ブラッシー', reading: 'ブラッシー', meaning: 'brassie, 2-wood' },
  { id: 'g65', domain: 'golf', expression: 'プレース', reading: 'プレース', meaning: 'placing (a ball when taking relief)' },
  { id: 'g66', domain: 'golf', expression: 'ホールアウト', reading: 'ホールアウト', meaning: 'hole out' },
  { id: 'g67', domain: 'golf', expression: 'ホールインワン', reading: 'ホールインワン', meaning: 'hole in one' },
  { id: 'g68', domain: 'golf', expression: 'ボギー', reading: 'ボギー', meaning: 'bogey' },
  { id: 'g69', domain: 'golf', expression: 'マウンド', reading: 'マウンド', meaning: 'mound' },
  { id: 'g70', domain: 'golf', expression: 'マッチプレー', reading: 'マッチプレー', meaning: 'match play' },
  { id: 'g71', domain: 'golf', expression: 'ミドルホール', reading: 'ミドルホール', meaning: 'par-four hole' },
  { id: 'g72', domain: 'golf', expression: 'ライ', reading: 'ライ', meaning: 'lie' },
  { id: 'g73', domain: 'golf', expression: 'ラウンド', reading: 'ラウンド', meaning: 'round' },
  { id: 'g74', domain: 'golf', expression: 'ラフ', reading: 'ラフ', meaning: 'rough' },
  { id: 'g75', domain: 'golf', expression: 'リカバリーショット', reading: 'リカバリーショット', meaning: 'recovery shot' },
  { id: 'g76', domain: 'golf', expression: 'ロングホール', reading: 'ロングホール', meaning: 'par-five hole' },
  { id: 'g77', domain: 'golf', expression: '刻む', reading: 'きざむ', meaning: 'to lay up, to play a conservative shot' },
  { id: 'g78', domain: 'golf', expression: 'ダボ', reading: 'ダボ', meaning: 'double bogey' },
  { id: 'g79', domain: 'golf', expression: 'ティーグラウンド', reading: 'ティーグラウンド', meaning: 'tee, teeing ground' },
  { id: 'g80', domain: 'golf', expression: 'インサイドアウト', reading: 'インサイドアウト', meaning: 'inside-out (swing)' },
  { id: 'g81', domain: 'golf', expression: 'インターロッキンググリップ', reading: 'インターロッキンググリップ', meaning: 'interlocking grip' },
  { id: 'g82', domain: 'golf', expression: 'レイアップ', reading: 'レイアップ', meaning: 'lay-up (shot)' },
  { id: 'g83', domain: 'golf', expression: '哥', reading: 'グロス', meaning: 'gross score' },
  { id: 'g84', domain: 'golf', expression: 'チップショット', reading: 'チップショット', meaning: 'chip shot' },
  { id: 'g85', domain: 'golf', expression: 'トリプルボギー', reading: 'トリプルボギー', meaning: 'triple bogey' },
  { id: 'g86', domain: 'golf', expression: 'ダブルボギー', reading: 'ダブルボギー', meaning: 'double bogey' },
  { id: 'g87', domain: 'golf', expression: 'ドッグレッグ', reading: 'ドッグレッグ', meaning: 'dogleg, dogleg hole' },
  { id: 'g88', domain: 'golf', expression: 'ティーアップ', reading: 'ティーアップ', meaning: 'teeing up' },
  { id: 'g89', domain: 'golf', expression: 'ティーショット', reading: 'ティーショット', meaning: 'tee shot' },
  { id: 'g90', domain: 'golf', expression: 'パーセーブ', reading: 'パーセーブ', meaning: 'par save, saving par' },
  { id: 'g91', domain: 'golf', expression: 'パーオン', reading: 'パーオン', meaning: 'green in regulation' },
  { id: 'g92', domain: 'golf', expression: '打ち下ろし', reading: 'うちおろし', meaning: 'downhill (hole)' },
  { id: 'g93', domain: 'golf', expression: 'ダブルイーグル', reading: 'ダブルイーグル', meaning: 'double eagle, albatross' },
  { id: 'g94', domain: 'golf', expression: 'チップイン', reading: 'チップイン', meaning: 'chip-in' },
  { id: 'g95', domain: 'golf', expression: 'ロングアイアン', reading: 'ロングアイアン', meaning: 'long iron' },
  { id: 'g96', domain: 'golf', expression: 'ドライビングコンテスト', reading: 'ドライビングコンテスト', meaning: 'driving contest' },
  { id: 'g97', domain: 'golf', expression: 'ドライビング', reading: 'ドライビング', meaning: 'driving' },
  { id: 'g98', domain: 'golf', expression: '最終ホール', reading: 'さいしゅうホール', meaning: 'last hole, finishing hole' },
  { id: 'g99', domain: 'golf', expression: 'ワンペナ', reading: 'ワンペナ', meaning: 'one-stroke penalty' },
  { id: 'g100', domain: 'golf', expression: 'パンチショット', reading: 'パンチショット', meaning: 'punch shot' },
  { id: 'g101', domain: 'golf', expression: 'ホステスプロ', reading: 'ホステスプロ', meaning: 'female golf pro sponsored by the tournament host' },
  { id: 'g102', domain: 'golf', expression: 'アンカリング', reading: 'アンカリング', meaning: 'anchoring (the club)' },
  { id: 'g103', domain: 'golf', expression: '罰打', reading: 'ばつだ', meaning: 'penalty, penalty stroke' },
  { id: 'g104', domain: 'golf', expression: 'セルフプレー', reading: 'セルフプレー', meaning: 'playing without a caddy' },
  { id: 'g105', domain: 'golf', expression: 'ダフ', reading: 'ダフ', meaning: 'duff, sclaff' },
  { id: 'g106', domain: 'golf', expression: 'ダフる', reading: 'ダフる', meaning: 'to duff, to sclaff' },
  { id: 'g107', domain: 'golf', expression: 'クォリファイングトーナメント', reading: 'クォリファイングトーナメント', meaning: 'qualifying tournament' },
  { id: 'g108', domain: 'golf', expression: 'ＱＴ', reading: 'キュー・ティー', meaning: 'qualifying tournament' },
  { id: 'g109', domain: 'golf', expression: 'ナイスオン', reading: 'ナイスオン', meaning: 'nice shot!' },
  { id: 'g110', domain: 'golf', expression: 'ホール', reading: 'ホール', meaning: 'hole, cup' },
  { id: 'g111', domain: 'golf', expression: 'カップイン', reading: 'カップイン', meaning: 'holing, going in the hole' },
  { id: 'g112', domain: 'golf', expression: '明治の大砲', reading: 'めいじのたいほう', meaning: 'poor swing, hanging back during the swing, Meiji-era cannon' },
  { id: 'g113', domain: 'golf', expression: 'ノーズロ', reading: 'ノーズロ', meaning: 'chip-in' },
  { id: 'g114', domain: 'golf', expression: 'フォア', reading: 'フォア', meaning: 'fore' },
  { id: 'g115', domain: 'golf', expression: 'チップ', reading: 'チップ', meaning: 'chip (shot)' },
  { id: 'g116', domain: 'golf', expression: 'オーバーラッピンググリップ', reading: 'オーバーラッピンググリップ', meaning: 'overlapping grip' },
  { id: 'g117', domain: 'golf', expression: 'ティー', reading: 'ティー', meaning: 'tee, teeing ground' },
  { id: 'g118', domain: 'golf', expression: 'ミニコース', reading: 'ミニコース', meaning: 'short course' },
  { id: 'g119', domain: 'golf', expression: '芝目', reading: 'しばめ', meaning: 'grain (of the grass)' },
  { id: 'g120', domain: 'golf', expression: '逆目', reading: 'ぎゃくめ', meaning: '(putting) against the grain' },
  { id: 'g121', domain: 'golf', expression: 'ＦＷ', reading: 'エフ・ダブリュー', meaning: 'fairway wood (club)' },
  { id: 'g122', domain: 'golf', expression: 'コック', reading: 'コック', meaning: '(wrist) cock' },
  { id: 'g123', domain: 'golf', expression: 'エージシュート', reading: 'エージシュート', meaning: 'shooting one\'s age' },
  { id: 'g124', domain: 'golf', expression: 'マッシー', reading: 'マッシー', meaning: 'mashie' },
  { id: 't1', domain: 'tech', expression: '人工知能', reading: 'じんこうちのう', meaning: 'artificial intelligence, AI' },
  { id: 't2', domain: 'tech', expression: '機械学習', reading: 'きかいがくしゅう', meaning: 'machine learning' },
  { id: 't3', domain: 'tech', expression: '深層学習', reading: 'しんそうがくしゅう', meaning: 'deep learning' },
  { id: 't4', domain: 'tech', expression: '学習', reading: 'がくしゅう', meaning: 'learning, study' },
  { id: 't5', domain: 'tech', expression: '認識', reading: 'にんしき', meaning: 'recognition, awareness, perception' },
  { id: 't6', domain: 'tech', expression: '推論', reading: 'すいろん', meaning: 'inference, deduction, induction' },
  { id: 't7', domain: 'tech', expression: '知能', reading: 'ちのう', meaning: 'intelligence, intellect, brains' },
  { id: 't8', domain: 'tech', expression: 'ロボット', reading: 'ロボット', meaning: 'robot' },
  { id: 't9', domain: 'tech', expression: 'ロボット工学', reading: 'ロボットこうがく', meaning: 'robotics' },
  { id: 't10', domain: 'tech', expression: '産業用ロボット', reading: 'さんぎょうようロボット', meaning: 'industrial robot' },
  { id: 't11', domain: 'tech', expression: '自律', reading: 'じりつ', meaning: 'autonomy, self-control, self-discipline' },
  { id: 't12', domain: 'tech', expression: '自動化', reading: 'じどうか', meaning: 'automation' },
  { id: 't13', domain: 'tech', expression: '自動運転', reading: 'じどううんてん', meaning: 'automatic operation (machine), automatic driving (vehicle)' },
  { id: 't14', domain: 'tech', expression: '無人', reading: 'むじん', meaning: 'unmanned, uninhabited, unattended' },
  { id: 't15', domain: 'tech', expression: '運転', reading: 'うんてん', meaning: 'operation (of a machine), running, working' },
  { id: 't16', domain: 'tech', expression: '車両', reading: 'しゃりょう', meaning: '(wheeled) vehicle, car, (railroad) car' },
  { id: 't17', domain: 'tech', expression: '自動車', reading: 'じどうしゃ', meaning: 'car, automobile, motorcar' },
  { id: 't18', domain: 'tech', expression: 'センサー', reading: 'センサー', meaning: 'sensor' },
  { id: 't19', domain: 'tech', expression: 'カメラ', reading: 'カメラ', meaning: 'camera' },
  { id: 't20', domain: 'tech', expression: 'レーダー', reading: 'レーダー', meaning: 'radar' },
  { id: 't21', domain: 'tech', expression: '装置', reading: 'そうち', meaning: 'equipment, device, installation' },
  { id: 't22', domain: 'tech', expression: '制御', reading: 'せいぎょ', meaning: 'control (of a machine, device, etc.)' },
  { id: 't23', domain: 'tech', expression: '制御装置', reading: 'せいぎょそうち', meaning: 'controller, control unit' },
  { id: 't24', domain: 'tech', expression: '半導体', reading: 'はんどうたい', meaning: 'semiconductor' },
  { id: 't25', domain: 'tech', expression: '回路', reading: 'かいろ', meaning: 'circuit' },
  { id: 't26', domain: 'tech', expression: '電池', reading: 'でんち', meaning: 'battery, cell' },
  { id: 't27', domain: 'tech', expression: '部品', reading: 'ぶひん', meaning: 'parts, accessories, components' },
  { id: 't28', domain: 'tech', expression: '駆動', reading: 'くどう', meaning: 'drive, driving (force)' },
  { id: 't29', domain: 'tech', expression: 'モーター', reading: 'モーター', meaning: 'motor, engine' },
  { id: 't30', domain: 'tech', expression: 'データ', reading: 'データ', meaning: 'data, datum' },
  { id: 't31', domain: 'tech', expression: 'データベース', reading: 'データベース', meaning: 'database' },
  { id: 't32', domain: 'tech', expression: 'アルゴリズム', reading: 'アルゴリズム', meaning: 'algorithm' },
  { id: 't33', domain: 'tech', expression: 'プログラム', reading: 'プログラム', meaning: 'program (of events, music, etc.), programme' },
  { id: 't34', domain: 'tech', expression: '演算', reading: 'えんざん', meaning: 'operation, calculation' },
  { id: 't35', domain: 'tech', expression: '計算', reading: 'けいさん', meaning: 'calculation, computation, reckoning' },
  { id: 't36', domain: 'tech', expression: '処理', reading: 'しょり', meaning: 'processing, dealing with, treatment' },
  { id: 't37', domain: 'tech', expression: '情報', reading: 'じょうほう', meaning: 'information, news, report' },
  { id: 't38', domain: 'tech', expression: '信号', reading: 'しんごう', meaning: 'signal, signalling, signaling' },
  { id: 't39', domain: 'tech', expression: '解析', reading: 'かいせき', meaning: 'analysis, analytical study' },
  { id: 't40', domain: 'tech', expression: '分析', reading: 'ぶんせき', meaning: 'analysis' },
  { id: 't41', domain: 'tech', expression: '統計', reading: 'とうけい', meaning: 'statistics' },
  { id: 't42', domain: 'tech', expression: '確率', reading: 'かくりつ', meaning: 'probability, likelihood, chances' },
  { id: 't43', domain: 'tech', expression: '画像', reading: 'がぞう', meaning: 'image, picture, portrait' },
  { id: 't44', domain: 'tech', expression: '音声', reading: 'おんせい', meaning: 'voice, speech, sound of a voice' },
  { id: 't45', domain: 'tech', expression: '言語', reading: 'げんご', meaning: 'language' },
  { id: 't46', domain: 'tech', expression: '翻訳', reading: 'ほんやく', meaning: 'translation' },
  { id: 't47', domain: 'tech', expression: '予測', reading: 'よそく', meaning: 'prediction, estimation' },
  { id: 't48', domain: 'tech', expression: '判断', reading: 'はんだん', meaning: 'judgment, judgement, decision' },
  { id: 't49', domain: 'tech', expression: '精度', reading: 'せいど', meaning: 'precision, accuracy' },
  { id: 't50', domain: 'tech', expression: '技術', reading: 'ぎじゅつ', meaning: 'technology, engineering' },
  { id: 't51', domain: 'tech', expression: '開発', reading: 'かいはつ', meaning: 'development, cultivation, application' },
  { id: 't52', domain: 'tech', expression: '研究', reading: 'けんきゅう', meaning: 'research, study, investigation' },
  { id: 't53', domain: 'tech', expression: '設計', reading: 'せっけい', meaning: 'plan, design, layout' },
  { id: 't54', domain: 'tech', expression: '実験', reading: 'じっけん', meaning: 'experiment, experimentation' },
  { id: 't55', domain: 'tech', expression: '性能', reading: 'せいのう', meaning: 'ability, performance, efficiency' },
  { id: 't56', domain: 'tech', expression: '効率', reading: 'こうりつ', meaning: 'efficiency' },
  { id: 't57', domain: 'tech', expression: '最適化', reading: 'さいてきか', meaning: 'optimization, optimisation' },
  { id: 't58', domain: 'tech', expression: '実装', reading: 'じっそう', meaning: 'implementation (e.g. of a feature)' },
  { id: 't59', domain: 'tech', expression: '試験', reading: 'しけん', meaning: 'examination, exam, test' },
  { id: 't60', domain: 'tech', expression: '検査', reading: 'けんさ', meaning: 'inspection (e.g. customs, factory), examination, test' },
  { id: 't61', domain: 'tech', expression: '故障', reading: 'こしょう', meaning: 'fault, trouble, breakdown' },
  { id: 't62', domain: 'tech', expression: '安全', reading: 'あんぜん', meaning: 'safety, security' },
  { id: 't63', domain: 'tech', expression: '事故', reading: 'じこ', meaning: 'accident, incident, trouble' },
  { id: 't64', domain: 'tech', expression: '規格', reading: 'きかく', meaning: 'standard, norm' },
  { id: 't65', domain: 'tech', expression: '特許', reading: 'とっきょ', meaning: 'patent' },
  { id: 't66', domain: 'tech', expression: '工場', reading: 'こうじょう', meaning: 'factory, plant, mill' },
  { id: 't67', domain: 'tech', expression: '産業', reading: 'さんぎょう', meaning: 'industry' },
  { id: 't68', domain: 'tech', expression: '製造', reading: 'せいぞう', meaning: 'manufacture, production' },
  { id: 't69', domain: 'tech', expression: '量産', reading: 'りょうさん', meaning: 'mass production' },
];

export const DOMAIN_BY_ID: ReadonlyMap<string, Domain> = new Map(
  DOMAINS.map((entry) => [entry.id, entry]),
);

export const DOMAIN_VOCAB_BY_ID: ReadonlyMap<string, DomainEntry> = new Map(
  DOMAIN_VOCAB.map((entry) => [entry.id, entry]),
);

export function domainVocabOf(domainId: string): DomainEntry[] {
  return DOMAIN_VOCAB.filter((entry) => entry.domain === domainId);
}

/** knowledge_items.key に入る形。型が DOMAIN なので接頭辞で衝突しない。 */
export function domainKey(id: string): string {
  return `domain_${id}`;
}

export function domainVocabOfKey(key: string): DomainEntry | undefined {
  return key.startsWith('domain_')
    ? DOMAIN_VOCAB_BY_ID.get(key.slice('domain_'.length))
    : undefined;
}
