/**
 * JLPT N4 語彙（V2 §8）。**自動生成。手で編集しない。**
 *
 *   pnpm build:vocab
 *
 * 出典: elzup/jlpt-word-list（MIT License, © 2020 Jamie Sinclair / elzup）
 *       https://raw.githubusercontent.com/elzup/jlpt-word-list/master/src/n4.csv
 *
 * 語義は出典どおりの英語。中国語に機械翻訳して取り込むと、確かめようの
 * 無い誤りが「正解データ」として混ざる——語義は事実なので出典に委ねる
 * （§8）。学習者への中国語の説明は、必要なときにチューターが行う。
 *
 * 並びは Genki の課順を骨にし、その後ろに Genki に無い語を出典の並びの
 * まま置く。詳細は scripts/build-jlpt-vocab.ts を参照。
 */
import type { VocabEntry } from './vocabTypes.js';

export const VOCAB_N4: readonly VocabEntry[] = [
  { id: '大学生#だいがくせい', level: 'N4', expression: '大学生', reading: 'だいがくせい', meaning: 'college student, university student', genkiLesson: 1 },
  { id: '科学#かがく', level: 'N4', expression: '科学', reading: 'かがく', meaning: 'science', genkiLesson: 1 },
  { id: 'アメリカ#アメリカ', level: 'N4', expression: 'アメリカ', reading: 'アメリカ', meaning: 'America, U.S.A.', genkiLesson: 1 },
  { id: '歴史#れきし', level: 'N4', expression: '歴史', reading: 'れきし', meaning: 'history', genkiLesson: 1 },
  { id: '専門#せんもん', level: 'N4', expression: '専門', reading: 'せんもん', meaning: 'major; speciality', genkiLesson: 1 },
  { id: '政治#せいじ', level: 'N4', expression: '政治', reading: 'せいじ', meaning: 'politics', genkiLesson: 1 },
  { id: '高校生#こうこうせい', level: 'N4', expression: '高校生', reading: 'こうこうせい', meaning: 'high school student', genkiLesson: 1 },
  { id: '文学#ぶんがく', level: 'N4', expression: '文学', reading: 'ぶんがく', meaning: 'literature', genkiLesson: 1 },
  { id: '大抵#たいてい', level: 'N4', expression: '大抵', reading: 'たいてい', meaning: 'generally, usually', genkiLesson: 3 },
  { id: 'テニス#テニス', level: 'N4', expression: 'テニス', reading: 'テニス', meaning: 'tennis', genkiLesson: 3 },
  { id: 'アルバイト#アルバイト', level: 'N4', expression: 'アルバイト', reading: 'アルバイト', meaning: 'part-time job', genkiLesson: 4 },
  { id: 'だから#だから', level: 'N4', expression: 'だから', reading: 'だから', meaning: 'so; therefore', genkiLesson: 4 },
  { id: 'さっき#さっき', level: 'N4', expression: 'さっき', reading: 'さっき', meaning: 'a little while ago', genkiLesson: 4 },
  { id: 'お土産#おみやげ', level: 'N4', expression: 'お土産', reading: 'おみやげ', meaning: 'souvenir', genkiLesson: 4 },
  { id: '僕#ぼく', level: 'N4', expression: '僕', reading: 'ぼく', meaning: 'I (used by men towards those of equal or lower status)', genkiLesson: 5 },
  { id: '怖い#こわい', level: 'N4', expression: '怖い', reading: 'こわい', meaning: 'scary, frightening', genkiLesson: 5 },
  { id: '優しい#やさしい', level: 'N4', expression: '優しい', reading: 'やさしい', meaning: 'kind (person), gentle (person), easy (problem)', genkiLesson: 5 },
  { id: '急ぐ#いそぐ', level: 'N4', expression: '急ぐ', reading: 'いそぐ', meaning: 'to hurry, to be in a hurry, to rush', genkiLesson: 6 },
  { id: '痩せる#やせる', level: 'N4', expression: '痩せる', reading: 'やせる', meaning: 'to lose weight', genkiLesson: 7 },
  { id: 'もちろん#もちろん', level: 'N4', expression: 'もちろん', reading: 'もちろん', meaning: 'certainly, of course', genkiLesson: 7 },
  { id: '髪#かみ', level: 'N4', expression: '髪', reading: 'かみ', meaning: 'hair', genkiLesson: 7 },
  { id: '太る#ふとる', level: 'N4', expression: '太る', reading: 'ふとる', meaning: 'to gain weight', genkiLesson: 7 },
  { id: 'うん#うん', level: 'N4', expression: 'うん', reading: 'うん', meaning: 'yes (informal), all right (ok)', genkiLesson: 8 },
  { id: '思う#おもう', level: 'N4', expression: '思う', reading: 'おもう', meaning: 'to think, to feel', genkiLesson: 8 },
  { id: '始める#はじめる', level: 'N4', expression: '始める', reading: 'はじめる', meaning: 'to start, to begin', genkiLesson: 8 },
  { id: '空気#くうき', level: 'N4', expression: '空気', reading: 'くうき', meaning: 'air, atmosphere', genkiLesson: 8 },
  { id: '天気予報#てんきよほう', level: 'N4', expression: '天気予報', reading: 'てんきよほう', meaning: 'weather forecast', genkiLesson: 8 },
  { id: '今度#こんど', level: 'N4', expression: '今度', reading: 'こんど', meaning: 'now, this time, near future, one of these days, next time', genkiLesson: 9 },
  { id: '踊る#おどる', level: 'N4', expression: '踊る', reading: 'おどる', meaning: 'to dance', genkiLesson: 9 },
  { id: '寂しい#さびしい', level: 'N4', expression: '寂しい', reading: 'さびしい', meaning: 'lonely, lonesome', genkiLesson: 9 },
  { id: '試験#しけん', level: 'N4', expression: '試験', reading: 'しけん', meaning: 'an exam', genkiLesson: 9 },
  { id: '是非#ぜひ', level: 'N4', expression: '是非', reading: 'ぜひ', meaning: 'certainly, by all means; without fail', genkiLesson: 9 },
  { id: 'コンサート#コンサート', level: 'N4', expression: 'コンサート', reading: 'コンサート', meaning: 'concert', genkiLesson: 9 },
  { id: 'ピアノ#ピアノ', level: 'N4', expression: 'ピアノ', reading: 'ピアノ', meaning: 'piano', genkiLesson: 9 },
  { id: '床屋#とこや', level: 'N4', expression: '床屋', reading: 'とこや', meaning: 'barber\'s (shop)', genkiLesson: 10 },
  { id: '季節#きせつ', level: 'N4', expression: '季節', reading: 'きせつ', meaning: 'season (in reference to weather)', genkiLesson: 10 },
  { id: '世界#せかい', level: 'N4', expression: '世界', reading: 'せかい', meaning: 'world', genkiLesson: 10 },
  { id: '決める#きめる', level: 'N4', expression: '決める', reading: 'きめる', meaning: 'to decide (v.t.)', genkiLesson: 10 },
  { id: '手袋#てぶくろ', level: 'N4', expression: '手袋', reading: 'てぶくろ', meaning: 'glove(s)', genkiLesson: 10 },
  { id: '予約#よやく', level: 'N4', expression: '予約', reading: 'よやく', meaning: 'reservation', genkiLesson: 10 },
  { id: '払う#はらう', level: 'N4', expression: '払う', reading: 'はらう', meaning: 'to pay', genkiLesson: 10 },
  { id: '眠い#ねむい', level: 'N4', expression: '眠い', reading: 'ねむい', meaning: 'sleepy, drowsy', genkiLesson: 10 },
  { id: 'この頃#このごろ', level: 'N4', expression: 'この頃', reading: 'このごろ', meaning: 'these days, nowadays', genkiLesson: 10 },
  { id: '社長#しゃちょう', level: 'N4', expression: '社長', reading: 'しゃちょう', meaning: 'president of a company', genkiLesson: 11 },
  { id: '美術館#びじゅつかん', level: 'N4', expression: '美術館', reading: 'びじゅつかん', meaning: 'art gallery, art museum', genkiLesson: 11 },
  { id: 'おもちゃ#おもちゃ', level: 'N4', expression: 'おもちゃ', reading: 'おもちゃ', meaning: 'a toy', genkiLesson: 11 },
  { id: '夢#ゆめ', level: 'N4', expression: '夢', reading: 'ゆめ', meaning: 'a dream', genkiLesson: 11 },
  { id: '久しぶり#ひさしぶり', level: 'N4', expression: '久しぶり', reading: 'ひさしぶり', meaning: 'it has been a long time; for the first time in a long time', genkiLesson: 11 },
  { id: '将来#しょうらい', level: 'N4', expression: '将来', reading: 'しょうらい', meaning: '(in the) future; prospects', genkiLesson: 11 },
  { id: '湖#みずうみ', level: 'N4', expression: '湖', reading: 'みずうみ', meaning: 'lake', genkiLesson: 11 },
  { id: '彼#かれ', level: 'N4', expression: '彼', reading: 'かれ', meaning: 'he, boyfriend', genkiLesson: 12 },
  { id: '用事#ようじ', level: 'N4', expression: '用事', reading: 'ようじ', meaning: 'business to take care of; tasks; errands', genkiLesson: 12 },
  { id: '試合#しあい', level: 'N4', expression: '試合', reading: 'しあい', meaning: 'match, game, competition', genkiLesson: 12 },
  { id: 'プレゼント#プレゼント', level: 'N4', expression: 'プレゼント', reading: 'プレゼント', meaning: 'present, gift', genkiLesson: 12 },
  { id: '彼女#かのじょ', level: 'N4', expression: '彼女', reading: 'かのじょ', meaning: 'girlfriend; she', genkiLesson: 12 },
  { id: 'もうすぐ#もうすぐ', level: 'N4', expression: 'もうすぐ', reading: 'もうすぐ', meaning: 'very soon; in a few moments; days', genkiLesson: 12 },
  { id: 'お宅#おたく', level: 'N4', expression: 'お宅', reading: 'おたく', meaning: '(someone else\'s) house; home -- polite word for 家 (いえ) --', genkiLesson: 13 },
  { id: '厳しい#きびしい', level: 'N4', expression: '厳しい', reading: 'きびしい', meaning: 'hard; rigorous; strict', genkiLesson: 13 },
  { id: '悲しい#かなしい', level: 'N4', expression: '悲しい', reading: 'かなしい', meaning: 'sad, sorrowful', genkiLesson: 13 },
  { id: '頑張る#がんばる', level: 'N4', expression: '頑張る', reading: 'がんばる', meaning: 'to try one\'s best, to try hard, to persist', genkiLesson: 13 },
  { id: '文法#ぶんぽう', level: 'N4', expression: '文法', reading: 'ぶんぽう', meaning: 'grammar', genkiLesson: 13 },
  { id: '泣く#なく', level: 'N4', expression: '泣く', reading: 'なく', meaning: 'to cry', genkiLesson: 13 },
  { id: '着物#きもの', level: 'N4', expression: '着物', reading: 'きもの', meaning: 'kimono; Japanese traditional dress', genkiLesson: 13 },
  { id: '約束#やくそく', level: 'N4', expression: '約束', reading: 'やくそく', meaning: 'arrangement, appointment, promise', genkiLesson: 13 },
  { id: 'ケーキ#ケーキ', level: 'N4', expression: 'ケーキ', reading: 'ケーキ', meaning: 'cake', genkiLesson: 13 },
  { id: '漫画#まんが', level: 'N4', expression: '漫画', reading: 'まんが', meaning: 'comic (book), cartoon', genkiLesson: 14 },
  { id: 'ご主人#ごしゅじん', level: 'N4', expression: 'ご主人', reading: 'ごしゅじん', meaning: '(your, her) husband', genkiLesson: 14 },
  { id: '送る#おくる', level: 'N4', expression: '送る', reading: 'おくる', meaning: 'to send, to dispatch', genkiLesson: 14 },
  { id: '指輪#ゆびわ', level: 'N4', expression: '指輪', reading: 'ゆびわ', meaning: '(finger) ring', genkiLesson: 14 },
  { id: '地震#じしん', level: 'N4', expression: '地震', reading: 'じしん', meaning: 'earthquake', genkiLesson: 15 },
  { id: '捨てる#すてる', level: 'N4', expression: '捨てる', reading: 'すてる', meaning: 'throw away (trash), dump, discard', genkiLesson: 15 },
  { id: '予定#よてい', level: 'N4', expression: '予定', reading: 'よてい', meaning: 'plans, arrangement, schedule', genkiLesson: 15 },
  { id: '探す#さがす', level: 'N4', expression: '探す', reading: 'さがす', meaning: 'to search, to seek, to look for', genkiLesson: 15 },
  { id: '旅館#りょかん', level: 'N4', expression: '旅館', reading: 'りょかん', meaning: 'a Japanese inn', genkiLesson: 15 },
  { id: '最近#さいきん', level: 'N4', expression: '最近', reading: 'さいきん', meaning: 'recently, nowadays, in recent years, most recent, latest', genkiLesson: 15 },
  { id: '見える#みえる', level: 'N4', expression: '見える', reading: 'みえる', meaning: 'to be visible; -- polite verb meaning 来る (くる) --', genkiLesson: 15 },
  { id: '番組#ばんぐみ', level: 'N4', expression: '番組', reading: 'ばんぐみ', meaning: 'broadcast program', genkiLesson: 15 },
  { id: 'ごみ#ごみ', level: 'N4', expression: 'ごみ', reading: 'ごみ', meaning: 'trash, garbage', genkiLesson: 16 },
  { id: '台風#たいふう', level: 'N4', expression: '台風', reading: 'たいふう', meaning: 'typhoon', genkiLesson: 16 },
  { id: '日#ひ', level: 'N4', expression: '日', reading: 'ひ', meaning: 'sun, sunshine, day', genkiLesson: 16 },
  { id: '起こす#おこす', level: 'N4', expression: '起こす', reading: 'おこす', meaning: 'to wake (someone) up', genkiLesson: 16 },
  { id: '親#おや', level: 'N4', expression: '親', reading: 'おや', meaning: 'a parent', genkiLesson: 16 },
  { id: '集める#あつめる', level: 'N4', expression: '集める', reading: 'あつめる', meaning: 'to collect, to gather (v.t.), to assemble', genkiLesson: 16 },
  { id: '直す#なおす', level: 'N4', expression: '直す', reading: 'なおす', meaning: 'to correct (v.t.); to fix', genkiLesson: 16 },
  { id: 'この間#このあいだ', level: 'N4', expression: 'この間', reading: 'このあいだ', meaning: 'the other day, recently', genkiLesson: 16 },
  { id: '足りる#たりる', level: 'N4', expression: '足りる', reading: 'たりる', meaning: 'to be sufficient; to be enough', genkiLesson: 17 },
  { id: '選ぶ#えらぶ', level: 'N4', expression: '選ぶ', reading: 'えらぶ', meaning: 'to choose; to select', genkiLesson: 17 },
  { id: '例えば#たとえば', level: 'N4', expression: '例えば', reading: 'たとえば', meaning: 'for example, e.g.', genkiLesson: 17 },
  { id: 'ひげ#ひげ', level: 'N4', expression: 'ひげ', reading: 'ひげ', meaning: 'beard', genkiLesson: 17 },
  { id: '恥ずかしい#はずかしい', level: 'N4', expression: '恥ずかしい', reading: 'はずかしい', meaning: 'ashamed, embarrassed', genkiLesson: 18 },
  { id: 'まず#まず', level: 'N4', expression: 'まず', reading: 'まず', meaning: 'first (of all), to start with', genkiLesson: 18 },
  { id: '日記#にっき', level: 'N4', expression: '日記', reading: 'にっき', meaning: 'diary, journal', genkiLesson: 18 },
  { id: 'カーテン#カーテン', level: 'N4', expression: 'カーテン', reading: 'カーテン', meaning: 'curtain', genkiLesson: 18 },
  { id: '考える#かんがえる', level: 'N4', expression: '考える', reading: 'かんがえる', meaning: 'to think (about); to consider', genkiLesson: 18 },
  { id: '怒る#おこる', level: 'N4', expression: '怒る', reading: 'おこる', meaning: 'to get angry; to scold angrily', genkiLesson: 19 },
  { id: 'いらっしゃる#いらっしゃる', level: 'N4', expression: 'いらっしゃる', reading: 'いらっしゃる', meaning: '-- honorific expression for いく, くる, and いる --', genkiLesson: 19 },
  { id: '寄る#よる', level: 'N4', expression: '寄る', reading: 'よる', meaning: 'to stop by', genkiLesson: 19 },
  { id: 'なさる#なさる', level: 'N4', expression: 'なさる', reading: 'なさる', meaning: '-- honorific expression for する --', genkiLesson: 19 },
  { id: 'お礼#おれい', level: 'N4', expression: 'お礼', reading: 'おれい', meaning: 'expression of gratitude; thanking; gift of appreciation; bow', genkiLesson: 19 },
  { id: '部長#ぶちょう', level: 'N4', expression: '部長', reading: 'ぶちょう', meaning: 'department (division) manager', genkiLesson: 19 },
  { id: 'お子さん#おこさん', level: 'N4', expression: 'お子さん', reading: 'おこさん', meaning: '(someone else\'s) child (polite)', genkiLesson: 19 },
  { id: '遅れる#おくれる', level: 'N4', expression: '遅れる', reading: 'おくれる', meaning: 'to (be) become late', genkiLesson: 19 },
  { id: '召し上がる#めしあがる', level: 'N4', expression: '召し上がる', reading: 'めしあがる', meaning: '-- honorific form of 食べる (たべる) and 飲む (のむ) --', genkiLesson: 19 },
  { id: '文化#ぶんか', level: 'N4', expression: '文化', reading: 'ぶんか', meaning: 'culture', genkiLesson: 19 },
  { id: 'おっしゃる#おっしゃる', level: 'N4', expression: 'おっしゃる', reading: 'おっしゃる', meaning: '-- honorific expression for いう --', genkiLesson: 19 },
  { id: '月#つき', level: 'N4', expression: '月', reading: 'つき', meaning: 'moon', genkiLesson: 20 },
  { id: '致す#いたす', level: 'N4', expression: '致す', reading: 'いたす', meaning: '-- extra-modest expression for する --', genkiLesson: 20 },
  { id: '小説#しょうせつ', level: 'N4', expression: '小説', reading: 'しょうせつ', meaning: 'novel', genkiLesson: 20 },
  { id: 'おる#おる', level: 'N4', expression: 'おる', reading: 'おる', meaning: '-- extra-modest expression for いる --', genkiLesson: 20 },
  { id: '申す#もうす', level: 'N4', expression: '申す', reading: 'もうす', meaning: '-- extra-modest (humble) expression for 言う (いう) --', genkiLesson: 20 },
  { id: '空港#くうこう', level: 'N4', expression: '空港', reading: 'くうこう', meaning: 'airport', genkiLesson: 20 },
  { id: '差し上げる#さしあげる', level: 'N4', expression: '差し上げる', reading: 'さしあげる', meaning: '-- humble expression for あげる --', genkiLesson: 20 },
  { id: '音#おと', level: 'N4', expression: '音', reading: 'おと', meaning: 'sound, note', genkiLesson: 20 },
  { id: '伝える#つたえる', level: 'N4', expression: '伝える', reading: 'つたえる', meaning: 'to convey (a message); to tell, to report', genkiLesson: 20 },
  { id: '字#じ', level: 'N4', expression: '字', reading: 'じ', meaning: 'letter; character', genkiLesson: 20 },
  { id: '参る#まいる', level: 'N4', expression: '参る', reading: 'まいる', meaning: 'humble expression for 行く and 来る', genkiLesson: 20 },
  { id: '戻る#もどる', level: 'N4', expression: '戻る', reading: 'もどる', meaning: 'to return (v.i.); to come back', genkiLesson: 20 },
  { id: '趣味#しゅみ', level: 'N4', expression: '趣味', reading: 'しゅみ', meaning: 'hobby; pastime', genkiLesson: 20 },
  { id: '盗む#ぬすむ', level: 'N4', expression: '盗む', reading: 'ぬすむ', meaning: 'to steal; to rob', genkiLesson: 21 },
  { id: 'ガソリン#ガソリン', level: 'N4', expression: 'ガソリン', reading: 'ガソリン', meaning: 'gasoline, petrol', genkiLesson: 21 },
  { id: '焼く#やく', level: 'N4', expression: '焼く', reading: 'やく', meaning: 'to bake, to grill', genkiLesson: 21 },
  { id: '泥棒#どろぼう', level: 'N4', expression: '泥棒', reading: 'どろぼう', meaning: 'thief; burglar', genkiLesson: 21 },
  { id: '赤ちゃん#あかちゃん', level: 'N4', expression: '赤ちゃん', reading: 'あかちゃん', meaning: 'baby, infant', genkiLesson: 21 },
  { id: '包む#つつむ', level: 'N4', expression: '包む', reading: 'つつむ', meaning: 'to wrap, to cover', genkiLesson: 21 },
  { id: '間違える#まちがえる', level: 'N4', expression: '間違える', reading: 'まちがえる', meaning: 'to make a mistake', genkiLesson: 21 },
  { id: '昔#むかし', level: 'N4', expression: '昔', reading: 'むかし', meaning: 'old days; past', genkiLesson: 21 },
  { id: '事#こと', level: 'N4', expression: '事', reading: 'こと', meaning: 'thing(s), matter(s), fact', genkiLesson: 21 },
  { id: 'ひどい#ひどい', level: 'N4', expression: 'ひどい', reading: 'ひどい', meaning: 'terrible, awful, unfair, cruel', genkiLesson: 21 },
  { id: 'びっくりする#びっくりする', level: 'N4', expression: 'びっくりする', reading: 'びっくりする', meaning: 'to be surprised', genkiLesson: 21 },
  { id: '見つける#みつける', level: 'N4', expression: '見つける', reading: 'みつける', meaning: 'to discover, to find (v.t.)', genkiLesson: 21 },
  { id: '留守#るす', level: 'N4', expression: '留守', reading: 'るす', meaning: 'absence; not at home', genkiLesson: 21 },
  { id: '褒める#ほめる', level: 'N4', expression: '褒める', reading: 'ほめる', meaning: 'to praise; to say nice things', genkiLesson: 21 },
  { id: '続ける#つづける', level: 'N4', expression: '続ける', reading: 'つづける', meaning: 'to continue, to keep up', genkiLesson: 21 },
  { id: 'いじめる#いじめる', level: 'N4', expression: 'いじめる', reading: 'いじめる', meaning: 'to bully, to torment', genkiLesson: 21 },
  { id: '工場#こうじょう', level: 'N4', expression: '工場', reading: 'こうじょう', meaning: 'factory', genkiLesson: 21 },
  { id: '警察#けいさつ', level: 'N4', expression: '警察', reading: 'けいさつ', meaning: 'police; police station', genkiLesson: 21 },
  { id: '会議#かいぎ', level: 'N4', expression: '会議', reading: 'かいぎ', meaning: 'business meeting; conference', genkiLesson: 21 },
  { id: '予習#よしゅう', level: 'N4', expression: '予習', reading: 'よしゅう', meaning: 'preparation of lessons (for class)', genkiLesson: 22 },
  { id: '拾う#ひろう', level: 'N4', expression: '拾う', reading: 'ひろう', meaning: 'to pick up (something), to find', genkiLesson: 22 },
  { id: '受付#うけつけ', level: 'N4', expression: '受付', reading: 'うけつけ', meaning: 'reception(ist) desk', genkiLesson: 22 },
  { id: 'お嬢さん#おじょうさん', level: 'N4', expression: 'お嬢さん', reading: 'おじょうさん', meaning: '(someone\'s) daughter (polite)', genkiLesson: 22 },
  { id: '育てる#そだてる', level: 'N4', expression: '育てる', reading: 'そだてる', meaning: 'to raise (v.t.); to bring up', genkiLesson: 22 },
  { id: '運ぶ#はこぶ', level: 'N4', expression: '運ぶ', reading: 'はこぶ', meaning: 'to transport, to carry', genkiLesson: 22 },
  { id: '先輩#せんぱい', level: 'N4', expression: '先輩', reading: 'せんぱい', meaning: 'senior members of a group', genkiLesson: 22 },
  { id: '自由#じゆう', level: 'N4', expression: '自由', reading: 'じゆう', meaning: 'freedom', genkiLesson: 22 },
  { id: '小学校#しょうがっこう', level: 'N4', expression: '小学校', reading: 'しょうがっこう', meaning: 'elementary school', genkiLesson: 23 },
  { id: '場所#ばしょ', level: 'N4', expression: '場所', reading: 'ばしょ', meaning: 'place, location', genkiLesson: 23 },
  { id: '踏む#ふむ', level: 'N4', expression: '踏む', reading: 'ふむ', meaning: 'to step on, to tread on' },
  { id: '～区#く', level: 'N4', expression: '～区', reading: 'く', meaning: '~ district, ~ ward, ~ borough', displayReading: '～く', isAffix: true },
  { id: 'すっと#すっと', level: 'N4', expression: 'すっと', reading: 'すっと', meaning: 'straight, quickly' },
  { id: 'とうとう#とうとう', level: 'N4', expression: 'とうとう', reading: 'とうとう', meaning: 'finally, at last' },
  { id: '鳴る#なる', level: 'N4', expression: '鳴る', reading: 'なる', meaning: 'to sound, to ring (v.i.)' },
  { id: 'しっかり#しっかり', level: 'N4', expression: 'しっかり', reading: 'しっかり', meaning: 'firmly, steady' },
  { id: '生きる#いきる', level: 'N4', expression: '生きる', reading: 'いきる', meaning: 'to live' },
  { id: '苦い#にがい', level: 'N4', expression: '苦い', reading: 'にがい', meaning: 'bitter' },
  { id: '沸く#わく', level: 'N4', expression: '沸く', reading: 'わく', meaning: 'to boil, to grow hot' },
  { id: '意見#いけん', level: 'N4', expression: '意見', reading: 'いけん', meaning: 'opinion, view, idea' },
  { id: 'やはり#やはり', level: 'N4', expression: 'やはり', reading: 'やはり', meaning: 'as I thought, absolutely', displayReading: 'やはり; やっぱり' },
  { id: 'ステレオ#ステレオ', level: 'N4', expression: 'ステレオ', reading: 'ステレオ', meaning: 'stereo' },
  { id: '医学#いがく', level: 'N4', expression: '医学', reading: 'いがく', meaning: 'medical science' },
  { id: 'テキスト#テキスト', level: 'N4', expression: 'テキスト', reading: 'テキスト', meaning: 'text; text book' },
  { id: '～月#つき', level: 'N4', expression: '～月', reading: 'つき', meaning: 'month', displayReading: '～つき', isAffix: true },
  { id: '折る#おる', level: 'N4', expression: '折る', reading: 'おる', meaning: 'to snap, to break; to bend' },
  { id: '～会#かい', level: 'N4', expression: '～会', reading: 'かい', meaning: '~ meeting', displayReading: '～かい', isAffix: true },
  { id: 'うかがう#うかがう', level: 'N4', expression: 'うかがう', reading: 'うかがう', meaning: 'to ask' },
  { id: '聞こえる#きこえる', level: 'N4', expression: '聞こえる', reading: 'きこえる', meaning: 'to be heard, to be audible' },
  { id: '必ず#かならず', level: 'N4', expression: '必ず', reading: 'かならず', meaning: 'surely, certainly' },
  { id: '壊す#こわす', level: 'N4', expression: '壊す', reading: 'こわす', meaning: 'to break, to break down' },
  { id: 'オートバイ#オートバイ', level: 'N4', expression: 'オートバイ', reading: 'オートバイ', meaning: 'motorcycle (lit: auto-bi(ke))' },
  { id: '運動#うんどうする', level: 'N4', expression: '運動', reading: 'うんどうする', meaning: 'exercise' },
  { id: '止む#やむ', level: 'N4', expression: '止む', reading: 'やむ', meaning: 'to cease, to stop' },
  { id: 'もし#もし', level: 'N4', expression: 'もし', reading: 'もし', meaning: 'if' },
  { id: '表#おもて', level: 'N4', expression: '表', reading: 'おもて', meaning: 'surface; front; outside' },
  { id: '運転手#うんてんしゅ', level: 'N4', expression: '運転手', reading: 'うんてんしゅ', meaning: 'driver (by occupation)' },
  { id: '心配#しんぱいする', level: 'N4', expression: '心配', reading: 'しんぱいする', meaning: 'worry, concern' },
  { id: '別#べつ', level: 'N4', expression: '別', reading: 'べつ', meaning: 'distinction, different' },
  { id: '非常に#ひじょうに', level: 'N4', expression: '非常に', reading: 'ひじょうに', meaning: 'extremely; very' },
  { id: '柔らかい#やわらかい', level: 'N4', expression: '柔らかい', reading: 'やわらかい', meaning: 'soft (in reference to texture), tender' },
  { id: '～ございます#ございます', level: 'N4', expression: '～ございます', reading: 'ございます', meaning: 'to be (polite), to exist', displayReading: '～ございます', isAffix: true },
  { id: '気#き', level: 'N4', expression: '気', reading: 'き', meaning: 'spirit, mood' },
  { id: '比べる#くらべる', level: 'N4', expression: '比べる', reading: 'くらべる', meaning: 'to compare' },
  { id: 'ほとんど#ほとんど', level: 'N4', expression: 'ほとんど', reading: 'ほとんど', meaning: 'mostly, almost' },
  { id: 'つもり#つもり', level: 'N4', expression: 'つもり', reading: 'つもり', meaning: 'intention, plan' },
  { id: '郊外#こうがい', level: 'N4', expression: '郊外', reading: 'こうがい', meaning: 'suburb, outskirts' },
  { id: 'だめ#だめ', level: 'N4', expression: 'だめ', reading: 'だめ', meaning: 'useless, no good, hopeless' },
  { id: '売り場#うりば', level: 'N4', expression: '売り場', reading: 'うりば', meaning: 'place where things are sold' },
  { id: '正月#しょうがつ', level: 'N4', expression: '正月', reading: 'しょうがつ', meaning: 'New Year, New Year\'s Day' },
  { id: '規則#きそく', level: 'N4', expression: '規則', reading: 'きそく', meaning: 'rule, regulation' },
  { id: '発音#はつおん', level: 'N4', expression: '発音', reading: 'はつおん', meaning: 'pronunciation' },
  { id: '屋上#おくじょう', level: 'N4', expression: '屋上', reading: 'おくじょう', meaning: 'rooftop' },
  { id: '失礼#しつれい', level: 'N4', expression: '失礼', reading: 'しつれい', meaning: 'discourtesy, impoliteness; Excuse me' },
  { id: 'アフリカ#アフリカ', level: 'N4', expression: 'アフリカ', reading: 'アフリカ', meaning: 'Africa' },
  { id: '点#てん', level: 'N4', expression: '点', reading: 'てん', meaning: 'mark, score, grade; point, dot' },
  { id: '一生懸命#いっしょうけんめい', level: 'N4', expression: '一生懸命', reading: 'いっしょうけんめい', meaning: 'very hard (as in "to work hard"), with utmost effort' },
  { id: '機会#きかい', level: 'N4', expression: '機会', reading: 'きかい', meaning: 'chance, opportunity' },
  { id: '建てる#たてる', level: 'N4', expression: '建てる', reading: 'たてる', meaning: 'to build' },
  { id: '複雑#ふくざつ', level: 'N4', expression: '複雑', reading: 'ふくざつ', meaning: 'complexity, complication' },
  { id: '布団#ふとん', level: 'N4', expression: '布団', reading: 'ふとん', meaning: 'futon' },
  { id: '大事#だいじ', level: 'N4', expression: '大事', reading: 'だいじ', meaning: 'important, valuable, serious matter' },
  { id: '贈り物#おくりもの', level: 'N4', expression: '贈り物', reading: 'おくりもの', meaning: 'a gift; a present' },
  { id: '～製#せい', level: 'N4', expression: '～製', reading: 'せい', meaning: 'made in ~', displayReading: '～せい', isAffix: true },
  { id: '注意#ちゅうい', level: 'N4', expression: '注意', reading: 'ちゅうい', meaning: 'caution, attention' },
  { id: '～軒#けん', level: 'N4', expression: '～軒', reading: 'けん', meaning: 'counter for houses', displayReading: '～けん', isAffix: true },
  { id: 'そう#そう', level: 'N4', expression: 'そう', reading: 'そう', meaning: 'really, (is that) so; yes, right' },
  { id: '通る#とおる', level: 'N4', expression: '通る', reading: 'とおる', meaning: 'to pass (by), to go through' },
  { id: '過ぎる#すぎる', level: 'N4', expression: '過ぎる', reading: 'すぎる', meaning: 'to exceed, to go beyond' },
  { id: 'レポート#レポート', level: 'N4', expression: 'レポート', reading: 'レポート', meaning: 'report', displayReading: 'レポート; リポート' },
  { id: '葉#は', level: 'N4', expression: '葉', reading: 'は', meaning: 'leaf' },
  { id: '必要#ひつよう', level: 'N4', expression: '必要', reading: 'ひつよう', meaning: 'necessary' },
  { id: '課長#かちょう', level: 'N4', expression: '課長', reading: 'かちょう', meaning: 'section manager' },
  { id: 'すると#すると', level: 'N4', expression: 'すると', reading: 'すると', meaning: 'and, then' },
  { id: '止める#やめる', level: 'N4', expression: '止める', reading: 'やめる', meaning: 'to end, to stop' },
  { id: 'ガラス#ガラス', level: 'N4', expression: 'ガラス', reading: 'ガラス', meaning: 'glass, pane' },
  { id: '～学部#がくぶ', level: 'N4', expression: '～学部', reading: 'がくぶ', meaning: 'department of a university', displayReading: '～がくぶ', isAffix: true },
  { id: 'エスカレーター#エスカレーター', level: 'N4', expression: 'エスカレーター', reading: 'エスカレーター', meaning: 'escalator' },
  { id: '人口#じんこう', level: 'N4', expression: '人口', reading: 'じんこう', meaning: 'population' },
  { id: '絹#きぬ', level: 'N4', expression: '絹', reading: 'きぬ', meaning: 'silk' },
  { id: 'ちっとも#ちっとも', level: 'N4', expression: 'ちっとも', reading: 'ちっとも', meaning: 'not at all (neg. verb)' },
  { id: '深い#ふかい', level: 'N4', expression: '深い', reading: 'ふかい', meaning: 'deep, profound' },
  { id: '壊れる#こわれる', level: 'N4', expression: '壊れる', reading: 'こわれる', meaning: 'to be broken, to break' },
  { id: '揺れる#ゆれる', level: 'N4', expression: '揺れる', reading: 'ゆれる', meaning: 'to shake, to sway' },
  { id: '落る#おちる', level: 'N4', expression: '落る', reading: 'おちる', meaning: 'to fall, to drop' },
  { id: 'できるだけ#できるだけ', level: 'N4', expression: 'できるだけ', reading: 'できるだけ', meaning: 'if at all possible, as much as possible' },
  { id: '中学校#ちゅうがっこう', level: 'N4', expression: '中学校', reading: 'ちゅうがっこう', meaning: 'junior high school pupil' },
  { id: 'ガス#ガス', level: 'N4', expression: 'ガス', reading: 'ガス', meaning: 'gas' },
  { id: '祈る#いのる', level: 'N4', expression: '祈る', reading: 'いのる', meaning: 'to pray; to wish' },
  { id: '盛ん#さかん', level: 'N4', expression: '盛ん', reading: 'さかん', meaning: 'prosperous, active, thriving' },
  { id: '噛む#かむ', level: 'N4', expression: '噛む', reading: 'かむ', meaning: 'to bite, to chew' },
  { id: '浅い#あさい', level: 'N4', expression: '浅い', reading: 'あさい', meaning: 'shallow, superficial' },
  { id: 'それに#それに', level: 'N4', expression: 'それに', reading: 'それに', meaning: 'moreover; besides' },
  { id: '西洋#せいよう', level: 'N4', expression: '西洋', reading: 'せいよう', meaning: 'the West, Western countries' },
  { id: 'パート (タイム)#パート', level: 'N4', expression: 'パート (タイム)', reading: 'パート', meaning: 'part time (esp. female part time employees)', displayReading: 'パート (タイム)' },
  { id: '時代#じだい', level: 'N4', expression: '時代', reading: 'じだい', meaning: 'age, period, epoch, era' },
  { id: '申し上げる#もうしあげる', level: 'N4', expression: '申し上げる', reading: 'もうしあげる', meaning: '(humble)to say, to tell' },
  { id: '～式#しき', level: 'N4', expression: '～式', reading: 'しき', meaning: '~ ceremony; ~ style', displayReading: '～しき', isAffix: true },
  { id: '出席#しゅっせきする', level: 'N4', expression: '出席', reading: 'しゅっせきする', meaning: 'attendance' },
  { id: '～家#か', level: 'N4', expression: '～家', reading: 'か', meaning: 'person who is specialized in ~', displayReading: '～か', isAffix: true },
  { id: '迎える#むかえる', level: 'N4', expression: '迎える', reading: 'むかえる', meaning: 'to welcome; to meet; to greet' },
  { id: '触る#さわる', level: 'N4', expression: '触る', reading: 'さわる', meaning: 'to touch, to feel' },
  { id: '建て#だて', level: 'N4', expression: '建て', reading: 'だて', meaning: '~ storied, separate housing', displayReading: '～だて', isAffix: true },
  { id: '動物園#どうぶつえん', level: 'N4', expression: '動物園', reading: 'どうぶつえん', meaning: 'zoo' },
  { id: '捕まえる#つかまえる', level: 'N4', expression: '捕まえる', reading: 'つかまえる', meaning: 'to catch, to arrest' },
  { id: '決まる#きまる', level: 'N4', expression: '決まる', reading: 'きまる', meaning: 'to be set; fixed (v.i.)' },
  { id: '開く#ひらく', level: 'N4', expression: '開く', reading: 'ひらく', meaning: 'to open; to hold (an event)' },
  { id: '逃げる#にげる', level: 'N4', expression: '逃げる', reading: 'にげる', meaning: 'to escape, to run away' },
  { id: '残念#ざんねん', level: 'N4', expression: '残念', reading: 'ざんねん', meaning: 'regret; regrettable' },
  { id: '畳#たたみ', level: 'N4', expression: '畳', reading: 'たたみ', meaning: 'tatami mat (Japanese straw mat)' },
  { id: '丁寧#ていねい', level: 'N4', expression: '丁寧', reading: 'ていねい', meaning: 'polite, courteous, careful' },
  { id: '地理#ちり', level: 'N4', expression: '地理', reading: 'ちり', meaning: 'geography' },
  { id: 'なるべく#なるべく', level: 'N4', expression: 'なるべく', reading: 'なるべく', meaning: 'if possible, as much as possible' },
  { id: '無理#むり', level: 'N4', expression: '無理', reading: 'むり', meaning: 'unreasonable, impossible' },
  { id: 'サンドイッチ#サンドイッチ', level: 'N4', expression: 'サンドイッチ', reading: 'サンドイッチ', meaning: 'sandwich' },
  { id: '会議室#かいぎしつ', level: 'N4', expression: '会議室', reading: 'かいぎしつ', meaning: 'conference room' },
  { id: '品物#しなもの', level: 'N4', expression: '品物', reading: 'しなもの', meaning: 'goods' },
  { id: '人形#にんぎょう', level: 'N4', expression: '人形', reading: 'にんぎょう', meaning: 'doll, figure' },
  { id: '利用#りよう', level: 'N4', expression: '利用', reading: 'りよう', meaning: 'use, utilization' },
  { id: '飾る#かざる', level: 'N4', expression: '飾る', reading: 'かざる', meaning: 'to decorate, to adorn' },
  { id: '止める#とめる', level: 'N4', expression: '止める', reading: 'とめる', meaning: 'to stop (something)' },
  { id: 'いくら～ても#いくらても', level: 'N4', expression: 'いくら～ても', reading: 'いくらても', meaning: 'however much one may ~', displayReading: 'いくら～ても', isAffix: true },
  { id: 'ビル#ビル', level: 'N4', expression: 'ビル', reading: 'ビル', meaning: '(abbr.) building' },
  { id: 'けんかする#けんかする', level: 'N4', expression: 'けんかする', reading: 'けんかする', meaning: 'quarrel' },
  { id: '投げる#なげる', level: 'N4', expression: '投げる', reading: 'なげる', meaning: 'to pitch, to cast away' },
  { id: '故障#こしょうする', level: 'N4', expression: '故障', reading: 'こしょうする', meaning: 'breakdown' },
  { id: '力#ちから', level: 'N4', expression: '力', reading: 'ちから', meaning: 'strength, power' },
  { id: '受ける#うける', level: 'N4', expression: '受ける', reading: 'うける', meaning: 'to take (an examination, interview, etc.); to receive' },
  { id: '気分#きぶん', level: 'N4', expression: '気分', reading: 'きぶん', meaning: 'feeling, mood' },
  { id: 'そんな#そんな', level: 'N4', expression: 'そんな', reading: 'そんな', meaning: 'such, like that, that sort of' },
  { id: '星#ほし', level: 'N4', expression: '星', reading: 'ほし', meaning: 'star' },
  { id: '場合#ばあい', level: 'N4', expression: '場合', reading: 'ばあい', meaning: 'case, situation' },
  { id: 'やっと#やっと', level: 'N4', expression: 'やっと', reading: 'やっと', meaning: 'at last, finally' },
  { id: '行う#おこなう', level: 'N4', expression: '行う', reading: 'おこなう', meaning: 'to carry out; to conduct (typically used in written language)' },
  { id: 'ぶどう#ぶどう', level: 'N4', expression: 'ぶどう', reading: 'ぶどう', meaning: 'grapes' },
  { id: '無くなる#なくなる', level: 'N4', expression: '無くなる', reading: 'なくなる', meaning: 'to disappear, to get lost' },
  { id: '準備#じゅんびする', level: 'N4', expression: '準備', reading: 'じゅんびする', meaning: 'prepare' },
  { id: '住所#じゅうしょ', level: 'N4', expression: '住所', reading: 'じゅうしょ', meaning: 'address; place of residence' },
  { id: '再来月#さらいげつ', level: 'N4', expression: '再来月', reading: 'さらいげつ', meaning: 'the month after next' },
  { id: '林#はやし', level: 'N4', expression: '林', reading: 'はやし', meaning: 'woods, forest' },
  { id: '倍#ばい', level: 'N4', expression: '倍', reading: 'ばい', meaning: 'double' },
  { id: '線#せん', level: 'N4', expression: '線', reading: 'せん', meaning: 'line, wire' },
  { id: '戦争#せんそう', level: 'N4', expression: '戦争', reading: 'せんそう', meaning: 'war' },
  { id: '調べる#しらべる', level: 'N4', expression: '調べる', reading: 'しらべる', meaning: 'to check; to look up; to inquire; to search' },
  { id: '寝坊#ねぼう', level: 'N4', expression: '寝坊', reading: 'ねぼう', meaning: 'sleeping in late' },
  { id: 'パパ#パパ', level: 'N4', expression: 'パパ', reading: 'パパ', meaning: 'papa, daddy' },
  { id: '光る#ひかる', level: 'N4', expression: '光る', reading: 'ひかる', meaning: 'to shine, to glitter' },
  { id: '夫#おっと', level: 'N4', expression: '夫', reading: 'おっと', meaning: 'husband' },
  { id: '雲#くも', level: 'N4', expression: '雲', reading: 'くも', meaning: 'cloud' },
  { id: '坂#さか', level: 'N4', expression: '坂', reading: 'さか', meaning: 'slope, hill' },
  { id: '～(て) しまう#しまう', level: 'N4', expression: '～(て) しまう', reading: 'しまう', meaning: 'to end up ~', displayReading: '～(て) しまう', isAffix: true },
  { id: '飛行場#ひこうじょう', level: 'N4', expression: '飛行場', reading: 'ひこうじょう', meaning: 'airport' },
  { id: '柔道#じゅうどう', level: 'N4', expression: '柔道', reading: 'じゅうどう', meaning: 'judo' },
  { id: '決して#けっして', level: 'N4', expression: '決して', reading: 'けっして', meaning: 'never' },
  { id: '事務所#じむしょ', level: 'N4', expression: '事務所', reading: 'じむしょ', meaning: 'office' },
  { id: '連絡#れんらく', level: 'N4', expression: '連絡', reading: 'れんらく', meaning: 'communication, contact, connection' },
  { id: '客#きゃく', level: 'N4', expression: '客', reading: 'きゃく', meaning: 'guest, customer' },
  { id: '美しい#うつくしい', level: 'N4', expression: '美しい', reading: 'うつくしい', meaning: 'beautiful, lovely' },
  { id: 'どんどん#どんどん', level: 'N4', expression: 'どんどん', reading: 'どんどん', meaning: 'quickly and steadily; at a rapid pace' },
  { id: '適当#てきとう', level: 'N4', expression: '適当', reading: 'てきとう', meaning: 'fitness, suitability' },
  { id: '素晴らしい#すばらしい', level: 'N4', expression: '素晴らしい', reading: 'すばらしい', meaning: 'wonderful; terrific' },
  { id: '終わり#おわり', level: 'N4', expression: '終わり', reading: 'おわり', meaning: 'end' },
  { id: '壁#かべ', level: 'N4', expression: '壁', reading: 'かべ', meaning: 'wall' },
  { id: '一度#いちど', level: 'N4', expression: '一度', reading: 'いちど', meaning: 'once, one time' },
  { id: '親切#しんせつ', level: 'N4', expression: '親切', reading: 'しんせつ', meaning: 'kindness' },
  { id: '知らせる#しらせる', level: 'N4', expression: '知らせる', reading: 'しらせる', meaning: 'to notify' },
  { id: '歯医者#はいしゃ', level: 'N4', expression: '歯医者', reading: 'はいしゃ', meaning: 'dentist' },
  { id: '熱心#ねっしん', level: 'N4', expression: '熱心', reading: 'ねっしん', meaning: 'enthusiasm' },
  { id: 'もらう#もらう', level: 'N4', expression: 'もらう', reading: 'もらう', meaning: 'to receive' },
  { id: '治る#なおる', level: 'N4', expression: '治る', reading: 'なおる', meaning: 'to get better; to recover from illness (v.i.)' },
  { id: '熱#ねつ', level: 'N4', expression: '熱', reading: 'ねつ', meaning: 'fever, temperature' },
  { id: 'お祭り#おまつり', level: 'N4', expression: 'お祭り', reading: 'おまつり', meaning: 'festival' },
  { id: '水道#すいどう', level: 'N4', expression: '水道', reading: 'すいどう', meaning: 'water service, water line' },
  { id: '匂い#におい', level: 'N4', expression: '匂い', reading: 'におい', meaning: 'odor, smell' },
  { id: 'ベル#ベル', level: 'N4', expression: 'ベル', reading: 'ベル', meaning: 'bell' },
  { id: '赤ん坊#あかんぼう', level: 'N4', expression: '赤ん坊', reading: 'あかんぼう', meaning: 'baby' },
  { id: 'おかしい#おかしい', level: 'N4', expression: 'おかしい', reading: 'おかしい', meaning: 'strange; odd; funny' },
  { id: '事故#じこ', level: 'N4', expression: '事故', reading: 'じこ', meaning: 'accident' },
  { id: '変#へん', level: 'N4', expression: '変', reading: 'へん', meaning: 'strange, odd' },
  { id: '辞典#じてん', level: 'N4', expression: '辞典', reading: 'じてん', meaning: 'encyclopedia, reference book' },
  { id: '残る#のこる', level: 'N4', expression: '残る', reading: 'のこる', meaning: 'to remain (v.i.), to be left' },
  { id: '立てる#たてる', level: 'N4', expression: '立てる', reading: 'たてる', meaning: 'to stand (something) up, to erect (something)' },
  { id: 'くれる#くれる', level: 'N4', expression: 'くれる', reading: 'くれる', meaning: 'to give, to do for' },
  { id: '～員#いん', level: 'N4', expression: '～員', reading: 'いん', meaning: 'member of ~', displayReading: '～いん', isAffix: true },
  { id: '原因#げんいん', level: 'N4', expression: '原因', reading: 'げんいん', meaning: 'cause, origin, source' },
  { id: '驚く#おどろく', level: 'N4', expression: '驚く', reading: 'おどろく', meaning: 'to be surprised, to be astonished' },
  { id: '祖母#そぼ', level: 'N4', expression: '祖母', reading: 'そぼ', meaning: 'grandmother' },
  { id: '答#こたえ', level: 'N4', expression: '答', reading: 'こたえ', meaning: 'answer, response' },
  { id: '漬ける#つける', level: 'N4', expression: '漬ける', reading: 'つける', meaning: 'to soak, to moisten, to pickle' },
  { id: '内#うち', level: 'N4', expression: '内', reading: 'うち', meaning: 'within, inside' },
  { id: 'スクリーン#スクリーン', level: 'N4', expression: 'スクリーン', reading: 'スクリーン', meaning: 'screen' },
  { id: '増える#ふえる', level: 'N4', expression: '増える', reading: 'ふえる', meaning: 'to increase, to multiply' },
  { id: 'または#または', level: 'N4', expression: 'または', reading: 'または', meaning: 'or, otherwise' },
  { id: 'けがする#けがする', level: 'N4', expression: 'けがする', reading: 'けがする', meaning: 'injury (to animate object), hurt' },
  { id: '以下#いか', level: 'N4', expression: '以下', reading: 'いか', meaning: 'less than, below' },
  { id: '～ばかり#ばかり', level: 'N4', expression: '～ばかり', reading: 'ばかり', meaning: 'just did ~, only', displayReading: '～ばかり', isAffix: true },
  { id: '心#こころ', level: 'N4', expression: '心', reading: 'こころ', meaning: 'heart, mind' },
  { id: '～だす#だす', level: 'N4', expression: '～だす', reading: 'だす', meaning: 'to start doing ~', displayReading: '～だす', isAffix: true },
  { id: 'サラダ#サラダ', level: 'N4', expression: 'サラダ', reading: 'サラダ', meaning: 'salad' },
  { id: '届ける#とどける', level: 'N4', expression: '届ける', reading: 'とどける', meaning: 'to deliver (v.t.)' },
  { id: '景色#けしき', level: 'N4', expression: '景色', reading: 'けしき', meaning: 'scenery, landscape' },
  { id: '確か#たしか', level: 'N4', expression: '確か', reading: 'たしか', meaning: 'if I remember correctly; certain, definite' },
  { id: 'ステーキ#ステーキ', level: 'N4', expression: 'ステーキ', reading: 'ステーキ', meaning: 'steak' },
  { id: '食料品#しょくりょうひん', level: 'N4', expression: '食料品', reading: 'しょくりょうひん', meaning: 'foodstuff, groceries' },
  { id: '森#もり', level: 'N4', expression: '森', reading: 'もり', meaning: 'forest' },
  { id: '以内#いない', level: 'N4', expression: '以内', reading: 'いない', meaning: 'within, less (no more) than' },
  { id: 'オーバー#オーバー', level: 'N4', expression: 'オーバー', reading: 'オーバー', meaning: 'overcoat; over, exceeding, exaggeration' },
  { id: '乾く#かわく', level: 'N4', expression: '乾く', reading: 'かわく', meaning: 'to get dry' },
  { id: '石#いし', level: 'N4', expression: '石', reading: 'いし', meaning: 'stone' },
  { id: '思い出す#おもいだす', level: 'N4', expression: '思い出す', reading: 'おもいだす', meaning: 'to recall, to remember' },
  { id: '細かい#こまかい', level: 'N4', expression: '細かい', reading: 'こまかい', meaning: 'small; fine, minute' },
  { id: '塗る#ぬる', level: 'N4', expression: '塗る', reading: 'ぬる', meaning: 'to paint, to plaster' },
  { id: '珍しい#めずらしい', level: 'N4', expression: '珍しい', reading: 'めずらしい', meaning: 'unusual, rare' },
  { id: '用#よう', level: 'N4', expression: '用', reading: 'よう', meaning: 'errand, task, business (to take care of)' },
  { id: '公務員#こうむいん', level: 'N4', expression: '公務員', reading: 'こうむいん', meaning: 'government worker, public servant' },
  { id: '用意#ようい', level: 'N4', expression: '用意', reading: 'ようい', meaning: 'preparation' },
  { id: '形#かたち', level: 'N4', expression: '形', reading: 'かたち', meaning: 'shape' },
  { id: '運転#うんてんする', level: 'N4', expression: '運転', reading: 'うんてんする', meaning: 'driving' },
  { id: 'すっかり#すっかり', level: 'N4', expression: 'すっかり', reading: 'すっかり', meaning: 'all, completely' },
  { id: 'アナウンサー#アナウンサー', level: 'N4', expression: 'アナウンサー', reading: 'アナウンサー', meaning: 'announcer' },
  { id: '消しゴム#けしゴム', level: 'N4', expression: '消しゴム', reading: 'けしゴム', meaning: 'eraser' },
  { id: '海岸#かいがん', level: 'N4', expression: '海岸', reading: 'かいがん', meaning: 'coast, seashore' },
  { id: '火#ひ', level: 'N4', expression: '火', reading: 'ひ', meaning: 'fire' },
  { id: '味噌#みそ', level: 'N4', expression: '味噌', reading: 'みそ', meaning: 'miso, bean paste' },
  { id: 'お祝い#おいわい', level: 'N4', expression: 'お祝い', reading: 'おいわい', meaning: 'congratulation, celebration' },
  { id: '乗り物#のりもの', level: 'N4', expression: '乗り物', reading: 'のりもの', meaning: 'vehicle' },
  { id: '案内#あんないする', level: 'N4', expression: '案内', reading: 'あんないする', meaning: 'information, guidance' },
  { id: '通う#かよう', level: 'N4', expression: '通う', reading: 'かよう', meaning: 'to go back and forth; to commute' },
  { id: '連れる#つれる', level: 'N4', expression: '連れる', reading: 'つれる', meaning: 'to lead, to take (a person)' },
  { id: '技術#ぎじゅつ', level: 'N4', expression: '技術', reading: 'ぎじゅつ', meaning: 'technique, technology, skill' },
  { id: '小鳥#ことり', level: 'N4', expression: '小鳥', reading: 'ことり', meaning: 'small bird' },
  { id: '下宿#げしゅく', level: 'N4', expression: '下宿', reading: 'げしゅく', meaning: 'lodging, boarding house' },
  { id: 'ジャム#ジャム', level: 'N4', expression: 'ジャム', reading: 'ジャム', meaning: 'jam' },
  { id: '招待#しょうたいする', level: 'N4', expression: '招待', reading: 'しょうたいする', meaning: 'invitation' },
  { id: '鏡#かがみ', level: 'N4', expression: '鏡', reading: 'かがみ', meaning: 'mirror' },
  { id: 'はず#はず', level: 'N4', expression: 'はず', reading: 'はず', meaning: 'it should be so' },
  { id: '法律#ほうりつ', level: 'N4', expression: '法律', reading: 'ほうりつ', meaning: 'law' },
  { id: '進む#すすむ', level: 'N4', expression: '進む', reading: 'すすむ', meaning: 'to advance, to proceed' },
  { id: '楽む#たのしむ', level: 'N4', expression: '楽む', reading: 'たのしむ', meaning: 'to enjoy' },
  { id: '貿易#ぼうえき', level: 'N4', expression: '貿易', reading: 'ぼうえき', meaning: 'trade' },
  { id: '反対#はんたい', level: 'N4', expression: '反対', reading: 'はんたい', meaning: 'oppose, opposition, resistance' },
  { id: '真面目#まじめ', level: 'N4', expression: '真面目', reading: 'まじめ', meaning: 'diligent, serious' },
  { id: '店員#てんいん', level: 'N4', expression: '店員', reading: 'てんいん', meaning: 'clerk; shop-employee' },
  { id: '泊まる#とまる', level: 'N4', expression: '泊まる', reading: 'とまる', meaning: 'to stay (over night) (v.i.)' },
  { id: 'よろしい#よろしい', level: 'N4', expression: 'よろしい', reading: 'よろしい', meaning: '(hon.) good, OK, all right' },
  { id: '今夜#こんや', level: 'N4', expression: '今夜', reading: 'こんや', meaning: 'this evening, tonight' },
  { id: 'おつり#おつり', level: 'N4', expression: 'おつり', reading: 'おつり', meaning: 'change; balance of money returned to the purchaser' },
  { id: 'チェックする#チェックする', level: 'N4', expression: 'チェックする', reading: 'チェックする', meaning: 'check' },
  { id: '会話#かいわ', level: 'N4', expression: '会話', reading: 'かいわ', meaning: 'conversation' },
  { id: '交通#こうつう', level: 'N4', expression: '交通', reading: 'こうつう', meaning: 'traffic, transportation' },
  { id: 'ワープロ#ワープロ', level: 'N4', expression: 'ワープロ', reading: 'ワープロ', meaning: 'word processor' },
  { id: '喜ぶ#よろこぶ', level: 'N4', expression: '喜ぶ', reading: 'よろこぶ', meaning: 'to rejoice, to be delighted, to be glad' },
  { id: '急行#きゅうこう', level: 'N4', expression: '急行', reading: 'きゅうこう', meaning: 'express train or bus' },
  { id: '皆#みな', level: 'N4', expression: '皆', reading: 'みな', meaning: 'everyone' },
  { id: '味#あじ', level: 'N4', expression: '味', reading: 'あじ', meaning: 'flavor, taste' },
  { id: '校長#こうちょう', level: 'N4', expression: '校長', reading: 'こうちょう', meaning: 'principal, headmaster' },
  { id: 'ごちそう#ごちそう', level: 'N4', expression: 'ごちそう', reading: 'ごちそう', meaning: 'feast, treating (someone)' },
  { id: '踊り#おどり', level: 'N4', expression: '踊り', reading: 'おどり', meaning: 'dance' },
  { id: '興味#きょうみ', level: 'N4', expression: '興味', reading: 'きょうみ', meaning: 'interest (in something)' },
  { id: '引っ越す#ひっこす', level: 'N4', expression: '引っ越す', reading: 'ひっこす', meaning: 'to move to a new place of residence' },
  { id: '冷房#れいぼう', level: 'N4', expression: '冷房', reading: 'れいぼう', meaning: 'cooling, air conditioning' },
  { id: '都合#つごう', level: 'N4', expression: '都合', reading: 'つごう', meaning: 'circumstances, convenience' },
  { id: '遠慮#えんりょする', level: 'N4', expression: '遠慮', reading: 'えんりょする', meaning: 'restraint, reserve, hesitate' },
  { id: '亡くなる#なくなる', level: 'N4', expression: '亡くなる', reading: 'なくなる', meaning: 'to pass away' },
  { id: 'はっきり#はっきり', level: 'N4', expression: 'はっきり', reading: 'はっきり', meaning: 'clearly, distinctly' },
  { id: '気持ち#きもち', level: 'N4', expression: '気持ち', reading: 'きもち', meaning: 'feeling, sensation, mood' },
  { id: '祖父#そふ', level: 'N4', expression: '祖父', reading: 'そふ', meaning: 'grandfather' },
  { id: '港#みなと', level: 'N4', expression: '港', reading: 'みなと', meaning: 'harbor, port' },
  { id: '凄い#すごい', level: 'N4', expression: '凄い', reading: 'すごい', meaning: 'terrific, great' },
  { id: '入学#にゅうがくする', level: 'N4', expression: '入学', reading: 'にゅうがくする', meaning: 'entry to school or university' },
  { id: '片付ける#かたづける', level: 'N4', expression: '片付ける', reading: 'かたづける', meaning: 'to (clean) tidy up (v.t.), to put away' },
  { id: '写す#うつす', level: 'N4', expression: '写す', reading: 'うつす', meaning: 'to copy (v.t.); to photograph' },
  { id: 'パソコン#パソコン', level: 'N4', expression: 'パソコン', reading: 'パソコン', meaning: '(personal) computer' },
  { id: '火事#かじ', level: 'N4', expression: '火事', reading: 'かじ', meaning: 'fire' },
  { id: '足す#たす', level: 'N4', expression: '足す', reading: 'たす', meaning: 'to add (numbers)' },
  { id: '教会#きょうかい', level: 'N4', expression: '教会', reading: 'きょうかい', meaning: 'church' },
  { id: '彼ら#かれら', level: 'N4', expression: '彼ら', reading: 'かれら', meaning: 'they (usually male)' },
  { id: '男性#だんせい', level: 'N4', expression: '男性', reading: 'だんせい', meaning: 'man; male' },
  { id: '理由#りゆう', level: 'N4', expression: '理由', reading: 'りゆう', meaning: 'reason' },
  { id: '生産#せいさんする', level: 'N4', expression: '生産', reading: 'せいさんする', meaning: 'production; to produce' },
  { id: '暮れる#くれる', level: 'N4', expression: '暮れる', reading: 'くれる', meaning: 'to get dark, to come to an end' },
  { id: '釣る#つる', level: 'N4', expression: '釣る', reading: 'つる', meaning: 'to fish' },
  { id: '～ちゃん#ちゃん', level: 'N4', expression: '～ちゃん', reading: 'ちゃん', meaning: 'suffix for familiar (female) person', displayReading: '～ちゃん', isAffix: true },
  { id: '打つ#うつ', level: 'N4', expression: '打つ', reading: 'うつ', meaning: 'to hit, to strike' },
  { id: 'あんな#あんな', level: 'N4', expression: 'あんな', reading: 'あんな', meaning: 'such, like that' },
  { id: '謝る#あやまる', level: 'N4', expression: '謝る', reading: 'あやまる', meaning: 'to apologize' },
  { id: '昼間#ひるま', level: 'N4', expression: '昼間', reading: 'ひるま', meaning: 'daytime, during the day' },
  { id: '教育#きょういく', level: 'N4', expression: '教育', reading: 'きょういく', meaning: 'education' },
  { id: '女性#じょせい', level: 'N4', expression: '女性', reading: 'じょせい', meaning: 'woman' },
  { id: '米#こめ', level: 'N4', expression: '米', reading: 'こめ', meaning: 'uncooked rice' },
  { id: '邪魔#じゃま', level: 'N4', expression: '邪魔', reading: 'じゃま', meaning: 'hindrance, intrusion' },
  { id: '国際#こくさい', level: 'N4', expression: '国際', reading: 'こくさい', meaning: 'international' },
  { id: '隅#すみ', level: 'N4', expression: '隅', reading: 'すみ', meaning: 'corner' },
  { id: '伺う#うかがう', level: 'N4', expression: '伺う', reading: 'うかがう', meaning: 'humble form of 行く (いく), 聞く (きく) and 来る (くる)' },
  { id: '再来週#さらいしゅう', level: 'N4', expression: '再来週', reading: 'さらいしゅう', meaning: 'the week after next' },
  { id: '喉#のど', level: 'N4', expression: '喉', reading: 'のど', meaning: 'throat' },
  { id: '周り#まわり', level: 'N4', expression: '周り', reading: 'まわり', meaning: 'surroundings' },
  { id: '不便#ふべん', level: 'N4', expression: '不便', reading: 'ふべん', meaning: 'inconvenience' },
  { id: '血#ち', level: 'N4', expression: '血', reading: 'ち', meaning: 'blood' },
  { id: '～続ける#つづける', level: 'N4', expression: '～続ける', reading: 'つづける', meaning: 'to continue doing ~', displayReading: '～つづける', isAffix: true },
  { id: '毛#け', level: 'N4', expression: '毛', reading: 'け', meaning: 'hair, fur' },
  { id: '中々#なかなか', level: 'N4', expression: '中々', reading: 'なかなか', meaning: 'very, considerably, quite' },
  { id: '随分#ずいぶん', level: 'N4', expression: '随分', reading: 'ずいぶん', meaning: 'extremely' },
  { id: '～やすい#やすい', level: 'N4', expression: '～やすい', reading: 'やすい', meaning: 'easy to do ~', displayReading: '～やすい', isAffix: true },
  { id: '押し入れ#おしいれ', level: 'N4', expression: '押し入れ', reading: 'おしいれ', meaning: 'closet' },
  { id: '電灯#でんとう', level: 'N4', expression: '電灯', reading: 'でんとう', meaning: 'electric light' },
  { id: '叱る#しかる', level: 'N4', expression: '叱る', reading: 'しかる', meaning: 'to scold' },
  { id: 'サンダル#サンダル', level: 'N4', expression: 'サンダル', reading: 'サンダル', meaning: 'sandal' },
  { id: 'うまい#うまい', level: 'N4', expression: 'うまい', reading: 'うまい', meaning: 'delicious; skillful; fortunate' },
  { id: '変える#かえる', level: 'N4', expression: '変える', reading: 'かえる', meaning: 'to change, to alter, to vary' },
  { id: '講堂#こうどう', level: 'N4', expression: '講堂', reading: 'こうどう', meaning: 'auditorium' },
  { id: '子#こ', level: 'N4', expression: '子', reading: 'こ', meaning: 'child' },
  { id: '沸かす#わかす', level: 'N4', expression: '沸かす', reading: 'わかす', meaning: 'to boil' },
  { id: 'レジ#レジ', level: 'N4', expression: 'レジ', reading: 'レジ', meaning: 'register' },
  { id: 'しばらく#しばらく', level: 'N4', expression: 'しばらく', reading: 'しばらく', meaning: 'little while' },
  { id: '特に#とくに', level: 'N4', expression: '特に', reading: 'とくに', meaning: 'particularly' },
  { id: '空く#あく', level: 'N4', expression: '空く', reading: 'あく', meaning: 'to open, to become empty (vacant)' },
  { id: '計画#けいかくする', level: 'N4', expression: '計画', reading: 'けいかくする', meaning: 'plan, project, schedule' },
  { id: '通り#とおり', level: 'N4', expression: '通り', reading: 'とおり', meaning: '~ Street, ~ Avenue' },
  { id: '下着#したぎ', level: 'N4', expression: '下着', reading: 'したぎ', meaning: 'underwear' },
  { id: '経済#けいざい', level: 'N4', expression: '経済', reading: 'けいざい', meaning: 'economics, finance, economy' },
  { id: 'こう#こう', level: 'N4', expression: 'こう', reading: 'こう', meaning: 'like this, this way' },
  { id: '裏#うら', level: 'N4', expression: '裏', reading: 'うら', meaning: 'reverse side, back' },
  { id: '為#ため', level: 'N4', expression: '為', reading: 'ため', meaning: 'good, advantage, in order to' },
  { id: 'おいでになる#おいでになる', level: 'N4', expression: 'おいでになる', reading: 'おいでになる', meaning: '(hon.) to be' },
  { id: '変わる#かわる', level: 'N4', expression: '変わる', reading: 'かわる', meaning: 'to change (v.i.), to be transformed, to vary' },
  { id: '以外#いがい', level: 'N4', expression: '以外', reading: 'いがい', meaning: 'other than, with the exception of, excepting' },
  { id: '済む#すむ', level: 'N4', expression: '済む', reading: 'すむ', meaning: 'to finish, to end' },
  { id: 'ハンバーグ#ハンバーグ', level: 'N4', expression: 'ハンバーグ', reading: 'ハンバーグ', meaning: 'hamburger steak' },
  { id: '市#し', level: 'N4', expression: '市', reading: 'し', meaning: 'city' },
  { id: '引き出し#ひきだし', level: 'N4', expression: '引き出し', reading: 'ひきだし', meaning: 'drawer' },
  { id: '遊び#あそび', level: 'N4', expression: '遊び', reading: 'あそび', meaning: 'play' },
  { id: '支度#したくする', level: 'N4', expression: '支度', reading: 'したくする', meaning: 'preparation' },
  { id: '～始める#はじめる', level: 'N4', expression: '～始める', reading: 'はじめる', meaning: 'to start doing ~', displayReading: '～はじめる', isAffix: true },
  { id: '十分#じゅうぶん', level: 'N4', expression: '十分', reading: 'じゅうぶん', meaning: 'enough' },
  { id: 'きっと#きっと', level: 'N4', expression: 'きっと', reading: 'きっと', meaning: 'surely, definitely, undoubtedly, certainly' },
  { id: '遠く#とおく', level: 'N4', expression: '遠く', reading: 'とおく', meaning: 'far away, distant' },
  { id: '大体#だいたい', level: 'N4', expression: '大体', reading: 'だいたい', meaning: 'approximately; in most cases; in general; to begin with (same as もともと)' },
  { id: '折れる#おれる', level: 'N4', expression: '折れる', reading: 'おれる', meaning: 'to break, to be folded, to give in; to turn (a corner)' },
  { id: '正しい#ただしい', level: 'N4', expression: '正しい', reading: 'ただしい', meaning: 'correct' },
  { id: '輸入#ゆにゅう', level: 'N4', expression: '輸入', reading: 'ゆにゅう', meaning: 'import' },
  { id: '返事#へんじ', level: 'N4', expression: '返事', reading: 'へんじ', meaning: 'reply, answer' },
  { id: '都#と', level: 'N4', expression: '都', reading: 'と', meaning: 'metropolitan' },
  { id: '産業#さんぎょう', level: 'N4', expression: '産業', reading: 'さんぎょう', meaning: 'industry' },
  { id: 'お金持ち#かねもち', level: 'N4', expression: 'お金持ち', reading: 'かねもち', meaning: 'rich person', displayReading: 'かねもち; おかねもち' },
  { id: '説明#せつめい', level: 'N4', expression: '説明', reading: 'せつめい', meaning: 'explanation' },
  { id: '島#しま', level: 'N4', expression: '島', reading: 'しま', meaning: 'island' },
  { id: '道具#どうぐ', level: 'N4', expression: '道具', reading: 'どうぐ', meaning: 'tool' },
  { id: '滑る#すべる', level: 'N4', expression: '滑る', reading: 'すべる', meaning: 'to slide, to slip' },
  { id: 'それほど#それほど', level: 'N4', expression: 'それほど', reading: 'それほど', meaning: 'to that degree; extent' },
  { id: '以上#いじょう', level: 'N4', expression: '以上', reading: 'いじょう', meaning: 'more than; this is all' },
  { id: '～まま#まま', level: 'N4', expression: '～まま', reading: 'まま', meaning: 'as it is', displayReading: '～まま', isAffix: true },
  { id: '特急#とっきゅう', level: 'N4', expression: '特急', reading: 'とっきゅう', meaning: 'limited express (train faster than an express)' },
  { id: '～(に) よると#よると', level: 'N4', expression: '～(に) よると', reading: 'よると', meaning: 'according to ~', displayReading: '～(に) よると', isAffix: true },
  { id: '妻#つま', level: 'N4', expression: '妻', reading: 'つま', meaning: 'wife (humble)' },
  { id: '帰り#かえり', level: 'N4', expression: '帰り', reading: 'かえり', meaning: 'return, coming back' },
  { id: '具合#ぐあい', level: 'N4', expression: '具合', reading: 'ぐあい', meaning: 'condition, state, health' },
  { id: '堅#かたい', level: 'N4', expression: '堅', reading: 'かたい', meaning: 'solid, hard, firm' },
  { id: '駐車場#ちゅうしゃじょう', level: 'N4', expression: '駐車場', reading: 'ちゅうしゃじょう', meaning: 'parking lot' },
  { id: 'スーツ#スーツ', level: 'N4', expression: 'スーツ', reading: 'スーツ', meaning: 'suit' },
  { id: '危険#きけん', level: 'N4', expression: '危険', reading: 'きけん', meaning: 'danger, risk, hazard' },
  { id: '間#あいだ', level: 'N4', expression: '間', reading: 'あいだ', meaning: 'space, interval' },
  { id: '卒業#そつぎょう', level: 'N4', expression: '卒業', reading: 'そつぎょう', meaning: 'graduation' },
  { id: 'それで#それで', level: 'N4', expression: 'それで', reading: 'それで', meaning: 'and (conj.), thereupon, because of that' },
  { id: '枝#えだ', level: 'N4', expression: '枝', reading: 'えだ', meaning: 'branch, twig' },
  { id: 'そろそろ#そろそろ', level: 'N4', expression: 'そろそろ', reading: 'そろそろ', meaning: 'gradually, soon' },
  { id: 'あげる#あげる', level: 'N4', expression: 'あげる', reading: 'あげる', meaning: 'to give' },
  { id: '騒ぐ#さわぐ', level: 'N4', expression: '騒ぐ', reading: 'さわぐ', meaning: 'to make noise, to clamor' },
  { id: '尋ねる#たずねる', level: 'N4', expression: '尋ねる', reading: 'たずねる', meaning: 'to inquire (same as 質問する)' },
  { id: '放送#ほうそうする', level: 'N4', expression: '放送', reading: 'ほうそうする', meaning: 'broadcasting' },
  { id: '市民#しみん', level: 'N4', expression: '市民', reading: 'しみん', meaning: 'citizen' },
  { id: 'ファックス#ファックス', level: 'N4', expression: 'ファックス', reading: 'ファックス', meaning: 'fax' },
  { id: '負ける#まける', level: 'N4', expression: '負ける', reading: 'まける', meaning: 'to lose (a game) (v.i.), to be defeated' },
  { id: '田舎#いなか', level: 'N4', expression: '田舎', reading: 'いなか', meaning: 'rural, countryside' },
  { id: '講義#こうぎ', level: 'N4', expression: '講義', reading: 'こうぎ', meaning: 'a lecture' },
  { id: 'そんなに#そんなに', level: 'N4', expression: 'そんなに', reading: 'そんなに', meaning: 'so much, like that' },
  { id: '昼休み#ひるやすみ', level: 'N4', expression: '昼休み', reading: 'ひるやすみ', meaning: 'lunch break, noon recess' },
  { id: '忘れ物#わすれもの', level: 'N4', expression: '忘れ物', reading: 'わすれもの', meaning: 'lost article, something forgotten' },
  { id: '下りる#おりる', level: 'N4', expression: '下りる', reading: 'おりる', meaning: 'to get down, to go; come down' },
  { id: '腕#うで', level: 'N4', expression: '腕', reading: 'うで', meaning: 'arm (in reference to body)' },
  { id: '訳#わけ', level: 'N4', expression: '訳', reading: 'わけ', meaning: 'reason; explanation' },
  { id: '承知#しょうちする', level: 'N4', expression: '承知', reading: 'しょうちする', meaning: 'consent, acceptance' },
  { id: '高校#こうこう', level: 'N4', expression: '高校', reading: 'こうこう', meaning: 'high school; senior high school', displayReading: 'こうこう; こうとうがっこう' },
  { id: '似る#にる', level: 'N4', expression: '似る', reading: 'にる', meaning: 'to resemble, to be similar' },
  { id: '～おわる#おわる', level: 'N4', expression: '～おわる', reading: 'おわる', meaning: 'to finish doing ~', displayReading: '～おわる', isAffix: true },
  { id: '暖房#だんぼう', level: 'N4', expression: '暖房', reading: 'だんぼう', meaning: 'heating' },
  { id: '割合#わりあい', level: 'N4', expression: '割合', reading: 'わりあい', meaning: 'rate, ratio, percentage' },
  { id: '寺#てら', level: 'N4', expression: '寺', reading: 'てら', meaning: 'Buddhist temple' },
  { id: '慣れる#なれる', level: 'N4', expression: '慣れる', reading: 'なれる', meaning: 'to grow accustomed to' },
  { id: '普通#ふつう', level: 'N4', expression: '普通', reading: 'ふつう', meaning: 'common; usual' },
  { id: '手伝う#てつだう', level: 'N4', expression: '手伝う', reading: 'てつだう', meaning: 'to help' },
  { id: 'なるほど#なるほど', level: 'N4', expression: 'なるほど', reading: 'なるほど', meaning: 'I see; I now understand' },
  { id: 'くださる#くださる', level: 'N4', expression: 'くださる', reading: 'くださる', meaning: '(hon.) to give, to confer' },
  { id: '息子#むすこ', level: 'N4', expression: '息子', reading: 'むすこ', meaning: '(humble) son' },
  { id: '会場#かいじょう', level: 'N4', expression: '会場', reading: 'かいじょう', meaning: 'venue, meeting place' },
  { id: '笑う#わらう', level: 'N4', expression: '笑う', reading: 'わらう', meaning: 'to laugh, to smile' },
  { id: '光#ひかり', level: 'N4', expression: '光', reading: 'ひかり', meaning: 'light' },
  { id: 'お見舞い#おみまい', level: 'N4', expression: 'お見舞い', reading: 'おみまい', meaning: 'calling on someone who is ill, visit' },
  { id: '席#せき', level: 'N4', expression: '席', reading: 'せき', meaning: 'a seat' },
  { id: '～様#さま', level: 'N4', expression: '～様', reading: 'さま', meaning: 'Mr., Mrs., Ms.', displayReading: '～さま', isAffix: true },
  { id: 'ご存じ#ごぞんじ', level: 'N4', expression: 'ご存じ', reading: 'ごぞんじ', meaning: 'knowing, acquaintance' },
  { id: '下る#さがる', level: 'N4', expression: '下る', reading: 'さがる', meaning: 'to descend, to drop, to fall' },
  { id: 'アジア#アジア', level: 'N4', expression: 'アジア', reading: 'アジア', meaning: 'Asia' },
  { id: '空く#すく', level: 'N4', expression: '空く', reading: 'すく', meaning: 'to be empty (in reference to people), to be less crowded' },
  { id: 'あ#あ', level: 'N4', expression: 'あ', reading: 'あ', meaning: 'Ah' },
  { id: '最も#もっとも', level: 'N4', expression: '最も', reading: 'もっとも', meaning: 'most' },
  { id: '合う#あう', level: 'N4', expression: '合う', reading: 'あう', meaning: 'to fit, to match' },
  { id: '～代#だい', level: 'N4', expression: '～代', reading: 'だい', meaning: '~ age; period', displayReading: '～だい', isAffix: true },
  { id: '最後#さいご', level: 'N4', expression: '最後', reading: 'さいご', meaning: 'last, end' },
  { id: '値段#ねだん', level: 'N4', expression: '値段', reading: 'ねだん', meaning: 'price' },
  { id: '退院#たいいんする', level: 'N4', expression: '退院', reading: 'たいいんする', meaning: 'leaving hospital' },
  { id: '展覧会#てんらんかい', level: 'N4', expression: '展覧会', reading: 'てんらんかい', meaning: 'exhibition' },
  { id: '汽車#きしゃ', level: 'N4', expression: '汽車', reading: 'きしゃ', meaning: 'train (steam)' },
  { id: '見つかる#みつかる', level: 'N4', expression: '見つかる', reading: 'みつかる', meaning: 'to be found (v.i.), to be discovered' },
  { id: '注射#ちゅうしゃ', level: 'N4', expression: '注射', reading: 'ちゅうしゃ', meaning: 'injection' },
  { id: '様#よう', level: 'N4', expression: '様', reading: 'よう', meaning: 'way, manner, kind' },
  { id: '～おき#おき', level: 'N4', expression: '～おき', reading: 'おき', meaning: 'after every ~', displayReading: '～おき', isAffix: true },
  { id: '最初#さいしょ', level: 'N4', expression: '最初', reading: 'さいしょ', meaning: 'beginning, first' },
  { id: '御～#ご', level: 'N4', expression: '御～', reading: 'ご', meaning: 'honorable ~', displayReading: 'ご～', isAffix: true },
  { id: '安心#あんしん', level: 'N4', expression: '安心', reading: 'あんしん', meaning: 'peace of mind, relief' },
  { id: '直る#なおる', level: 'N4', expression: '直る', reading: 'なおる', meaning: 'to be fixed' },
  { id: '続く#つづく', level: 'N4', expression: '続く', reading: 'つづく', meaning: 'to be continued' },
  { id: '世話#せわする', level: 'N4', expression: '世話', reading: 'せわする', meaning: 'looking after; to look after' },
  { id: '近所#きんじょ', level: 'N4', expression: '近所', reading: 'きんじょ', meaning: 'neighborhood' },
  { id: '億#おく', level: 'N4', expression: '億', reading: 'おく', meaning: 'hundred million' },
  { id: '数学#すうがく', level: 'N4', expression: '数学', reading: 'すうがく', meaning: 'mathematics' },
  { id: '習慣#しゅうかん', level: 'N4', expression: '習慣', reading: 'しゅうかん', meaning: 'custom (in reference to culture)' },
  { id: '焼ける#やける', level: 'N4', expression: '焼ける', reading: 'やける', meaning: 'to burn, to be roasted' },
  { id: '君#きみ', level: 'N4', expression: '君', reading: 'きみ', meaning: 'you (informal for men)' },
  { id: '冷える#ひえる', level: 'N4', expression: '冷える', reading: 'ひえる', meaning: 'to grow cold, to cool down' },
  { id: '点く#つく', level: 'N4', expression: '点く', reading: 'つく', meaning: 'to be started, to be switched on' },
  { id: '落す#おとす', level: 'N4', expression: '落す', reading: 'おとす', meaning: 'to drop, to lose' },
  { id: '明日#あす', level: 'N4', expression: '明日', reading: 'あす', meaning: 'tomorrow' },
  { id: '出発#しゅっぱつする', level: 'N4', expression: '出発', reading: 'しゅっぱつする', meaning: 'departure' },
  { id: '拝見#はいけんする', level: 'N4', expression: '拝見', reading: 'はいけんする', meaning: '(humble) (polite) seeing, look at' },
  { id: '割れる#われる', level: 'N4', expression: '割れる', reading: 'われる', meaning: 'to break' },
  { id: '背中#せなか', level: 'N4', expression: '背中', reading: 'せなか', meaning: 'back (of body)' },
  { id: '新聞社#しんぶんしゃ', level: 'N4', expression: '新聞社', reading: 'しんぶんしゃ', meaning: 'newspaper company' },
  { id: '～君#くん', level: 'N4', expression: '～君', reading: 'くん', meaning: 'Mr. (junior) ~, master ~', displayReading: '～くん', isAffix: true },
  { id: '濡れる#ぬれる', level: 'N4', expression: '濡れる', reading: 'ぬれる', meaning: 'to get wet' },
  { id: '倒れる#たおれる', level: 'N4', expression: '倒れる', reading: 'たおれる', meaning: 'to collapse, to break down' },
  { id: 'スーパー (マーケット)#スーパー', level: 'N4', expression: 'スーパー (マーケット)', reading: 'スーパー', meaning: 'supermarket', displayReading: 'スーパー (マーケット)' },
  { id: 'アクセサリー#アクセサリー', level: 'N4', expression: 'アクセサリー', reading: 'アクセサリー', meaning: 'accessory' },
  { id: '向かう#むかう', level: 'N4', expression: '向かう', reading: 'むかう', meaning: 'to face, to go towards' },
  { id: '仕方#しかた', level: 'N4', expression: '仕方', reading: 'しかた', meaning: 'way (of doing something)' },
  { id: '首#くび', level: 'N4', expression: '首', reading: 'くび', meaning: 'neck' },
  { id: '程#ほど', level: 'N4', expression: '程', reading: 'ほど', meaning: 'degree, extent' },
  { id: '代わり#かわり', level: 'N4', expression: '代わり', reading: 'かわり', meaning: 'substitute, replacement' },
  { id: '失敗#しっぱい', level: 'N4', expression: '失敗', reading: 'しっぱい', meaning: 'failure, mistake' },
  { id: '工業#こうぎょう', level: 'N4', expression: '工業', reading: 'こうぎょう', meaning: '(manufacturing) industry' },
  { id: '移る#うつる', level: 'N4', expression: '移る', reading: 'うつる', meaning: 'to move (from a house); to transfer (from a department); to shift' },
  { id: 'スーツケース#スーツケース', level: 'N4', expression: 'スーツケース', reading: 'スーツケース', meaning: 'suitcase' },
  { id: '研究室#けんきゅうしつ', level: 'N4', expression: '研究室', reading: 'けんきゅうしつ', meaning: 'the professor\'s office; laboratory' },
  { id: '紹介#しょうかい', level: 'N4', expression: '紹介', reading: 'しょうかい', meaning: 'an introduction' },
  { id: 'けれど#けれど', level: 'N4', expression: 'けれど', reading: 'けれど', meaning: 'but, although', displayReading: 'けれど; けれども' },
  { id: '舟#ふね', level: 'N4', expression: '舟', reading: 'ふね', meaning: 'ship, boat' },
  { id: '動く#うごく', level: 'N4', expression: '動く', reading: 'うごく', meaning: 'to move' },
  { id: '～(に) ついて#ついて', level: 'N4', expression: '～(に) ついて', reading: 'ついて', meaning: 'about, concerning', displayReading: '～(に) ついて', isAffix: true },
  { id: '虫#むし', level: 'N4', expression: '虫', reading: 'むし', meaning: 'insect' },
  { id: 'コンピュータ#コンピュータ', level: 'N4', expression: 'コンピュータ', reading: 'コンピュータ', meaning: 'computer', displayReading: 'コンピュータ; コンピューター' },
  { id: '植える#うえる', level: 'N4', expression: '植える', reading: 'うえる', meaning: 'to plant' },
  { id: '両方#りょうほう', level: 'N4', expression: '両方', reading: 'りょうほう', meaning: 'both sides, both parties' },
  { id: '汚れる#よごれる', level: 'N4', expression: '汚れる', reading: 'よごれる', meaning: 'to become dirty' },
  { id: '水泳#すいえい', level: 'N4', expression: '水泳', reading: 'すいえい', meaning: 'swimming' },
  { id: '経験#けいけんする', level: 'N4', expression: '経験', reading: 'けいけんする', meaning: 'experience' },
  { id: '勝つ#かつ', level: 'N4', expression: '勝つ', reading: 'かつ', meaning: 'to win' },
  { id: '砂#すな', level: 'N4', expression: '砂', reading: 'すな', meaning: 'sand' },
  { id: '取り替える#とりかえる', level: 'N4', expression: '取り替える', reading: 'とりかえる', meaning: 'to exchange, to replace' },
  { id: '簡単#かんたん', level: 'N4', expression: '簡単', reading: 'かんたん', meaning: 'simple' },
  { id: '全然#ぜんぜん', level: 'N4', expression: '全然', reading: 'ぜんぜん', meaning: 'not at all; wholly, entirely' },
  { id: '特別#とくべつ', level: 'N4', expression: '特別', reading: 'とくべつ', meaning: 'special' },
  { id: '復習#ふくしゅう', level: 'N4', expression: '復習', reading: 'ふくしゅう', meaning: 'review (of lessons), revision' },
  { id: '間に合う#まにあう', level: 'N4', expression: '間に合う', reading: 'まにあう', meaning: 'to be in time for' },
  { id: '役に立つ#やくにたつ', level: 'N4', expression: '役に立つ', reading: 'やくにたつ', meaning: 'to be helpful, to be useful' },
  { id: '真中#まんなか', level: 'N4', expression: '真中', reading: 'まんなか', meaning: 'middle, center' },
  { id: '研究#けんきゅう', level: 'N4', expression: '研究', reading: 'けんきゅう', meaning: 'study, research, investigation' },
  { id: '草#くさ', level: 'N4', expression: '草', reading: 'くさ', meaning: 'grass' },
  { id: '込む#こむ', level: 'N4', expression: '込む', reading: 'こむ', meaning: 'to be crowded' },
  { id: '訪ねる#たずねる', level: 'N4', expression: '訪ねる', reading: 'たずねる', meaning: 'to visit' },
  { id: '下げる#さげる', level: 'N4', expression: '下げる', reading: 'さげる', meaning: 'to lower (v.t.); to hang' },
  { id: '花見#はなみ', level: 'N4', expression: '花見', reading: 'はなみ', meaning: 'cherry-blossom viewing' },
  { id: '途中#とちゅう', level: 'N4', expression: '途中', reading: 'とちゅう', meaning: 'on the way, midway' },
  { id: '入院#にゅういんする', level: 'N4', expression: '入院', reading: 'にゅういんする', meaning: 'hospitalization' },
  { id: '乗り換える#のりかえる', level: 'N4', expression: '乗り換える', reading: 'のりかえる', meaning: 'to transfer (trains), to change (bus, train, etc.)' },
  { id: '別れる#わかれる', level: 'N4', expression: '別れる', reading: 'わかれる', meaning: 'to part from, to separate' },
  { id: '～町#ちょう', level: 'N4', expression: '～町', reading: 'ちょう', meaning: 'the town of ~', displayReading: '～ちょう', isAffix: true },
  { id: '安全#あんぜん', level: 'N4', expression: '安全', reading: 'あんぜん', meaning: 'safety, security' },
  { id: '看護婦#かんごふ', level: 'N4', expression: '看護婦', reading: 'かんごふ', meaning: '(female) nurse' },
  { id: '見物#けんぶつ', level: 'N4', expression: '見物', reading: 'けんぶつ', meaning: 'sightseeing' },
  { id: '相談#そうだんする', level: 'N4', expression: '相談', reading: 'そうだんする', meaning: 'consultation' },
  { id: 'ガソリンスタンド#ガソリンスタンド', level: 'N4', expression: 'ガソリンスタンド', reading: 'ガソリンスタンド', meaning: 'gas station, service station' },
  { id: '眠る#ねむる', level: 'N4', expression: '眠る', reading: 'ねむる', meaning: 'to sleep' },
  { id: '上がる#あがる', level: 'N4', expression: '上がる', reading: 'あがる', meaning: 'to rise, to go up' },
  { id: '翻訳#ほんやく', level: 'N4', expression: '翻訳', reading: 'ほんやく', meaning: 'translation' },
  { id: '食事#しょくじする', level: 'N4', expression: '食事', reading: 'しょくじする', meaning: 'meal' },
  { id: '娘#むすめ', level: 'N4', expression: '娘', reading: 'むすめ', meaning: 'daughter (humble)' },
  { id: '湯#ゆ', level: 'N4', expression: '湯', reading: 'ゆ', meaning: 'hot water' },
  { id: '競争#きょうそう', level: 'N4', expression: '競争', reading: 'きょうそう', meaning: 'competition, contest' },
  { id: '集まる#あつまる', level: 'N4', expression: '集まる', reading: 'あつまる', meaning: 'to gather (v.i.), to collect' },
  { id: '～にくい#にくい', level: 'N4', expression: '～にくい', reading: 'にくい', meaning: 'difficult to do ~', displayReading: '～にくい', isAffix: true },
  { id: '生活#せいかつする', level: 'N4', expression: '生活', reading: 'せいかつする', meaning: 'living, life; to live' },
  { id: '糸#いと', level: 'N4', expression: '糸', reading: 'いと', meaning: 'thread' },
  { id: '関係#かんけい', level: 'N4', expression: '関係', reading: 'かんけい', meaning: 'relation(ship), connection' },
  { id: '～目#め', level: 'N4', expression: '～目', reading: 'め', meaning: 'number ~ sequence, ~nd; ~th', displayReading: '～め', isAffix: true },
  { id: '急#きゅう', level: 'N4', expression: '急', reading: 'きゅう', meaning: 'urgent, sudden; steep' },
  { id: '棚#たな', level: 'N4', expression: '棚', reading: 'たな', meaning: 'shelves, rack' },
  { id: '木綿#もめん', level: 'N4', expression: '木綿', reading: 'もめん', meaning: 'cotton' },
  { id: '輸出#ゆしゅつする', level: 'N4', expression: '輸出', reading: 'ゆしゅつする', meaning: 'export' },
  { id: 'タイプ#タイプ', level: 'N4', expression: 'タイプ', reading: 'タイプ', meaning: 'type, style' },
  { id: 'すり#すり', level: 'N4', expression: 'すり', reading: 'すり', meaning: 'pickpocket' },
  { id: 'アルコール#アルコール', level: 'N4', expression: 'アルコール', reading: 'アルコール', meaning: 'alcohol' },
  { id: 'ソフト#ソフト', level: 'N4', expression: 'ソフト', reading: 'ソフト', meaning: 'soft; soft hat; software' },
  { id: '神社#じんじゃ', level: 'N4', expression: '神社', reading: 'じんじゃ', meaning: 'Shinto shrine' },
  { id: '大分#だいぶ', level: 'N4', expression: '大分', reading: 'だいぶ', meaning: 'fairly well, to a large extent, considerably, pretty much' },
  { id: '楽しみ#たのしみ', level: 'N4', expression: '楽しみ', reading: 'たのしみ', meaning: 'pleasure, joy' },
  { id: '電報#でんぽう', level: 'N4', expression: '電報', reading: 'でんぽう', meaning: 'telegram' },
  { id: '家内#かない', level: 'N4', expression: '家内', reading: 'かない', meaning: '(one\'s own) wife' },
  { id: '指#ゆび', level: 'N4', expression: '指', reading: 'ゆび', meaning: 'finger' },
  { id: 'これから#これから', level: 'N4', expression: 'これから', reading: 'これから', meaning: 'from now on, after this' },
  { id: 'たまに#たまに', level: 'N4', expression: 'たまに', reading: 'たまに', meaning: 'occasionally' },
  { id: '社会#しゃかい', level: 'N4', expression: '社会', reading: 'しゃかい', meaning: 'society' },
];
