/**
 * JLPT N5 語彙（V2 §8）。**自動生成。手で編集しない。**
 *
 *   pnpm build:vocab
 *
 * 出典: elzup/jlpt-word-list（MIT License, © 2020 Jamie Sinclair / elzup）
 *       https://raw.githubusercontent.com/elzup/jlpt-word-list/master/src/n5.csv
 *
 * 語義は出典どおりの英語。中国語に機械翻訳して取り込むと、確かめようの
 * 無い誤りが「正解データ」として混ざる——語義は事実なので出典に委ねる
 * （§8）。学習者への中国語の説明は、必要なときにチューターが行う。
 *
 * 並びは Genki の課順（1〜23）を骨にし、その後ろに Genki に無い語を
 * 出典の並びのまま置く。詳細は scripts/build-jlpt-vocab.ts を参照。
 */

export interface VocabEntry {
  /** `表記#読み` で一意。同表記異読を別語として扱うため。 */
  readonly id: string;
  readonly expression: string;
  /** 仮名だけの主たる読み。振り仮名と音声合成に使う。 */
  readonly reading: string;
  /** 出典の読み表記（「いく; ゆく」「～えん」など）。 */
  readonly displayReading?: string;
  /** 出典どおりの英語の語義。 */
  readonly meaning: string;
  /** Genki の課。無い語は N5 の補遺。 */
  readonly genkiLesson?: number;
  /** 接辞（～円、～時）。単独の語として出題しない。 */
  readonly isAffix?: boolean;
}

export const VOCAB_N5: readonly VocabEntry[] = [
  { id: '医者#いしゃ', expression: '医者', reading: 'いしゃ', meaning: 'doctor; physician', genkiLesson: 1 },
  { id: '今#いま', expression: '今', reading: 'いま', meaning: 'now', genkiLesson: 1 },
  { id: '妹#いもうと', expression: '妹', reading: 'いもうと', meaning: 'younger sister (humble)', genkiLesson: 1 },
  { id: '英語#えいご', expression: '英語', reading: 'えいご', meaning: 'English (language)', genkiLesson: 1 },
  { id: 'ええ#ええ', expression: 'ええ', reading: 'ええ', meaning: 'yes', genkiLesson: 1 },
  { id: 'お母さん#おかあさん', expression: 'お母さん', reading: 'おかあさん', meaning: 'mother (formal)', genkiLesson: 1 },
  { id: 'お父さん#おとうさん', expression: 'お父さん', reading: 'おとうさん', meaning: 'father (formal)', genkiLesson: 1 },
  { id: '弟#おとうと', expression: '弟', reading: 'おとうと', meaning: 'younger brother', genkiLesson: 1 },
  { id: 'お兄さん#おにいさん', expression: 'お兄さん', reading: 'おにいさん', meaning: '(someone else\'s) older brother (formal)', genkiLesson: 1 },
  { id: 'お姉さん#おねえさん', expression: 'お姉さん', reading: 'おねえさん', meaning: 'older sister (formal)', genkiLesson: 1 },
  { id: '学生#がくせい', expression: '学生', reading: 'がくせい', meaning: 'student', genkiLesson: 1 },
  { id: '午後#ごご', expression: '午後', reading: 'ごご', meaning: 'afternoon, P.M.', genkiLesson: 1 },
  { id: '午前#ごぜん', expression: '午前', reading: 'ごぜん', meaning: 'morning, A.M.', genkiLesson: 1 },
  { id: '仕事#しごと', expression: '仕事', reading: 'しごと', meaning: 'work, job, occupation, employment', genkiLesson: 1 },
  { id: '先生#せんせい', expression: '先生', reading: 'せんせい', meaning: 'teacher, professor; master; doctor', genkiLesson: 1 },
  { id: '大学#だいがく', expression: '大学', reading: 'だいがく', meaning: 'college; university', genkiLesson: 1 },
  { id: '電話#でんわ', expression: '電話', reading: 'でんわ', meaning: 'a telephone', genkiLesson: 1 },
  { id: '友達#ともだち', expression: '友達', reading: 'ともだち', meaning: 'friend', genkiLesson: 1 },
  { id: '何#なん', expression: '何', reading: 'なん', meaning: 'what', displayReading: 'なん; なに', genkiLesson: 1 },
  { id: '名前#なまえ', expression: '名前', reading: 'なまえ', meaning: 'name', genkiLesson: 1 },
  { id: 'はい#はい', expression: 'はい', reading: 'はい', meaning: 'yes', genkiLesson: 1 },
  { id: '半#はん', expression: '半', reading: 'はん', meaning: 'half (e.g., にじはん | half-past two)', genkiLesson: 1 },
  { id: '番号#ばんごう', expression: '番号', reading: 'ばんごう', meaning: 'number, series of digits', genkiLesson: 1 },
  { id: '留学生#りゅうがくせい', expression: '留学生', reading: 'りゅうがくせい', meaning: 'international student', genkiLesson: 1 },
  { id: '私#わたし', expression: '私', reading: 'わたし', meaning: 'I, myself', genkiLesson: 1 },
  { id: 'あそこ#あそこ', expression: 'あそこ', reading: 'あそこ', meaning: 'there, over there, that place', genkiLesson: 2 },
  { id: 'あれ#あれ', expression: 'あれ', reading: 'あれ', meaning: 'that one (over there)', genkiLesson: 2 },
  { id: 'いくら#いくら', expression: 'いくら', reading: 'いくら', meaning: 'how much, how many', genkiLesson: 2 },
  { id: '鉛筆#えんぴつ', expression: '鉛筆', reading: 'えんぴつ', meaning: 'pencil', genkiLesson: 2 },
  { id: 'お手洗い#おてあらい', expression: 'お手洗い', reading: 'おてあらい', meaning: 'toilet, restroom, bathroom (lit., a place to wash one\'s hands)', genkiLesson: 2 },
  { id: '傘#かさ', expression: '傘', reading: 'かさ', meaning: 'umbrella, parasol', genkiLesson: 2 },
  { id: 'かばん#かばん', expression: 'かばん', reading: 'かばん', meaning: 'bag, basket', genkiLesson: 2 },
  { id: '喫茶店#きっさてん', expression: '喫茶店', reading: 'きっさてん', meaning: 'café', genkiLesson: 2 },
  { id: '銀行#ぎんこう', expression: '銀行', reading: 'ぎんこう', meaning: 'bank', genkiLesson: 2 },
  { id: '靴#くつ', expression: '靴', reading: 'くつ', meaning: 'shoes, footwear', genkiLesson: 2 },
  { id: 'これ#これ', expression: 'これ', reading: 'これ', meaning: 'this one', genkiLesson: 2 },
  { id: '財布#さいふ', expression: '財布', reading: 'さいふ', meaning: 'wallet', genkiLesson: 2 },
  { id: '魚#さかな', expression: '魚', reading: 'さかな', meaning: 'fish', genkiLesson: 2 },
  { id: '辞書#じしょ', expression: '辞書', reading: 'じしょ', meaning: 'dictionary', genkiLesson: 2 },
  { id: '自転車#じてんしゃ', expression: '自転車', reading: 'じてんしゃ', meaning: 'bicycle', genkiLesson: 2 },
  { id: '新聞#しんぶん', expression: '新聞', reading: 'しんぶん', meaning: 'newspaper', genkiLesson: 2 },
  { id: 'それ#それ', expression: 'それ', reading: 'それ', meaning: 'that one', genkiLesson: 2 },
  { id: '高い#たかい', expression: '高い', reading: 'たかい', meaning: 'tall, high; expensive', genkiLesson: 2 },
  { id: '誰#だれ', expression: '誰', reading: 'だれ', meaning: 'who', genkiLesson: 2 },
  { id: 'テープ#テープ', expression: 'テープ', reading: 'テープ', meaning: 'tape', genkiLesson: 2 },
  { id: 'どうも#どうも', expression: 'どうも', reading: 'どうも', meaning: 'Thank you; somehow; no matter how hard one may try', genkiLesson: 2 },
  { id: '時計#とけい', expression: '時計', reading: 'とけい', meaning: 'a watch; a clock', genkiLesson: 2 },
  { id: 'どこ#どこ', expression: 'どこ', reading: 'どこ', meaning: 'where, what place', genkiLesson: 2 },
  { id: '図書館#としょかん', expression: '図書館', reading: 'としょかん', meaning: 'library', genkiLesson: 2 },
  { id: 'どれ#どれ', expression: 'どれ', reading: 'どれ', meaning: 'which one', genkiLesson: 2 },
  { id: '肉#にく', expression: '肉', reading: 'にく', meaning: 'meat', genkiLesson: 2 },
  { id: 'ノート#ノート', expression: 'ノート', reading: 'ノート', meaning: 'notebook', genkiLesson: 2 },
  { id: 'ペン#ペン', expression: 'ペン', reading: 'ペン', meaning: 'pen', genkiLesson: 2 },
  { id: '帽子#ぼうし', expression: '帽子', reading: 'ぼうし', meaning: 'hat; cap', genkiLesson: 2 },
  { id: '本#ほん', expression: '本', reading: 'ほん', meaning: 'book', genkiLesson: 2 },
  { id: '野菜#やさい', expression: '野菜', reading: 'やさい', meaning: 'vegetable', genkiLesson: 2 },
  { id: '郵便局#ゆうびんきょく', expression: '郵便局', reading: 'ゆうびんきょく', meaning: 'post office', genkiLesson: 2 },
  { id: '朝#あさ', expression: '朝', reading: 'あさ', meaning: 'morning', genkiLesson: 3 },
  { id: '朝御飯#あさごはん', expression: '朝御飯', reading: 'あさごはん', meaning: 'breakfast', genkiLesson: 3 },
  { id: '明日#あした', expression: '明日', reading: 'あした', meaning: 'tomorrow', genkiLesson: 3 },
  { id: '家#いえ', expression: '家', reading: 'いえ', meaning: 'house, home', genkiLesson: 3 },
  { id: 'いつ#いつ', expression: 'いつ', reading: 'いつ', meaning: 'when', genkiLesson: 3 },
  { id: 'うち#うち', expression: 'うち', reading: 'うち', meaning: 'home; house; my place', genkiLesson: 3 },
  { id: '映画#えいが', expression: '映画', reading: 'えいが', meaning: 'movie, film', genkiLesson: 3 },
  { id: '起きる#おきる', expression: '起きる', reading: 'おきる', meaning: 'to get up (e.g., from sleeping); to happen', genkiLesson: 3 },
  { id: 'お酒#おさけ', expression: 'お酒', reading: 'おさけ', meaning: 'sake; alcohol', genkiLesson: 3 },
  { id: 'お茶#おちゃ', expression: 'お茶', reading: 'おちゃ', meaning: '(green) tea', genkiLesson: 3 },
  { id: '音楽#おんがく', expression: '音楽', reading: 'おんがく', meaning: 'Music', genkiLesson: 3 },
  { id: '学校#がっこう', expression: '学校', reading: 'がっこう', meaning: 'a school', genkiLesson: 3 },
  { id: '今日#きょう', expression: '今日', reading: 'きょう', meaning: 'today, this day', genkiLesson: 3 },
  { id: 'コーヒー#コーヒー', expression: 'コーヒー', reading: 'コーヒー', meaning: 'coffee', genkiLesson: 3 },
  { id: '今晩#こんばん', expression: '今晩', reading: 'こんばん', meaning: 'tonight, this evening', genkiLesson: 3 },
  { id: '雑誌#ざっし', expression: '雑誌', reading: 'ざっし', meaning: 'magazine, journal', genkiLesson: 3 },
  { id: 'スポーツ#スポーツ', expression: 'スポーツ', reading: 'スポーツ', meaning: 'sport(s)', genkiLesson: 3 },
  { id: 'ちょっと#ちょっと', expression: 'ちょっと', reading: 'ちょっと', meaning: 'a little, somewhat; just a little, somewhat', genkiLesson: 3 },
  { id: 'テレビ#テレビ', expression: 'テレビ', reading: 'テレビ', meaning: 'television, TV', genkiLesson: 3 },
  { id: '時々#ときどき', expression: '時々', reading: 'ときどき', meaning: 'sometimes', genkiLesson: 3 },
  { id: '土曜日#どようび', expression: '土曜日', reading: 'どようび', meaning: 'Saturday', genkiLesson: 3 },
  { id: '日曜日#にちようび', expression: '日曜日', reading: 'にちようび', meaning: 'Sunday', genkiLesson: 3 },
  { id: '寝る#ねる', expression: '寝る', reading: 'ねる', meaning: 'to sleep; to go to sleep; to go to bed', genkiLesson: 3 },
  { id: '早い#はやい', expression: '早い', reading: 'はやい', meaning: 'early', genkiLesson: 3 },
  { id: '晩御飯#ばんごはん', expression: '晩御飯', reading: 'ばんごはん', meaning: 'dinner, evening meal', genkiLesson: 3 },
  { id: '昼御飯#ひるごはん', expression: '昼御飯', reading: 'ひるごはん', meaning: 'lunch, midday meal', genkiLesson: 3 },
  { id: '毎日#まいにち', expression: '毎日', reading: 'まいにち', meaning: 'every day', genkiLesson: 3 },
  { id: '毎晩#まいばん', expression: '毎晩', reading: 'まいばん', meaning: 'every night', genkiLesson: 3 },
  { id: '水#みず', expression: '水', reading: 'みず', meaning: 'water', genkiLesson: 3 },
  { id: 'あなた#あなた', expression: 'あなた', reading: 'あなた', meaning: 'you', genkiLesson: 4 },
  { id: '犬#いぬ', expression: '犬', reading: 'いぬ', meaning: 'dog', genkiLesson: 4 },
  { id: '買い物#かいもの', expression: '買い物', reading: 'かいもの', meaning: 'shopping', genkiLesson: 4 },
  { id: '火曜日#かようび', expression: '火曜日', reading: 'かようび', meaning: 'Tuesday', genkiLesson: 4 },
  { id: '昨日#きのう', expression: '昨日', reading: 'きのう', meaning: 'yesterday', genkiLesson: 4 },
  { id: '金曜日#きんようび', expression: '金曜日', reading: 'きんようび', meaning: 'Friday', genkiLesson: 4 },
  { id: 'クラス#クラス', expression: 'クラス', reading: 'クラス', meaning: 'a class', genkiLesson: 4 },
  { id: '月曜日#げつようび', expression: '月曜日', reading: 'げつようび', meaning: 'Monday', genkiLesson: 4 },
  { id: '公園#こうえん', expression: '公園', reading: 'こうえん', meaning: 'a park', genkiLesson: 4 },
  { id: 'ここ#ここ', expression: 'ここ', reading: 'ここ', meaning: 'here, this place', genkiLesson: 4 },
  { id: '子供#こども', expression: '子供', reading: 'こども', meaning: 'child(ren)', genkiLesson: 4 },
  { id: '御飯#ごはん', expression: '御飯', reading: 'ごはん', meaning: 'rice (cooked); meal', genkiLesson: 4 },
  { id: '写真#しゃしん', expression: '写真', reading: 'しゃしん', meaning: 'a picture; a photograph', genkiLesson: 4 },
  { id: '水曜日#すいようび', expression: '水曜日', reading: 'すいようび', meaning: 'Wednesday', genkiLesson: 4 },
  { id: '先週#せんしゅう', expression: '先週', reading: 'せんしゅう', meaning: 'last week', genkiLesson: 4 },
  { id: 'そこ#そこ', expression: 'そこ', reading: 'そこ', meaning: 'that place, there; bottom, sole', genkiLesson: 4 },
  { id: '机#つくえ', expression: '机', reading: 'つくえ', meaning: 'desk', genkiLesson: 4 },
  { id: '手紙#てがみ', expression: '手紙', reading: 'てがみ', meaning: 'letter', genkiLesson: 4 },
  { id: 'デパート#デパート', expression: 'デパート', reading: 'デパート', meaning: '(abbr.) department store', genkiLesson: 4 },
  { id: 'どうして#どうして', expression: 'どうして', reading: 'どうして', meaning: 'why, for what reason', genkiLesson: 4 },
  { id: '猫#ねこ', expression: '猫', reading: 'ねこ', meaning: 'cat', genkiLesson: 4 },
  { id: 'パン#パン', expression: 'パン', reading: 'パン', meaning: 'bread', genkiLesson: 4 },
  { id: '人#ひと', expression: '人', reading: 'ひと', meaning: 'man, person', genkiLesson: 4 },
  { id: '病院#びょういん', expression: '病院', reading: 'びょういん', meaning: 'hospital', genkiLesson: 4 },
  { id: 'ホテル#ホテル', expression: 'ホテル', reading: 'ホテル', meaning: 'hotel', genkiLesson: 4 },
  { id: '町#まち', expression: '町', reading: 'まち', meaning: 'town; city', genkiLesson: 4 },
  { id: '木曜日#もくようび', expression: '木曜日', reading: 'もくようび', meaning: 'Thursday', genkiLesson: 4 },
  { id: 'もしもし#もしもし', expression: 'もしもし', reading: 'もしもし', meaning: 'Hello? (used on the phone)', genkiLesson: 4 },
  { id: 'レストラン#レストラン', expression: 'レストラン', reading: 'レストラン', meaning: 'restaurant', genkiLesson: 4 },
  { id: '新しい#あたらしい', expression: '新しい', reading: 'あたらしい', meaning: 'new', genkiLesson: 5 },
  { id: '暑い#あつい', expression: '暑い', reading: 'あつい', meaning: 'hot (in reference to weather), warm', genkiLesson: 5 },
  { id: '熱い#あつい', expression: '熱い', reading: 'あつい', meaning: 'hot (objects)', genkiLesson: 5 },
  { id: '忙しい#いそがしい', expression: '忙しい', reading: 'いそがしい', meaning: 'busy (people, days)', genkiLesson: 5 },
  { id: '海#うみ', expression: '海', reading: 'うみ', meaning: 'sea, beach', genkiLesson: 5 },
  { id: '大きい#おおきい', expression: '大きい', reading: 'おおきい', meaning: 'big, large', genkiLesson: 5 },
  { id: '面白い#おもしろい', expression: '面白い', reading: 'おもしろい', meaning: 'interesting, amusing', genkiLesson: 5 },
  { id: '泳ぐ#およぐ', expression: '泳ぐ', reading: 'およぐ', meaning: 'to swim', genkiLesson: 5 },
  { id: '切手#きって', expression: '切手', reading: 'きって', meaning: 'postal (postage) stamps', genkiLesson: 5 },
  { id: '切符#きっぷ', expression: '切符', reading: 'きっぷ', meaning: 'a ticket', genkiLesson: 5 },
  { id: '寒い#さむい', expression: '寒い', reading: 'さむい', meaning: 'cold (in reference to weather)', genkiLesson: 5 },
  { id: '宿題#しゅくだい', expression: '宿題', reading: 'しゅくだい', meaning: 'homework', genkiLesson: 5 },
  { id: '大丈夫#だいじょうぶ', expression: '大丈夫', reading: 'だいじょうぶ', meaning: 'It\'s ok (all right); No need to worry; Everything is under control', genkiLesson: 5 },
  { id: '楽しい#たのしい', expression: '楽しい', reading: 'たのしい', meaning: 'enjoyable, fun', genkiLesson: 5 },
  { id: '食べ物#たべもの', expression: '食べ物', reading: 'たべもの', meaning: 'food', genkiLesson: 5 },
  { id: '誕生日#たんじょうび', expression: '誕生日', reading: 'たんじょうび', meaning: 'birthday', genkiLesson: 5 },
  { id: '小さい#ちいさい', expression: '小さい', reading: 'ちいさい', meaning: 'small, little', genkiLesson: 5 },
  { id: 'つまらない#つまらない', expression: 'つまらない', reading: 'つまらない', meaning: 'boring, dull; insignificant', genkiLesson: 5 },
  { id: '出かける#でかける', expression: '出かける', reading: 'でかける', meaning: 'to go out; to depart', genkiLesson: 5 },
  { id: 'テスト#テスト', expression: 'テスト', reading: 'テスト', meaning: 'test', genkiLesson: 5 },
  { id: '天気#てんき', expression: '天気', reading: 'てんき', meaning: 'weather', genkiLesson: 5 },
  { id: 'とても#とても', expression: 'とても', reading: 'とても', meaning: 'very (much), greatly, exceedingly', genkiLesson: 5 },
  { id: '飲み物#のみもの', expression: '飲み物', reading: 'のみもの', meaning: 'drink, beverage', genkiLesson: 5 },
  { id: '葉書#はがき', expression: '葉書', reading: 'はがき', meaning: 'postcard', genkiLesson: 5 },
  { id: 'バス#バス', expression: 'バス', reading: 'バス', meaning: 'bus; bath; bass', genkiLesson: 5 },
  { id: '飛行機#ひこうき', expression: '飛行機', reading: 'ひこうき', meaning: 'airplane', genkiLesson: 5 },
  { id: '古い#ふるい', expression: '古い', reading: 'ふるい', meaning: 'old (in reference to objects, not people), aged, ancient', genkiLesson: 5 },
  { id: '部屋#へや', expression: '部屋', reading: 'へや', meaning: 'a room', genkiLesson: 5 },
  { id: '難しい#むずかしい', expression: '難しい', reading: 'むずかしい', meaning: 'difficult', genkiLesson: 5 },
  { id: '安い#やすい', expression: '安い', reading: 'やすい', meaning: 'inexpensive; cheap (things)', genkiLesson: 5 },
  { id: '休み#やすみ', expression: '休み', reading: 'やすみ', meaning: 'holiday; day off; absence', genkiLesson: 5 },
  { id: '旅行#りょこう', expression: '旅行', reading: 'りょこう', meaning: 'travel, trip', genkiLesson: 5 },
  { id: '遊ぶ#あそぶ', expression: '遊ぶ', reading: 'あそぶ', meaning: 'to play; to spend time pleasantly; to hang out', genkiLesson: 6 },
  { id: 'お金#おかね', expression: 'お金', reading: 'おかね', meaning: 'money', genkiLesson: 6 },
  { id: 'おばあさん#おばあさん', expression: 'おばあさん', reading: 'おばあさん', meaning: 'grandmother, female senior-citizen', genkiLesson: 6 },
  { id: '漢字#かんじ', expression: '漢字', reading: 'かんじ', meaning: 'kanji; Chinese character', genkiLesson: 6 },
  { id: '今週#こんしゅう', expression: '今週', reading: 'こんしゅう', meaning: 'this week', genkiLesson: 6 },
  { id: '死ぬ#しぬ', expression: '死ぬ', reading: 'しぬ', meaning: 'to die', genkiLesson: 6 },
  { id: '立つ#たつ', expression: '立つ', reading: 'たつ', meaning: 'to stand up', genkiLesson: 6 },
  { id: '次#つぎ', expression: '次', reading: 'つぎ', meaning: 'next', genkiLesson: 6 },
  { id: '電気#でんき', expression: '電気', reading: 'でんき', meaning: 'electricity, (electric) light', genkiLesson: 6 },
  { id: '電車#でんしゃ', expression: '電車', reading: 'でんしゃ', meaning: 'electric train', genkiLesson: 6 },
  { id: '荷物#にもつ', expression: '荷物', reading: 'にもつ', meaning: 'luggage; baggage', genkiLesson: 6 },
  { id: 'ページ#ページ', expression: 'ページ', reading: 'ページ', meaning: 'a page', genkiLesson: 6 },
  { id: '窓#まど', expression: '窓', reading: 'まど', meaning: 'window', genkiLesson: 6 },
  { id: '夜#よる', expression: '夜', reading: 'よる', meaning: 'evening, night', genkiLesson: 6 },
  { id: '来週#らいしゅう', expression: '来週', reading: 'らいしゅう', meaning: 'next week', genkiLesson: 6 },
  { id: '来年#らいねん', expression: '来年', reading: 'らいねん', meaning: 'next year', genkiLesson: 6 },
  { id: '姉#あね', expression: '姉', reading: 'あね', meaning: '(my) older sister (humble)', genkiLesson: 7 },
  { id: 'アパート#アパート', expression: 'アパート', reading: 'アパート', meaning: 'apartment (abbr.)', genkiLesson: 7 },
  { id: '歌#うた', expression: '歌', reading: 'うた', meaning: 'a song', genkiLesson: 7 },
  { id: '歌う#うたう', expression: '歌う', reading: 'うたう', meaning: 'to sing', genkiLesson: 7 },
  { id: '会社#かいしゃ', expression: '会社', reading: 'かいしゃ', meaning: 'company, corporation', genkiLesson: 7 },
  { id: '家族#かぞく', expression: '家族', reading: 'かぞく', meaning: 'family, members of a family', genkiLesson: 7 },
  { id: 'かぶる#かぶる', expression: 'かぶる', reading: 'かぶる', meaning: 'to wear, to put on (e.g., a hat on the head)', genkiLesson: 7 },
  { id: '兄弟#きょうだい', expression: '兄弟', reading: 'きょうだい', meaning: 'siblings (humble), brothers and sisters', genkiLesson: 7 },
  { id: '着る#きる', expression: '着る', reading: 'きる', meaning: 'to put on (clothes above your waist); to wear', genkiLesson: 7 },
  { id: '国#くに', expression: '国', reading: 'くに', meaning: 'country; place of origin', genkiLesson: 7 },
  { id: '車#くるま', expression: '車', reading: 'くるま', meaning: 'car, vehicle', genkiLesson: 7 },
  { id: '食堂#しょくどう', expression: '食堂', reading: 'しょくどう', meaning: 'cafeteria, dining hall', genkiLesson: 7 },
  { id: '知る#しる', expression: '知る', reading: 'しる', meaning: 'to know, to understand', genkiLesson: 7 },
  { id: '父#ちち', expression: '父', reading: 'ちち', meaning: '(my) father', genkiLesson: 7 },
  { id: '長い#ながい', expression: '長い', reading: 'ながい', meaning: 'long, lengthy', genkiLesson: 7 },
  { id: 'はく#はく', expression: 'はく', reading: 'はく', meaning: 'to put on (items below your waist)', genkiLesson: 7 },
  { id: '速い#はやい', expression: '速い', reading: 'はやい', meaning: 'fast, quick', genkiLesson: 7 },
  { id: '一人#ひとり', expression: '一人', reading: 'ひとり', meaning: 'one person', genkiLesson: 7 },
  { id: '二人#ふたり', expression: '二人', reading: 'ふたり', meaning: 'two people', genkiLesson: 7 },
  { id: '短い#みじかい', expression: '短い', reading: 'みじかい', meaning: 'short (length)', genkiLesson: 7 },
  { id: '目#め', expression: '目', reading: 'め', meaning: 'eye(s)', genkiLesson: 7 },
  { id: '眼鏡#めがね', expression: '眼鏡', reading: 'めがね', meaning: 'eye glasses', genkiLesson: 7 },
  { id: '雨#あめ', expression: '雨', reading: 'あめ', meaning: 'rain', genkiLesson: 8 },
  { id: '洗う#あらう', expression: '洗う', reading: 'あらう', meaning: 'to wash', genkiLesson: 8 },
  { id: '言う#いう', expression: '言う', reading: 'いう', meaning: 'to say', genkiLesson: 8 },
  { id: 'カメラ#カメラ', expression: 'カメラ', reading: 'カメラ', meaning: 'camera', genkiLesson: 8 },
  { id: '切る#きる', expression: '切る', reading: 'きる', meaning: 'to cut; to hang up (a phone)', genkiLesson: 8 },
  { id: '今朝#けさ', expression: '今朝', reading: 'けさ', meaning: 'this morning', genkiLesson: 8 },
  { id: '今月#こんげつ', expression: '今月', reading: 'こんげつ', meaning: 'this month', genkiLesson: 8 },
  { id: '作る#つくる', expression: '作る', reading: 'つくる', meaning: 'to make, to create', genkiLesson: 8 },
  { id: '所#ところ', expression: '所', reading: 'ところ', meaning: 'place', genkiLesson: 8 },
  { id: '夏#なつ', expression: '夏', reading: 'なつ', meaning: 'summer', genkiLesson: 8 },
  { id: 'パーティー#パーティー', expression: 'パーティー', reading: 'パーティー', meaning: 'a party', genkiLesson: 8 },
  { id: '箸#はし', expression: '箸', reading: 'はし', meaning: 'chopsticks', genkiLesson: 8 },
  { id: '冬#ふゆ', expression: '冬', reading: 'ふゆ', meaning: 'winter', genkiLesson: 8 },
  { id: '毎週#まいしゅう', expression: '毎週', reading: 'まいしゅう', meaning: 'every week', genkiLesson: 8 },
  { id: '来月#らいげつ', expression: '来月', reading: 'らいげつ', meaning: 'next month', genkiLesson: 8 },
  { id: '青い#あおい', expression: '青い', reading: 'あおい', meaning: 'blue', genkiLesson: 9 },
  { id: '赤い#あかい', expression: '赤い', reading: 'あかい', meaning: 'red', genkiLesson: 9 },
  { id: '五つ#いつつ', expression: '五つ', reading: 'いつつ', meaning: 'five things', genkiLesson: 9 },
  { id: '色#いろ', expression: '色', reading: 'いろ', meaning: 'color', genkiLesson: 9 },
  { id: 'お弁当#おべんとう', expression: 'お弁当', reading: 'おべんとう', meaning: 'a boxed lunch', genkiLesson: 9 },
  { id: 'ギター#ギター', expression: 'ギター', reading: 'ギター', meaning: 'guitar', genkiLesson: 9 },
  { id: '薬#くすり', expression: '薬', reading: 'くすり', meaning: 'medicine', genkiLesson: 9 },
  { id: '黒い#くろい', expression: '黒い', reading: 'くろい', meaning: 'black; dark', genkiLesson: 9 },
  { id: '九つ#ここのつ', expression: '九つ', reading: 'ここのつ', meaning: 'nine things', genkiLesson: 9 },
  { id: '作文#さくぶん', expression: '作文', reading: 'さくぶん', meaning: 'essay; composition', genkiLesson: 9 },
  { id: '白い#しろい', expression: '白い', reading: 'しろい', meaning: 'white', genkiLesson: 9 },
  { id: '先月#せんげつ', expression: '先月', reading: 'せんげつ', meaning: 'last month', genkiLesson: 9 },
  { id: '十#とお', expression: '十', reading: 'とお', meaning: 'ten (~)', displayReading: '(〜を) とお', genkiLesson: 9, isAffix: true },
  { id: '七つ#ななつ', expression: '七つ', reading: 'ななつ', meaning: 'seven things', genkiLesson: 9 },
  { id: '始まる#はじまる', expression: '始まる', reading: 'はじまる', meaning: '(something) begins', genkiLesson: 9 },
  { id: '弾く#ひく', expression: '弾く', reading: 'ひく', meaning: 'to play (a string instrument or piano)', genkiLesson: 9 },
  { id: '一つ#ひとつ', expression: '一つ', reading: 'ひとつ', meaning: 'one thing', genkiLesson: 9 },
  { id: '病気#びょうき', expression: '病気', reading: 'びょうき', meaning: 'illness; sickness', genkiLesson: 9 },
  { id: '二つ#ふたつ', expression: '二つ', reading: 'ふたつ', meaning: 'two things', genkiLesson: 9 },
  { id: '三つ#みっつ', expression: '三つ', reading: 'みっつ', meaning: 'three things', genkiLesson: 9 },
  { id: 'みんな#みんな', expression: 'みんな', reading: 'みんな', meaning: 'all, everyone, everybody', genkiLesson: 9 },
  { id: '六つ#むっつ', expression: '六つ', reading: 'むっつ', meaning: 'six things', genkiLesson: 9 },
  { id: 'もう#もう', expression: 'もう', reading: 'もう', meaning: 'already; again; more', genkiLesson: 9 },
  { id: '八つ#やっつ', expression: '八つ', reading: 'やっつ', meaning: 'eight things', genkiLesson: 9 },
  { id: '四つ#よっつ', expression: '四つ', reading: 'よっつ', meaning: 'four things', genkiLesson: 9 },
  { id: '若い#わかい', expression: '若い', reading: 'わかい', meaning: 'young', genkiLesson: 9 },
  { id: '秋#あき', expression: '秋', reading: 'あき', meaning: 'fall (season)', genkiLesson: 10 },
  { id: '一番#いちばん', expression: '一番', reading: 'いちばん', meaning: 'best (most), first, number one', genkiLesson: 10 },
  { id: '駅#えき', expression: '駅', reading: 'えき', meaning: 'station', genkiLesson: 10 },
  { id: '遅い#おそい', expression: '遅い', reading: 'おそい', meaning: 'slow; (to be) late', genkiLesson: 10 },
  { id: '顔#かお', expression: '顔', reading: 'かお', meaning: 'face (body part)', genkiLesson: 10 },
  { id: 'かかる#かかる', expression: 'かかる', reading: 'かかる', meaning: 'it takes (amount of time, money) (v.i.)', genkiLesson: 10 },
  { id: '今年#ことし', expression: '今年', reading: 'ことし', meaning: 'this year', genkiLesson: 10 },
  { id: 'シャツ#シャツ', expression: 'シャツ', reading: 'シャツ', meaning: 'shirt', genkiLesson: 10 },
  { id: '涼しい#すずしい', expression: '涼しい', reading: 'すずしい', meaning: 'cool, refreshing (in reference to weather)', genkiLesson: 10 },
  { id: '地下鉄#ちかてつ', expression: '地下鉄', reading: 'ちかてつ', meaning: 'underground train, subway', genkiLesson: 10 },
  { id: '冷たい#つめたい', expression: '冷たい', reading: 'つめたい', meaning: 'cold (things, people)', genkiLesson: 10 },
  { id: 'どちら#どちら', expression: 'どちら', reading: 'どちら', meaning: 'which (one) (way); where (polite)', genkiLesson: 10 },
  { id: 'どっち#どっち', expression: 'どっち', reading: 'どっち', meaning: 'which one, which way', genkiLesson: 10 },
  { id: 'なる#なる', expression: 'なる', reading: 'なる', meaning: 'to become', genkiLesson: 10 },
  { id: '春#はる', expression: '春', reading: 'はる', meaning: 'spring', genkiLesson: 10 },
  { id: 'お菓子#おかし', expression: 'お菓子', reading: 'おかし', meaning: 'confections, sweets, snack', genkiLesson: 11 },
  { id: '男の子#おとこのこ', expression: '男の子', reading: 'おとこのこ', meaning: 'boy', genkiLesson: 11 },
  { id: '女の子#おんなのこ', expression: '女の子', reading: 'おんなのこ', meaning: 'girl', genkiLesson: 11 },
  { id: '外国#がいこく', expression: '外国', reading: 'がいこく', meaning: 'foreign country; abroad', genkiLesson: 11 },
  { id: 'こちら#こちら', expression: 'こちら', reading: 'こちら', meaning: 'this person (polite); this way (polite)', genkiLesson: 11 },
  { id: '授業#じゅぎょう', expression: '授業', reading: 'じゅぎょう', meaning: 'a class (of school)', genkiLesson: 11 },
  { id: '疲れる#つかれる', expression: '疲れる', reading: 'つかれる', meaning: 'to get (become) tired; to become fatigued', genkiLesson: 11 },
  { id: '取る#とる', expression: '取る', reading: 'とる', meaning: 'to take (a class); to get (a grade)', genkiLesson: 11 },
  { id: '習う#ならう', expression: '習う', reading: 'ならう', meaning: 'to learn', genkiLesson: 11 },
  { id: '働く#はたらく', expression: '働く', reading: 'はたらく', meaning: 'to work', genkiLesson: 11 },
  { id: 'もっと#もっと', expression: 'もっと', reading: 'もっと', meaning: 'more', genkiLesson: 11 },
  { id: '山#やま', expression: '山', reading: 'やま', meaning: 'mountain', genkiLesson: 11 },
  { id: '甘い#あまい', expression: '甘い', reading: 'あまい', meaning: 'generous, sweet', genkiLesson: 12 },
  { id: '痛い#いたい', expression: '痛い', reading: 'いたい', meaning: 'hurt; painful; sore', genkiLesson: 12 },
  { id: 'いつも#いつも', expression: 'いつも', reading: 'いつも', meaning: 'always, usually, every time, never (with neg. verb)', genkiLesson: 12 },
  { id: '意味#いみ', expression: '意味', reading: 'いみ', meaning: 'meaning, significance', genkiLesson: 12 },
  { id: '風邪#かぜ', expression: '風邪', reading: 'かぜ', meaning: 'cold, flu', genkiLesson: 12 },
  { id: '曇り#くもり', expression: '曇り', reading: 'くもり', meaning: 'cloudiness, cloudy weather', genkiLesson: 12 },
  { id: '狭い#せまい', expression: '狭い', reading: 'せまい', meaning: 'narrow; not spacious', genkiLesson: 12 },
  { id: '多分#たぶん', expression: '多分', reading: 'たぶん', meaning: 'perhaps, probably, maybe', genkiLesson: 12 },
  { id: '歯#は', expression: '歯', reading: 'は', meaning: 'tooth', genkiLesson: 12 },
  { id: '初めて#はじめて', expression: '初めて', reading: 'はじめて', meaning: 'for the first time', genkiLesson: 12 },
  { id: '晴れ#はれ', expression: '晴れ', reading: 'はれ', meaning: 'clear (sunny) weather', genkiLesson: 12 },
  { id: '服#ふく', expression: '服', reading: 'ふく', meaning: 'clothes', genkiLesson: 12 },
  { id: '物#もの', expression: '物', reading: 'もの', meaning: 'thing (concrete object)', genkiLesson: 12 },
  { id: '雪#ゆき', expression: '雪', reading: 'ゆき', meaning: 'snow', genkiLesson: 12 },
  { id: '悪い#わるい', expression: '悪い', reading: 'わるい', meaning: 'bad, sinful; inferior', genkiLesson: 12 },
  { id: '一日#いちにち', expression: '一日', reading: 'いちにち', meaning: 'one day (duration)', genkiLesson: 13 },
  { id: '五日#いつか', expression: '五日', reading: 'いつか', meaning: 'five days; fifth day of the month', genkiLesson: 13 },
  { id: 'おじいさん#おじいさん', expression: 'おじいさん', reading: 'おじいさん', meaning: 'grandfather, male senior citizen', genkiLesson: 13 },
  { id: '大人#おとな', expression: '大人', reading: 'おとな', meaning: 'adult', genkiLesson: 13 },
  { id: '辛い#からい', expression: '辛い', reading: 'からい', meaning: 'hot and spicy; salty', genkiLesson: 13 },
  { id: 'カレー#カレー', expression: 'カレー', reading: 'カレー', meaning: 'curry (abbr. for curry and rice)', genkiLesson: 13 },
  { id: '紅茶#こうちゃ', expression: '紅茶', reading: 'こうちゃ', meaning: 'black tea', genkiLesson: 13 },
  { id: '九日#ここのか', expression: '九日', reading: 'ここのか', meaning: 'nine days; ninth day of the month', genkiLesson: 13 },
  { id: '言葉#ことば', expression: '言葉', reading: 'ことば', meaning: 'language; word(s); expression(s)', genkiLesson: 13 },
  { id: 'セーター#セーター', expression: 'セーター', reading: 'セーター', meaning: 'sweater', genkiLesson: 13 },
  { id: '全部#ぜんぶ', expression: '全部', reading: 'ぜんぶ', meaning: 'all, entire, whole', genkiLesson: 13 },
  { id: '近い#ちかい', expression: '近い', reading: 'ちかい', meaning: 'near, close by, short', genkiLesson: 13 },
  { id: '十日#とおか', expression: '十日', reading: 'とおか', meaning: 'ten days; tenth day of the month', genkiLesson: 13 },
  { id: '七日#なのか', expression: '七日', reading: 'なのか', meaning: 'seven days; seventh day (of the month)', genkiLesson: 13 },
  { id: '二日#ふつか', expression: '二日', reading: 'ふつか', meaning: 'two days; second day of the month', genkiLesson: 13 },
  { id: '磨く#みがく', expression: '磨く', reading: 'みがく', meaning: 'to brush (teeth); to polish', genkiLesson: 13 },
  { id: '店#みせ', expression: '店', reading: 'みせ', meaning: 'store, shop', genkiLesson: 13 },
  { id: '三日#みっか', expression: '三日', reading: 'みっか', meaning: 'three days, third day of the month', genkiLesson: 13 },
  { id: '六日#むいか', expression: '六日', reading: 'むいか', meaning: 'six days; sixth day of month', genkiLesson: 13 },
  { id: '八日#ようか', expression: '八日', reading: 'ようか', meaning: 'eight days; eighth day of the month', genkiLesson: 13 },
  { id: '四日#よっか', expression: '四日', reading: 'よっか', meaning: 'four days; fourth day of the month', genkiLesson: 13 },
  { id: '私#わたくし', expression: '私', reading: 'わたくし', meaning: 'I (formal), myself, private affairs', genkiLesson: 13 },
  { id: '兄#あに', expression: '兄', reading: 'あに', meaning: '(my) older brother (humble)', genkiLesson: 14 },
  { id: '奥さん#おくさん', expression: '奥さん', reading: 'おくさん', meaning: '(someone else\'s) wife (hon.)', genkiLesson: 14 },
  { id: '同じ#おなじ', expression: '同じ', reading: 'おなじ', meaning: 'same, identical', genkiLesson: 14 },
  { id: '去年#きょねん', expression: '去年', reading: 'きょねん', meaning: 'last year', genkiLesson: 14 },
  { id: 'コップ#コップ', expression: 'コップ', reading: 'コップ', meaning: 'a tumbler; a glass', genkiLesson: 14 },
  { id: '時間#じかん', expression: '時間', reading: 'じかん', meaning: 'time', genkiLesson: 14 },
  { id: 'ネクタイ#ネクタイ', expression: 'ネクタイ', reading: 'ネクタイ', meaning: 'tie, necktie', genkiLesson: 14 },
  { id: '母#はは', expression: '母', reading: 'はは', meaning: '(my) mother', genkiLesson: 14 },
  { id: 'よく#よく', expression: 'よく', reading: 'よく', meaning: 'frequently, often (much); well, skillfully', genkiLesson: 14 },
  { id: 'ラジオ#ラジオ', expression: 'ラジオ', reading: 'ラジオ', meaning: 'radio', genkiLesson: 14 },
  { id: '両親#りょうしん', expression: '両親', reading: 'りょうしん', meaning: 'parents (lit., both parents)', genkiLesson: 14 },
  { id: '売る#うる', expression: '売る', reading: 'うる', meaning: 'to sell (v.t.)', genkiLesson: 15 },
  { id: '絵#え', expression: '絵', reading: 'え', meaning: 'a painting; a picture; a drawing', genkiLesson: 15 },
  { id: '映画館#えいがかん', expression: '映画館', reading: 'えいがかん', meaning: 'movie theater, cinema', genkiLesson: 15 },
  { id: '外国人#がいこくじん', expression: '外国人', reading: 'がいこくじん', meaning: 'foreigner', genkiLesson: 15 },
  { id: 'そば#そば', expression: 'そば', reading: 'そば', meaning: 'near, close, beside; Japanese traditional buckwheat noodle', genkiLesson: 15 },
  { id: '地図#ちず', expression: '地図', reading: 'ちず', meaning: 'a map', genkiLesson: 15 },
  { id: '庭#にわ', expression: '庭', reading: 'にわ', meaning: 'garden', genkiLesson: 15 },
  { id: '広い#ひろい', expression: '広い', reading: 'ひろい', meaning: 'spacious; wide; broad', genkiLesson: 15 },
  { id: 'プール#プール', expression: 'プール', reading: 'プール', meaning: 'swimming pool', genkiLesson: 15 },
  { id: 'ペット#ペット', expression: 'ペット', reading: 'ペット', meaning: 'pet', genkiLesson: 15 },
  { id: '汚い#きたない', expression: '汚い', reading: 'きたない', meaning: 'dirty, unclean, filthy', genkiLesson: 16 },
  { id: '困る#こまる', expression: '困る', reading: 'こまる', meaning: 'to be bothered, to have difficulty', genkiLesson: 16 },
  { id: '砂糖#さとう', expression: '砂糖', reading: 'さとう', meaning: 'sugar', genkiLesson: 16 },
  { id: '出す#だす', expression: '出す', reading: 'だす', meaning: 'to take (something) out; to hand in (something)', genkiLesson: 16 },
  { id: '見せる#みせる', expression: '見せる', reading: 'みせる', meaning: 'to show, to display', genkiLesson: 16 },
  { id: '道#みち', expression: '道', reading: 'みち', meaning: 'road, street; way, directions', genkiLesson: 16 },
  { id: '男#おとこ', expression: '男', reading: 'おとこ', meaning: 'man, male', genkiLesson: 17 },
  { id: '女#おんな', expression: '女', reading: 'おんな', meaning: 'woman, female', genkiLesson: 17 },
  { id: '鍵#かぎ', expression: '鍵', reading: 'かぎ', meaning: 'a lock; a key', genkiLesson: 17 },
  { id: '紙#かみ', expression: '紙', reading: 'かみ', meaning: 'paper', genkiLesson: 17 },
  { id: '自分#じぶん', expression: '自分', reading: 'じぶん', meaning: 'myself, oneself', genkiLesson: 17 },
  { id: '少ない#すくない', expression: '少ない', reading: 'すくない', meaning: 'a little; a few', genkiLesson: 17 },
  { id: 'ストーブ#ストーブ', expression: 'ストーブ', reading: 'ストーブ', meaning: 'heater (lit: stove)', genkiLesson: 17 },
  { id: 'する#する', expression: 'する', reading: 'する', meaning: 'to do, to try; to wear small items (e.g., necktie, watch, etc.)', genkiLesson: 17 },
  { id: '強い#つよい', expression: '強い', reading: 'つよい', meaning: 'strong, powerful', genkiLesson: 17 },
  { id: 'ニュース#ニュース', expression: 'ニュース', reading: 'ニュース', meaning: 'news', genkiLesson: 17 },
  { id: '脱ぐ#ぬぐ', expression: '脱ぐ', reading: 'ぬぐ', meaning: 'to take off (clothes)', genkiLesson: 17 },
  { id: '前#まえ', expression: '前', reading: 'まえ', meaning: 'before, in front', genkiLesson: 17 },
  { id: '明るい#あかるい', expression: '明るい', reading: 'あかるい', meaning: 'bright (in reference to personality or weather); cheerful', genkiLesson: 18 },
  { id: '後#あと', expression: '後', reading: 'あと', meaning: 'afterwards (later); in the future; the rest; since then', genkiLesson: 18 },
  { id: '押す#おす', expression: '押す', reading: 'おす', meaning: 'to push, to press, to stamp (e.g., a passport)', genkiLesson: 18 },
  { id: '消える#きえる', expression: '消える', reading: 'きえる', meaning: 'to vanish, to disappear', genkiLesson: 18 },
  { id: '牛乳#ぎゅうにゅう', expression: '牛乳', reading: 'ぎゅうにゅう', meaning: 'milk', genkiLesson: 18 },
  { id: '咲く#さく', expression: '咲く', reading: 'さく', meaning: 'to bloom', genkiLesson: 18 },
  { id: '醤油#しょうゆ', expression: '醤油', reading: 'しょうゆ', meaning: 'soy sauce', genkiLesson: 18 },
  { id: 'スカート#スカート', expression: 'スカート', reading: 'スカート', meaning: 'skirt', genkiLesson: 18 },
  { id: '外#そと', expression: '外', reading: 'そと', meaning: 'outside, exterior', genkiLesson: 18 },
  { id: '頼む#たのむ', expression: '頼む', reading: 'たのむ', meaning: 'to request, to ask (a favor)', genkiLesson: 18 },
  { id: '夕方#ゆうがた', expression: '夕方', reading: 'ゆうがた', meaning: 'late afternoon (typically just before dinner time), evening', genkiLesson: 18 },
  { id: '冷蔵庫#れいぞうこ', expression: '冷蔵庫', reading: 'れいぞうこ', meaning: 'refrigerator', genkiLesson: 18 },
  { id: '一昨日#おととい', expression: '一昨日', reading: 'おととい', meaning: 'the day before yesterday', genkiLesson: 19 },
  { id: 'かける#かける', expression: 'かける', reading: 'かける', meaning: 'to dial/call (e.g., phone); to sit down', genkiLesson: 19 },
  { id: 'なぜ#なぜ', expression: 'なぜ', reading: 'なぜ', meaning: 'why (same as どうして)', genkiLesson: 19 },
  { id: '話#はなし', expression: '話', reading: 'はなし', meaning: 'talk (chat), story', genkiLesson: 19 },
  { id: '晴れる#はれる', expression: '晴れる', reading: 'はれる', meaning: 'to be sunny', genkiLesson: 19 },
  { id: '毎朝#まいあさ', expression: '毎朝', reading: 'まいあさ', meaning: 'every morning', genkiLesson: 19 },
  { id: 'まだ#まだ', expression: 'まだ', reading: 'まだ', meaning: 'yet, still, besides', genkiLesson: 19 },
  { id: '呼ぶ#よぶ', expression: '呼ぶ', reading: 'よぶ', meaning: 'to call (one\'s name); to invite', genkiLesson: 19 },
  { id: 'あちら#あちら', expression: 'あちら', reading: 'あちら', meaning: 'this way (polite)', genkiLesson: 20 },
  { id: '歩く#あるく', expression: '歩く', reading: 'あるく', meaning: 'to walk', genkiLesson: 20 },
  { id: '重い#おもい', expression: '重い', reading: 'おもい', meaning: 'heavy; serious', genkiLesson: 20 },
  { id: '角#かど', expression: '角', reading: 'かど', meaning: 'corner (e.g., desk, pavement)', genkiLesson: 20 },
  { id: 'また#また', expression: 'また', reading: 'また', meaning: 'and; furthermore', genkiLesson: 20 },
  { id: '置く#おく', expression: '置く', reading: 'おく', meaning: 'to put; to lay; to place', genkiLesson: 21 },
  { id: '少し#すこし', expression: '少し', reading: 'すこし', meaning: 'little, few', genkiLesson: 21 },
  { id: '遠い#とおい', expression: '遠い', reading: 'とおい', meaning: 'far (away), distant', genkiLesson: 21 },
  { id: '貼る#はる', expression: '貼る', reading: 'はる', meaning: 'to post; to paste; to attach', genkiLesson: 21 },
  { id: 'やる#やる', expression: 'やる', reading: 'やる', meaning: 'to do; to give (to pets, parents, siblings, etc.)', genkiLesson: 21 },
  { id: 'うるさい#うるさい', expression: 'うるさい', reading: 'うるさい', meaning: 'noisy; annoying', genkiLesson: 22 },
  { id: '風#かぜ', expression: '風', reading: 'かぜ', meaning: 'wind, breeze', genkiLesson: 22 },
  { id: '木#き', expression: '木', reading: 'き', meaning: 'tree, wood, timber', genkiLesson: 22 },
  { id: '走る#はしる', expression: '走る', reading: 'はしる', meaning: 'to run', genkiLesson: 22 },
  { id: '吹く#ふく', expression: '吹く', reading: 'ふく', meaning: 'to blow (wind, etc.)', genkiLesson: 22 },
  { id: '体#からだ', expression: '体', reading: 'からだ', meaning: 'body; health', genkiLesson: 23 },
  { id: '靴下#くつした', expression: '靴下', reading: 'くつした', meaning: 'socks', genkiLesson: 23 },
  { id: '違う#ちがう', expression: '違う', reading: 'ちがう', meaning: 'to be different; to differ; wrong', genkiLesson: 23 },
  { id: 'まずい#まずい', expression: 'まずい', reading: 'まずい', meaning: 'terrible (in reference to food), unappetizing, unpleasant (taste)', genkiLesson: 23 },
  { id: 'ああ#ああ', expression: 'ああ', reading: 'ああ', meaning: 'Ah!, Oh!' },
  { id: '会う#あう', expression: '会う', reading: 'あう', meaning: 'to meet, to see' },
  { id: '青#あお', expression: '青', reading: 'あお', meaning: 'blue' },
  { id: '赤#あか', expression: '赤', reading: 'あか', meaning: 'red' },
  { id: '開く#あく', expression: '開く', reading: 'あく', meaning: 'to open, to become open' },
  { id: '開ける#あける', expression: '開ける', reading: 'あける', meaning: 'to open (v.t.)' },
  { id: '上げる#あげる', expression: '上げる', reading: 'あげる', meaning: 'to raise, to lift' },
  { id: '明後日#あさって', expression: '明後日', reading: 'あさって', meaning: 'day after tomorrow' },
  { id: '足#あし', expression: '足', reading: 'あし', meaning: 'foot; leg' },
  { id: '暖かい#あたたかい', expression: '暖かい', reading: 'あたたかい', meaning: 'warm' },
  { id: '頭#あたま', expression: '頭', reading: 'あたま', meaning: 'head' },
  { id: '厚い#あつい', expression: '厚い', reading: 'あつい', meaning: 'kind, warm(hearted), thick, deep' },
  { id: 'あっち#あっち', expression: 'あっち', reading: 'あっち', meaning: 'over there' },
  { id: 'あの#あの', expression: 'あの', reading: 'あの', meaning: 'that over there; like that, that way; um...' },
  { id: '浴びる#あびる', expression: '浴びる', reading: 'あびる', meaning: 'to bathe, to shower' },
  { id: '危ない#あぶない', expression: '危ない', reading: 'あぶない', meaning: 'dangerous, critical' },
  { id: '余り#あまり', expression: '余り', reading: 'あまり', meaning: 'not very; surplus' },
  { id: '飴#あめ', expression: '飴', reading: 'あめ', meaning: '(hard) candy' },
  { id: '在る#ある', expression: '在る', reading: 'ある', meaning: 'to be, to have' },
  { id: '有る#ある', expression: '有る', reading: 'ある', meaning: 'to be, to have' },
  { id: 'いい#いい', expression: 'いい', reading: 'いい', meaning: 'good', displayReading: 'いい; よい' },
  { id: 'いいえ#いいえ', expression: 'いいえ', reading: 'いいえ', meaning: 'no, not at all' },
  { id: 'いかが#いかが', expression: 'いかが', reading: 'いかが', meaning: 'how, in what way' },
  { id: '行く#いく', expression: '行く', reading: 'いく', meaning: 'to go', displayReading: 'いく; ゆく' },
  { id: 'いくつ#いくつ', expression: 'いくつ', reading: 'いくつ', meaning: 'how many, how old' },
  { id: '池#いけ', expression: '池', reading: 'いけ', meaning: 'pond' },
  { id: '椅子#いす', expression: '椅子', reading: 'いす', meaning: 'chair' },
  { id: '一#いち', expression: '一', reading: 'いち', meaning: 'one' },
  { id: '一緒#いっしょ', expression: '一緒', reading: 'いっしょ', meaning: 'together' },
  { id: '嫌#いや', expression: '嫌', reading: 'いや', meaning: 'disagreeable, detestable, unpleasant' },
  { id: '入口#いりぐち', expression: '入口', reading: 'いりぐち', meaning: 'entrance' },
  { id: '居る#いる', expression: '居る', reading: 'いる', meaning: '(humble) to be (animate), to exist' },
  { id: '要る#いる', expression: '要る', reading: 'いる', meaning: 'to need' },
  { id: '入れる#いれる', expression: '入れる', reading: 'いれる', meaning: 'to put in' },
  { id: '色々#いろいろ', expression: '色々', reading: 'いろいろ', meaning: 'various' },
  { id: '上#うえ', expression: '上', reading: 'うえ', meaning: 'above (up, top, etc.), over, on top of' },
  { id: '後ろ#うしろ', expression: '後ろ', reading: 'うしろ', meaning: 'back, behind, rear' },
  { id: '薄い#うすい', expression: '薄い', reading: 'うすい', meaning: 'thin, weak' },
  { id: '生まれる#うまれる', expression: '生まれる', reading: 'うまれる', meaning: 'to be born' },
  { id: '上着#うわぎ', expression: '上着', reading: 'うわぎ', meaning: 'coat, jacket' },
  { id: 'エレベーター#エレベーター', expression: 'エレベーター', reading: 'エレベーター', meaning: 'elevator' },
  { id: '～円#えん', expression: '～円', reading: 'えん', meaning: 'Yen', displayReading: '～えん', isAffix: true },
  { id: 'お～#お', expression: 'お～', reading: 'お', meaning: 'honorable ~ (honorific)', displayReading: 'お～', isAffix: true },
  { id: '美味しい#おいしい', expression: '美味しい', reading: 'おいしい', meaning: 'delicious, tasty' },
  { id: '多い#おおい', expression: '多い', reading: 'おおい', meaning: 'many; there are a lot' },
  { id: '大きな#おおきな', expression: '大きな', reading: 'おおきな', meaning: 'big' },
  { id: '大勢#おおぜい', expression: '大勢', reading: 'おおぜい', meaning: 'great number of people' },
  { id: 'お皿#おさら', expression: 'お皿', reading: 'おさら', meaning: 'plate, dish' },
  { id: '伯父#おじさん', expression: '伯父', reading: 'おじさん', meaning: 'uncle, middle-aged man' },
  { id: '教える#おしえる', expression: '教える', reading: 'おしえる', meaning: 'to teach, to inform, to instruct' },
  { id: 'おととし#おととし', expression: 'おととし', reading: 'おととし', meaning: 'year before last' },
  { id: 'お腹#おなか', expression: 'お腹', reading: 'おなか', meaning: 'stomach' },
  { id: '伯母さん#おばさん', expression: '伯母さん', reading: 'おばさん', meaning: 'aunt' },
  { id: 'お風呂#おふろ', expression: 'お風呂', reading: 'おふろ', meaning: 'a bath' },
  { id: '覚える#おぼえる', expression: '覚える', reading: 'おぼえる', meaning: 'to learn, to commit to memory, to remember, to memorize' },
  { id: 'おまわりさん#おまわりさん', expression: 'おまわりさん', reading: 'おまわりさん', meaning: 'policeman (friendly term)' },
  { id: '降りる#おりる', expression: '降りる', reading: 'おりる', meaning: 'to get off' },
  { id: '終る#おわる', expression: '終る', reading: 'おわる', meaning: 'to finish, to close' },
  { id: '～回#かい', expression: '～回', reading: 'かい', meaning: 'counter for occurrences (~ times)', displayReading: '～かい', isAffix: true },
  { id: '～階#かい', expression: '～階', reading: 'かい', meaning: 'counter for stories (floors) of a building', displayReading: '～かい', isAffix: true },
  { id: '階段#かいだん', expression: '階段', reading: 'かいだん', meaning: 'stairs' },
  { id: '買う#かう', expression: '買う', reading: 'かう', meaning: 'to buy' },
  { id: '返す#かえす', expression: '返す', reading: 'かえす', meaning: 'to return something' },
  { id: '帰る#かえる', expression: '帰る', reading: 'かえる', meaning: 'to go back, to go home, to return' },
  { id: '書く#かく', expression: '書く', reading: 'かく', meaning: 'to write' },
  { id: '～か月#かげつ', expression: '～か月', reading: 'かげつ', meaning: '(number of) months', displayReading: '～かげつ', isAffix: true },
  { id: '掛ける#かける', expression: '掛ける', reading: 'かける', meaning: 'to put on (e.g., glasses); to hang (e.g., on a wall)' },
  { id: '貸す#かす', expression: '貸す', reading: 'かす', meaning: 'to lend' },
  { id: '方#かた', expression: '方', reading: 'かた', meaning: '-- honorific form for 人 (ひと) --; way of doing' },
  { id: '片仮名#かたかな', expression: '片仮名', reading: 'かたかな', meaning: 'katakana' },
  { id: '～月#がつ', expression: '～月', reading: 'がつ', meaning: 'month of year', displayReading: '～がつ', isAffix: true },
  { id: 'カップ#カップ', expression: 'カップ', reading: 'カップ', meaning: 'cup' },
  { id: '家庭#かてい', expression: '家庭', reading: 'かてい', meaning: 'home; family' },
  { id: '花瓶#かびん', expression: '花瓶', reading: 'かびん', meaning: '(flower) vase' },
  { id: '借りる#かりる', expression: '借りる', reading: 'かりる', meaning: 'to borrow, to owe' },
  { id: '～がる#がる', expression: '～がる', reading: 'がる', meaning: 'feel', displayReading: '～がる', isAffix: true },
  { id: '軽い#かるい', expression: '軽い', reading: 'かるい', meaning: 'light, non-serious, minor' },
  { id: 'カレンダー#カレンダー', expression: 'カレンダー', reading: 'カレンダー', meaning: 'calendar' },
  { id: '川#かわ', expression: '川', reading: 'かわ', meaning: 'river' },
  { id: '～側#がわ', expression: '～側', reading: 'がわ', meaning: '~ side', displayReading: '～がわ', isAffix: true },
  { id: '可愛い#かわいい', expression: '可愛い', reading: 'かわいい', meaning: 'cute, adorable' },
  { id: '黄色#きいろ', expression: '黄色', reading: 'きいろ', meaning: 'yellow' },
  { id: '黄色い#きいろい', expression: '黄色い', reading: 'きいろい', meaning: 'yellow' },
  { id: '聞く#きく', expression: '聞く', reading: 'きく', meaning: 'to hear, to listen, to ask' },
  { id: '北#きた', expression: '北', reading: 'きた', meaning: 'north' },
  { id: '九#きゅう', expression: '九', reading: 'きゅう', meaning: 'nine' },
  { id: '牛肉#ぎゅうにく', expression: '牛肉', reading: 'ぎゅうにく', meaning: 'beef' },
  { id: '教室#きょうしつ', expression: '教室', reading: 'きょうしつ', meaning: 'classroom' },
  { id: '嫌い#きらい', expression: '嫌い', reading: 'きらい', meaning: 'dislike' },
  { id: '綺麗#きれい', expression: '綺麗', reading: 'きれい', meaning: 'pretty, clean, tidy' },
  { id: 'キロ#キロ', expression: 'キロ', reading: 'キロ', meaning: '(abbr.) kilo (kilogram)', displayReading: 'キロ; キログラム' },
  { id: '九#く', expression: '九', reading: 'く', meaning: 'nine' },
  { id: '下さい#ください', expression: '下さい', reading: 'ください', meaning: '(with te-form verb) please do for me' },
  { id: '果物#くだもの', expression: '果物', reading: 'くだもの', meaning: 'fruit' },
  { id: '口#くち', expression: '口', reading: 'くち', meaning: 'job opening; mouth' },
  { id: '曇る#くもる', expression: '曇る', reading: 'くもる', meaning: 'to become cloudy, to become dim' },
  { id: '暗い#くらい', expression: '暗い', reading: 'くらい', meaning: 'dark, gloomy' },
  { id: '～くらい#くらい', expression: '～くらい', reading: 'くらい', meaning: 'approximate (quantity)', displayReading: '～くらい; ぐらい', isAffix: true },
  { id: 'グラム#グラム', expression: 'グラム', reading: 'グラム', meaning: 'gram' },
  { id: '来る#くる', expression: '来る', reading: 'くる', meaning: 'to come' },
  { id: '黒#くろ', expression: '黒', reading: 'くろ', meaning: 'black' },
  { id: '警官#けいかん', expression: '警官', reading: 'けいかん', meaning: 'police officer' },
  { id: '消す#けす', expression: '消す', reading: 'けす', meaning: 'to erase, to delete, to turn off power' },
  { id: '結構#けっこう', expression: '結構', reading: 'けっこう', meaning: 'splendid; enough, tolerably' },
  { id: '結婚#けっこん', expression: '結婚', reading: 'けっこん', meaning: 'marriage (get married)', displayReading: 'けっこん (する)' },
  { id: '玄関#げんかん', expression: '玄関', reading: 'げんかん', meaning: 'entrance (to a house or a building)' },
  { id: '元気#げんき', expression: '元気', reading: 'げんき', meaning: 'health(y), energetic' },
  { id: '～個#こ', expression: '～個', reading: 'こ', meaning: 'counter for small items (e.g., fruits, cups)', displayReading: '～こ', isAffix: true },
  { id: '五#ご', expression: '五', reading: 'ご', meaning: 'five' },
  { id: '～語#ご', expression: '～語', reading: 'ご', meaning: 'word, language', displayReading: '～ご', isAffix: true },
  { id: '交差点#こうさてん', expression: '交差点', reading: 'こうさてん', meaning: 'intersection' },
  { id: '交番#こうばん', expression: '交番', reading: 'こうばん', meaning: 'police box' },
  { id: '声#こえ', expression: '声', reading: 'こえ', meaning: 'voice' },
  { id: 'コート#コート', expression: 'コート', reading: 'コート', meaning: 'coat; court (e.g., tennis)' },
  { id: '答える#こたえる', expression: '答える', reading: 'こたえる', meaning: 'to answer, to reply' },
  { id: 'こっち#こっち', expression: 'こっち', reading: 'こっち', meaning: 'this person; this direction; this side' },
  { id: 'この#この', expression: 'この', reading: 'この', meaning: 'this' },
  { id: 'コピーする#コピーする', expression: 'コピーする', reading: 'コピーする', meaning: 'to copy' },
  { id: '～ころ#ころ', expression: '～ころ', reading: 'ころ', meaning: 'about, toward, approximately (time)', displayReading: '～ころ; ～ごろ', isAffix: true },
  { id: 'こんな#こんな', expression: 'こんな', reading: 'こんな', meaning: 'such, like this' },
  { id: 'さあ#さあ', expression: 'さあ', reading: 'さあ', meaning: 'come now, well' },
  { id: '～歳#さい', expression: '～歳', reading: 'さい', meaning: '~ years old', displayReading: '～さい', isAffix: true },
  { id: '先#さき', expression: '先', reading: 'さき', meaning: 'future; recent, previous' },
  { id: '差す#さす', expression: '差す', reading: 'さす', meaning: 'to raise (stretch out) hands, to raise (e.g., umbrella)' },
  { id: '～冊#さつ', expression: '～冊', reading: 'さつ', meaning: 'counter for books', displayReading: '～さつ', isAffix: true },
  { id: 'さ来年#さらいねん', expression: 'さ来年', reading: 'さらいねん', meaning: 'year after next' },
  { id: '～さん#さん', expression: '～さん', reading: 'さん', meaning: 'Mr. ~, Ms. ~', displayReading: '～さん', isAffix: true },
  { id: '三#さん', expression: '三', reading: 'さん', meaning: 'three' },
  { id: '散歩#さんぽ', expression: '散歩', reading: 'さんぽ', meaning: 'walk, stroll', displayReading: 'さんぽ (する)' },
  { id: '四#し', expression: '四', reading: 'し', meaning: 'four' },
  { id: '～時#じ', expression: '～時', reading: 'じ', meaning: '~ o\'clock (time)', displayReading: '～じ', isAffix: true },
  { id: '塩#しお', expression: '塩', reading: 'しお', meaning: 'salt' },
  { id: 'しかし#しかし', expression: 'しかし', reading: 'しかし', meaning: 'however; but' },
  { id: '～時間#じかん', expression: '～時間', reading: 'じかん', meaning: '~ hours', displayReading: '～じかん', isAffix: true },
  { id: '静か#しずか', expression: '静か', reading: 'しずか', meaning: 'quiet, calm' },
  { id: '下#した', expression: '下', reading: 'した', meaning: 'under, below, beneath' },
  { id: '七#しち', expression: '七', reading: 'しち', meaning: 'seven' },
  { id: '質問#しつもん', expression: '質問', reading: 'しつもん', meaning: 'question, inquiry' },
  { id: '自動車#じどうしゃ', expression: '自動車', reading: 'じどうしゃ', meaning: 'automobile' },
  { id: '字引#じびき', expression: '字引', reading: 'じびき', meaning: 'dictionary' },
  { id: '閉まる#しまる', expression: '閉まる', reading: 'しまる', meaning: 'to close, to be closed' },
  { id: '閉める#しめる', expression: '閉める', reading: 'しめる', meaning: 'to close, to shut' },
  { id: '締める#しめる', expression: '締める', reading: 'しめる', meaning: 'to tie, to fasten, to tighten' },
  { id: 'じゃ#じゃ', expression: 'じゃ', reading: 'じゃ', meaning: 'well, well then', displayReading: 'じゃ; じゃあ' },
  { id: 'シャワー#シャワー', expression: 'シャワー', reading: 'シャワー', meaning: 'shower' },
  { id: '十#じゅう', expression: '十', reading: 'じゅう', meaning: 'ten' },
  { id: '～中#じゅう', expression: '～中', reading: 'じゅう', meaning: 'during, while', displayReading: '～じゅう', isAffix: true },
  { id: '～週間#しゅうかん', expression: '～週間', reading: 'しゅうかん', meaning: '~ weeks', displayReading: '～しゅうかん', isAffix: true },
  { id: '上手#じょうず', expression: '上手', reading: 'じょうず', meaning: 'be good at, skillful' },
  { id: '丈夫#じょうぶ', expression: '丈夫', reading: 'じょうぶ', meaning: 'strong, solid, durable' },
  { id: '白#しろ', expression: '白', reading: 'しろ', meaning: 'white' },
  { id: '～人#じん', expression: '～人', reading: 'じん', meaning: 'counter for people', displayReading: '～じん', isAffix: true },
  { id: '吸う#すう', expression: '吸う', reading: 'すう', meaning: 'to breathe in, to suck' },
  { id: '好き#すき', expression: '好き', reading: 'すき', meaning: 'liking, fondness, love' },
  { id: '～すぎ#すぎ', expression: '～すぎ', reading: 'すぎ', meaning: 'past; to exceed, ~ too much', displayReading: '～すぎ', isAffix: true },
  { id: 'すぐに#すぐに', expression: 'すぐに', reading: 'すぐに', meaning: 'immediately, soon' },
  { id: '～ずつ#ずつ', expression: '～ずつ', reading: 'ずつ', meaning: 'at a time', displayReading: '～ずつ', isAffix: true },
  { id: 'スプーン#スプーン', expression: 'スプーン', reading: 'スプーン', meaning: 'spoon' },
  { id: 'ズボン#ズボン', expression: 'ズボン', reading: 'ズボン', meaning: 'trousers' },
  { id: '住む#すむ', expression: '住む', reading: 'すむ', meaning: 'to reside, to live in' },
  { id: '座る#すわる', expression: '座る', reading: 'すわる', meaning: 'to sit' },
  { id: '背#せい', expression: '背', reading: 'せい', meaning: '(one\'s) height, stature' },
  { id: '生徒#せいと', expression: '生徒', reading: 'せいと', meaning: 'student; pupil' },
  { id: '石鹸#せっけん', expression: '石鹸', reading: 'せっけん', meaning: 'soap' },
  { id: '背広#せびろ', expression: '背広', reading: 'せびろ', meaning: 'men\'s suit' },
  { id: 'ゼロ#ゼロ', expression: 'ゼロ', reading: 'ゼロ', meaning: 'zero' },
  { id: '千#せん', expression: '千', reading: 'せん', meaning: 'thousand' },
  { id: '洗濯#せんたく', expression: '洗濯', reading: 'せんたく', meaning: 'washing, laundry' },
  { id: 'そう#そう', expression: 'そう', reading: 'そう', meaning: 'yes; appears, to be the case', displayReading: 'そう; そうです' },
  { id: '掃除#そうじ', expression: '掃除', reading: 'そうじ', meaning: 'cleaning, sweeping', displayReading: 'そうじ (する)' },
  { id: 'そうして#そうして', expression: 'そうして', reading: 'そうして', meaning: 'and, like that', displayReading: 'そうして; そして' },
  { id: 'そちら#そちら', expression: 'そちら', reading: 'そちら', meaning: 'over there' },
  { id: 'そっち#そっち', expression: 'そっち', reading: 'そっち', meaning: 'over there' },
  { id: 'その#その', expression: 'その', reading: 'その', meaning: 'that' },
  { id: '空#そら', expression: '空', reading: 'そら', meaning: 'sky' },
  { id: 'それから#それから', expression: 'それから', reading: 'それから', meaning: 'and then, after that' },
  { id: 'それでは#それでは', expression: 'それでは', reading: 'それでは', meaning: 'in that situation, well then...' },
  { id: '～台#だい', expression: '～台', reading: 'だい', meaning: 'counter for vehicles; machines', displayReading: '～だい', isAffix: true },
  { id: '大使館#たいしかん', expression: '大使館', reading: 'たいしかん', meaning: 'embassy' },
  { id: '大好き#だいすき', expression: '大好き', reading: 'だいすき', meaning: 'very like-able, like very much' },
  { id: '大切#たいせつ', expression: '大切', reading: 'たいせつ', meaning: 'important' },
  { id: '台所#だいどころ', expression: '台所', reading: 'だいどころ', meaning: 'kitchen' },
  { id: '大変#たいへん', expression: '大変', reading: 'たいへん', meaning: 'very; difficult, hard' },
  { id: '～だけ#だけ', expression: '～だけ', reading: 'だけ', meaning: 'only ~, just ~, as ~', displayReading: '～だけ', isAffix: true },
  { id: '沢山#たくさん', expression: '沢山', reading: 'たくさん', meaning: 'many, much' },
  { id: 'タクシー#タクシー', expression: 'タクシー', reading: 'タクシー', meaning: 'taxi' },
  { id: '～たち#たち', expression: '～たち', reading: 'たち', meaning: 'plural suffix', displayReading: '～たち', isAffix: true },
  { id: 'たて#たて', expression: 'たて', reading: 'たて', meaning: 'length, height' },
  { id: '建物#たてもの', expression: '建物', reading: 'たてもの', meaning: 'building' },
  { id: 'たばこ#たばこ', expression: 'たばこ', reading: 'たばこ', meaning: 'tobacco, cigarettes' },
  { id: '食べる#たべる', expression: '食べる', reading: 'たべる', meaning: 'to eat' },
  { id: '卵#たまご', expression: '卵', reading: 'たまご', meaning: 'egg' },
  { id: '誰か#だれか', expression: '誰か', reading: 'だれか', meaning: 'someone' },
  { id: '段々#だんだん', expression: '段々', reading: 'だんだん', meaning: 'gradually, by degrees' },
  { id: '小さな#ちいさな', expression: '小さな', reading: 'ちいさな', meaning: 'small, little' },
  { id: '近く#ちかく', expression: '近く', reading: 'ちかく', meaning: 'nearby; in the neighborhood' },
  { id: '茶色#ちゃいろ', expression: '茶色', reading: 'ちゃいろ', meaning: 'brown' },
  { id: '茶碗#ちゃわん', expression: '茶碗', reading: 'ちゃわん', meaning: 'rice bowl' },
  { id: '～中#ちゅう', expression: '～中', reading: 'ちゅう', meaning: 'during, while ~ing', displayReading: '～ちゅう', isAffix: true },
  { id: '丁度#ちょうど', expression: '丁度', reading: 'ちょうど', meaning: 'just, right, exactly' },
  { id: '一日#ついたち', expression: '一日', reading: 'ついたち', meaning: 'one day; first day of the month' },
  { id: '使う#つかう', expression: '使う', reading: 'つかう', meaning: 'to use' },
  { id: '着く#つく', expression: '着く', reading: 'つく', meaning: 'to arrive at, to reach' },
  { id: 'つける#つける', expression: 'つける', reading: 'つける', meaning: 'to turn on (e.g., a light); to take' },
  { id: '勤める#つとめる', expression: '勤める', reading: 'つとめる', meaning: 'to work (for)' },
  { id: '手#て', expression: '手', reading: 'て', meaning: 'hand' },
  { id: 'テープレコーダー#テープレコーダー', expression: 'テープレコーダー', reading: 'テープレコーダー', meaning: 'tape recorder' },
  { id: 'テーブル#テーブル', expression: 'テーブル', reading: 'テーブル', meaning: 'table' },
  { id: 'できる#できる', expression: 'できる', reading: 'できる', meaning: 'to be able to (to accomplish)' },
  { id: '出口#でぐち', expression: '出口', reading: 'でぐち', meaning: 'an exit' },
  { id: 'では#では', expression: 'では', reading: 'では', meaning: 'then, well, so' },
  { id: 'でも#でも', expression: 'でも', reading: 'でも', meaning: 'but, however' },
  { id: '出る#でる', expression: '出る', reading: 'でる', meaning: 'to appear, to leave' },
  { id: '戸#と', expression: '戸', reading: 'と', meaning: 'door (Japanese style)' },
  { id: '～度#ど', expression: '～度', reading: 'ど', meaning: 'counter for occurrences; ~ degree; ~ point', displayReading: '～ど', isAffix: true },
  { id: 'ドア#ドア', expression: 'ドア', reading: 'ドア', meaning: 'door (Western style)' },
  { id: 'トイレ#トイレ', expression: 'トイレ', reading: 'トイレ', meaning: 'bathroom; toilet' },
  { id: 'どう#どう', expression: 'どう', reading: 'どう', meaning: 'how, in what way' },
  { id: 'どうぞ#どうぞ', expression: 'どうぞ', reading: 'どうぞ', meaning: 'please, kindly, by all means' },
  { id: '動物#どうぶつ', expression: '動物', reading: 'どうぶつ', meaning: 'animal' },
  { id: '～時#とき', expression: '～時', reading: 'とき', meaning: 'at the time of ~', displayReading: '～とき', isAffix: true },
  { id: '年#とし', expression: '年', reading: 'とし', meaning: 'year, age' },
  { id: 'どなた#どなた', expression: 'どなた', reading: 'どなた', meaning: 'who' },
  { id: '隣#となり', expression: '隣', reading: 'となり', meaning: 'next to, next door to' },
  { id: 'どの#どの', expression: 'どの', reading: 'どの', meaning: 'which' },
  { id: '飛ぶ#とぶ', expression: '飛ぶ', reading: 'とぶ', meaning: 'to fly, to hop' },
  { id: '止まる#とまる', expression: '止まる', reading: 'とまる', meaning: 'to come to a halt' },
  { id: '鳥#とり', expression: '鳥', reading: 'とり', meaning: 'chicken (lit., bird)' },
  { id: '鶏肉#とりにく', expression: '鶏肉', reading: 'とりにく', meaning: 'chicken meat' },
  { id: '撮る#とる', expression: '撮る', reading: 'とる', meaning: 'to take (a photo), to make (a film)' },
  { id: 'どんな#どんな', expression: 'どんな', reading: 'どんな', meaning: 'what, what kind of' },
  { id: 'ない#ない', expression: 'ない', reading: 'ない', meaning: 'there isn\'t, doesn\'t have' },
  { id: 'ナイフ#ナイフ', expression: 'ナイフ', reading: 'ナイフ', meaning: 'knife' },
  { id: '中#なか', expression: '中', reading: 'なか', meaning: 'inside, middle, among' },
  { id: '鳴く#なく', expression: '鳴く', reading: 'なく', meaning: 'to make sound (animal)' },
  { id: '無くす#なくす', expression: '無くす', reading: 'なくす', meaning: 'to lose something' },
  { id: '夏休み#なつやすみ', expression: '夏休み', reading: 'なつやすみ', meaning: 'summer vacation' },
  { id: '～など#など', expression: '～など', reading: 'など', meaning: 'et cetera', displayReading: '～など', isAffix: true },
  { id: '並ぶ#ならぶ', expression: '並ぶ', reading: 'ならぶ', meaning: 'to line up, to stand in a line (v.i.)' },
  { id: '並べる#ならべる', expression: '並べる', reading: 'ならべる', meaning: 'to put (things) side by side; to line up' },
  { id: '何～#なん', expression: '何～', reading: 'なん', meaning: 'what sort of ~', displayReading: 'なん～', isAffix: true },
  { id: '二#に', expression: '二', reading: 'に', meaning: 'two' },
  { id: 'にぎやか#にぎやか', expression: 'にぎやか', reading: 'にぎやか', meaning: 'bustling, busy' },
  { id: '西#にし', expression: '西', reading: 'にし', meaning: 'west' },
  { id: '～日#にち', expression: '～日', reading: 'にち', meaning: '~ day of the month, for ~ days', displayReading: '～にち', isAffix: true },
  { id: '～人#にん', expression: '～人', reading: 'にん', meaning: 'counter for people', displayReading: '～にん', isAffix: true },
  { id: '温い#ぬるい', expression: '温い', reading: 'ぬるい', meaning: 'lukewarm' },
  { id: '～年#ねん', expression: '～年', reading: 'ねん', meaning: '~ years', displayReading: '～ねん', isAffix: true },
  { id: '登る#のぼる', expression: '登る', reading: 'のぼる', meaning: 'to climb' },
  { id: '飲む#のむ', expression: '飲む', reading: 'のむ', meaning: 'to drink' },
  { id: '乗る#のる', expression: '乗る', reading: 'のる', meaning: 'to get on, to ride in, to board' },
  { id: '～杯#はい', expression: '～杯', reading: 'はい', meaning: 'counter for cupfuls', displayReading: '～はい', isAffix: true },
  { id: '灰皿#はいざら', expression: '灰皿', reading: 'はいざら', meaning: 'ashtray' },
  { id: '入る#はいる', expression: '入る', reading: 'はいる', meaning: 'to enter, to contain, to hold' },
  { id: '箱#はこ', expression: '箱', reading: 'はこ', meaning: 'box' },
  { id: '橋#はし', expression: '橋', reading: 'はし', meaning: 'bridge' },
  { id: '初め#はじめ', expression: '初め', reading: 'はじめ', meaning: 'beginning, start' },
  { id: 'バター#バター', expression: 'バター', reading: 'バター', meaning: 'butter' },
  { id: '二十歳#はたち', expression: '二十歳', reading: 'はたち', meaning: '20 years old' },
  { id: '八#はち', expression: '八', reading: 'はち', meaning: 'eight' },
  { id: '二十日#はつか', expression: '二十日', reading: 'はつか', meaning: 'twenty days, twentieth (day of the month)' },
  { id: '花#はな', expression: '花', reading: 'はな', meaning: 'flower' },
  { id: '鼻#はな', expression: '鼻', reading: 'はな', meaning: 'nose' },
  { id: '話す#はなす', expression: '話す', reading: 'はなす', meaning: 'to speak' },
  { id: '晩#ばん', expression: '晩', reading: 'ばん', meaning: 'evening' },
  { id: '～番#ばん', expression: '～番', reading: 'ばん', meaning: '~st; ~th best', displayReading: '～ばん', isAffix: true },
  { id: 'ハンカチ#ハンカチ', expression: 'ハンカチ', reading: 'ハンカチ', meaning: 'handkerchief' },
  { id: '半分#はんぶん', expression: '半分', reading: 'はんぶん', meaning: 'half' },
  { id: '東#ひがし', expression: '東', reading: 'ひがし', meaning: 'east' },
  { id: '～匹#ひき', expression: '～匹', reading: 'ひき', meaning: 'counter for small animals', displayReading: '～ひき', isAffix: true },
  { id: '引く#ひく', expression: '引く', reading: 'ひく', meaning: 'to pull, to draw; subtract' },
  { id: '低い#ひくい', expression: '低い', reading: 'ひくい', meaning: 'short, low' },
  { id: '左#ひだり', expression: '左', reading: 'ひだり', meaning: 'left hand side' },
  { id: '一月#ひとつき', expression: '一月', reading: 'ひとつき', meaning: 'one month' },
  { id: '暇#ひま', expression: '暇', reading: 'ひま', meaning: 'free time, leisure' },
  { id: '百#ひゃく', expression: '百', reading: 'ひゃく', meaning: 'hundred' },
  { id: '平仮名#ひらがな', expression: '平仮名', reading: 'ひらがな', meaning: 'hiragana' },
  { id: '昼#ひる', expression: '昼', reading: 'ひる', meaning: 'noon, daytime' },
  { id: 'フィルム#フィルム', expression: 'フィルム', reading: 'フィルム', meaning: 'film (roll of)' },
  { id: '封筒#ふうとう', expression: '封筒', reading: 'ふうとう', meaning: 'envelope' },
  { id: 'フォーク#フォーク', expression: 'フォーク', reading: 'フォーク', meaning: 'fork' },
  { id: '豚肉#ぶたにく', expression: '豚肉', reading: 'ぶたにく', meaning: 'pork' },
  { id: '太い#ふとい', expression: '太い', reading: 'ふとい', meaning: 'fat, thick' },
  { id: '降る#ふる', expression: '降る', reading: 'ふる', meaning: 'to precipitate, to fall (e.g., rain, snow, etc.)' },
  { id: '～分#ふん', expression: '～分', reading: 'ふん', meaning: '~ minutes', displayReading: '～ふん', isAffix: true },
  { id: '文章#ぶんしょう', expression: '文章', reading: 'ぶんしょう', meaning: 'sentence, text' },
  { id: '下手#へた', expression: '下手', reading: 'へた', meaning: 'unskillful, poor' },
  { id: 'ベッド#ベッド', expression: 'ベッド', reading: 'ベッド', meaning: 'bed' },
  { id: '辺#へん', expression: '辺', reading: 'へん', meaning: 'area, vicinity' },
  { id: '勉強#べんきょう', expression: '勉強', reading: 'べんきょう', meaning: 'study', displayReading: 'べんきょう (する)' },
  { id: '便利#べんり', expression: '便利', reading: 'べんり', meaning: 'convenient, handy' },
  { id: 'ボールペン#ボールペン', expression: 'ボールペン', reading: 'ボールペン', meaning: 'ball-point pen' },
  { id: '外#ほか', expression: '外', reading: 'ほか', meaning: 'other, the rest' },
  { id: 'ポケット#ポケット', expression: 'ポケット', reading: 'ポケット', meaning: 'pocket' },
  { id: '欲しい#ほしい', expression: '欲しい', reading: 'ほしい', meaning: 'to want, in need of' },
  { id: 'ポスト#ポスト', expression: 'ポスト', reading: 'ポスト', meaning: 'mailbox; post, position' },
  { id: '細い#ほそい', expression: '細い', reading: 'ほそい', meaning: 'thin, slender, fine' },
  { id: 'ボタン#ボタン', expression: 'ボタン', reading: 'ボタン', meaning: 'button' },
  { id: '～本#ほん', expression: '～本', reading: 'ほん', meaning: 'counter for long cylindrical things', displayReading: '～ほん', isAffix: true },
  { id: '本棚#ほんだな', expression: '本棚', reading: 'ほんだな', meaning: 'bookshelf' },
  { id: '本当#ほんとう', expression: '本当', reading: 'ほんとう', meaning: 'real, true' },
  { id: '～枚#まい', expression: '～枚', reading: 'まい', meaning: 'counter for flat things', displayReading: '～まい', isAffix: true },
  { id: '毎月#まいげつ', expression: '毎月', reading: 'まいげつ', meaning: 'every month, monthly', displayReading: 'まいげつ; まいつき' },
  { id: '毎年#まいねん', expression: '毎年', reading: 'まいねん', meaning: 'every year, yearly, annually', displayReading: 'まいねん; まいとし' },
  { id: '～前#まえ', expression: '～前', reading: 'まえ', meaning: 'in front of ~', displayReading: '～まえ', isAffix: true },
  { id: '曲る#まがる', expression: '曲る', reading: 'まがる', meaning: 'to turn, to bend' },
  { id: '待つ#まつ', expression: '待つ', reading: 'まつ', meaning: 'to wait' },
  { id: 'まっすぐ#まっすぐ', expression: 'まっすぐ', reading: 'まっすぐ', meaning: 'straight (ahead), direct' },
  { id: 'マッチ#マッチ', expression: 'マッチ', reading: 'マッチ', meaning: 'match' },
  { id: '丸い#まるい', expression: '丸い', reading: 'まるい', meaning: 'round, circular' },
  { id: '万#まん', expression: '万', reading: 'まん', meaning: 'ten thousand' },
  { id: '万年筆#まんねんひつ', expression: '万年筆', reading: 'まんねんひつ', meaning: 'fountain pen' },
  { id: '右#みぎ', expression: '右', reading: 'みぎ', meaning: 'right hand side' },
  { id: '緑#みどり', expression: '緑', reading: 'みどり', meaning: 'green' },
  { id: '皆さん#みなさん', expression: '皆さん', reading: 'みなさん', meaning: 'all of you, everyone' },
  { id: '南#みなみ', expression: '南', reading: 'みなみ', meaning: 'South' },
  { id: '耳#みみ', expression: '耳', reading: 'みみ', meaning: 'ear' },
  { id: '見る#みる', expression: '見る', reading: 'みる', meaning: 'to see, to look' },
  { id: '向こう#むこう', expression: '向こう', reading: 'むこう', meaning: 'beyond, over there' },
  { id: '村#むら', expression: '村', reading: 'むら', meaning: 'village' },
  { id: 'メートル#メートル', expression: 'メートル', reading: 'メートル', meaning: 'meter' },
  { id: '持つ#もつ', expression: '持つ', reading: 'もつ', meaning: 'to hold, to carry; to possess' },
  { id: '門#もん', expression: '門', reading: 'もん', meaning: 'gate' },
  { id: '問題#もんだい', expression: '問題', reading: 'もんだい', meaning: 'a problem' },
  { id: '～屋#や', expression: '～屋', reading: 'や', meaning: '~ shop', displayReading: '～や', isAffix: true },
  { id: '八百屋#やおや', expression: '八百屋', reading: 'やおや', meaning: 'greengrocer' },
  { id: '易しい#やさしい', expression: '易しい', reading: 'やさしい', meaning: 'easy, plain, simple' },
  { id: '休む#やすむ', expression: '休む', reading: 'やすむ', meaning: 'to rest, to have a break, to get time off' },
  { id: '夕飯#ゆうはん', expression: '夕飯', reading: 'ゆうはん', meaning: 'dinner, supper, evening meal' },
  { id: '昨夜#ゆうべ', expression: '昨夜', reading: 'ゆうべ', meaning: 'last night' },
  { id: '有名#ゆうめい', expression: '有名', reading: 'ゆうめい', meaning: 'famous' },
  { id: 'ゆっくりと#ゆっくりと', expression: 'ゆっくりと', reading: 'ゆっくりと', meaning: 'slowly, at ease' },
  { id: '洋服#ようふく', expression: '洋服', reading: 'ようふく', meaning: 'Western-style clothes' },
  { id: '横#よこ', expression: '横', reading: 'よこ', meaning: 'beside; side; width' },
  { id: '読む#よむ', expression: '読む', reading: 'よむ', meaning: 'to read' },
  { id: '弱い#よわい', expression: '弱い', reading: 'よわい', meaning: 'weak' },
  { id: 'ラジオカセ#ラジオカセ', expression: 'ラジオカセ', reading: 'ラジオカセ', meaning: 'radio cassette player' },
  { id: 'りっぱ#りっぱ', expression: 'りっぱ', reading: 'りっぱ', meaning: 'splendid, fine' },
  { id: '料理#りょうり', expression: '料理', reading: 'りょうり', meaning: 'cooking; cuisine' },
  { id: '零#れい', expression: '零', reading: 'れい', meaning: 'zero, nought' },
  { id: 'レコード#レコード', expression: 'レコード', reading: 'レコード', meaning: 'record' },
  { id: '練習#れんしゅう', expression: '練習', reading: 'れんしゅう', meaning: '(to) practice', displayReading: 'れんしゅう (する)' },
  { id: '廊下#ろうか', expression: '廊下', reading: 'ろうか', meaning: 'corridor' },
  { id: '六#ろく', expression: '六', reading: 'ろく', meaning: 'six' },
  { id: 'ワイシャツ#ワイシャツ', expression: 'ワイシャツ', reading: 'ワイシャツ', meaning: 'shirt (lit: white shirt), business shirt' },
  { id: '分かる#わかる', expression: '分かる', reading: 'わかる', meaning: 'to understand' },
  { id: '忘れる#わすれる', expression: '忘れる', reading: 'わすれる', meaning: 'to forget' },
  { id: '渡す#わたす', expression: '渡す', reading: 'わたす', meaning: 'to hand (something) over (v.t.); to get across' },
  { id: '渡る#わたる', expression: '渡る', reading: 'わたる', meaning: 'to cross over, to go across' },
];

export const VOCAB_N5_BY_ID: ReadonlyMap<string, VocabEntry> = new Map(
  VOCAB_N5.map((entry) => [entry.id, entry]),
);

/** knowledge_items.key に入る形。型が VOCABULARY なので接頭辞で衝突しない。 */
export function vocabKey(id: string): string {
  return `vocab_${id}`;
}

export function vocabOfKey(key: string): VocabEntry | undefined {
  return key.startsWith('vocab_')
    ? VOCAB_N5_BY_ID.get(key.slice('vocab_'.length))
    : undefined;
}
